-- ============================================================================
-- BatCaverna — Migration 011 (Parte 3 de 5): Mapeamentos Lote 2/3
-- ============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS _mapa_taxonomia_temp (
  materia   TEXT NOT NULL,
  antigo    TEXT NOT NULL,
  canonico  TEXT NOT NULL
);

INSERT INTO _mapa_taxonomia_temp (materia, antigo, canonico) VALUES
('História', 'Nova República e Planos Econômicos', 'Brasil República'),
('História', 'Obras públicas no Nordeste / Açude Itans', 'Obras Públicas no Nordeste'),
('História', 'Ocupação da Amazônia / Ferrovia Madeira-Mamoré', 'Ocupação da Amazônia'),
('História', 'Patrimônio e Tradição Cultural (Cavalgada de Sant''Ana)', 'Patrimônio'),
('História', 'Período Colonial e Bandeirantismo', 'Brasil Colônia'),
('História', 'Período Regencial e Grupos Políticos', 'Brasil Império'),
('História', 'Primeira Guerra Mundial e Imprensa (''Gripe Espanhola'')', 'Guerras Mundiais'),
('História', 'Primeira República e Movimento Operário', 'Brasil República'),
('História', 'Processo de Independência do Brasil e Atuação Feminina', 'Brasil Império'),
('História', 'Redemocratização do Brasil (Nova República)', 'Brasil República'),
('História', 'Relações Atlânticas e Comércio Colonial', 'Brasil Colônia'),
('História', 'República Velha e Coronelismo', 'Brasil República'),
('História', 'Revoluções e Direitos Modernos', 'Revoluções'),
('História', 'Roma Antiga - Luta de Classes (Patrícios vs. Plebeus)', 'Idade Antiga'),
('História', 'Saúde Pública na República Velha / Divisão do Trabalho', 'Brasil República'),
('História', 'Segunda Guerra Mundial e Atuação do Brasil', 'Guerras Mundiais'),
('História', 'Segundo Reinado / Leitura e imprensa feminina', 'Brasil Império'),
('Inglês', 'Adjectives / Degrees of Comparison', 'Adjectives and Adverbs'),
('Inglês', 'Adjetivos (Comparativo e Superlativo)', 'Comparatives and Superlatives'),
('Inglês', 'Antônimos e Vocabulário', 'Vocabulary'),
('Inglês', 'Análise Comparativa de Textos', 'Reading Comprehension'),
('Inglês', 'Análise Crítica e Leitura de Carta do Leitor', 'Reading Comprehension'),
('Inglês', 'Análise Gramatical / Orações Condicionais', 'Conditionals'),
('Inglês', 'Análise Gramatical Textual', 'Reading Comprehension'),
('Inglês', 'Análise Literária e Poesia', 'Reading Comprehension'),
('Inglês', 'Análise Poética e Conectividade Humana', 'Reading Comprehension'),
('Inglês', 'Análise Poética e Identidade', 'Reading Comprehension'),
('Inglês', 'Análise de Cartum e Crítica Social no Trabalho', 'Reading Comprehension'),
('Inglês', 'Análise de Imagem / Publicidade', 'Reading Comprehension'),
('Inglês', 'Artigos e Preposições', 'Prepositions'),
('Inglês', 'Caso Genitivo e Pronomes', 'Pronouns'),
('Inglês', 'Classes Gramaticais e Morfologia', 'Gramática e Estrutura da Frase'),
('Inglês', 'Comparative Reading & Intertextuality', 'Comparatives and Superlatives'),
('Inglês', 'Comparativos e Advérbios', 'Comparatives and Superlatives'),
('Inglês', 'Compreensão Geral: Ideia Central e Título', 'Reading Comprehension'),
('Inglês', 'Compreensão Textual e Recursos Argumentativos', 'Reading Comprehension'),
('Inglês', 'Compreensão Textual e Vocabulário', 'Vocabulary'),
('Inglês', 'Compreensão de Texto (Interpretação)', 'Reading Comprehension'),
('Inglês', 'Compreensão de Texto (Vocabulário Militar)', 'Vocabulary'),
('Inglês', 'Compreensão de Texto e Coesão', 'Reading Comprehension'),
('Inglês', 'Compreensão de texto', 'Reading Comprehension'),
('Inglês', 'Compreensão de texto em língua inglesa', 'Reading Comprehension'),
('Inglês', 'Compreensão e Análise Textual', 'Reading Comprehension'),
('Inglês', 'Compreensão e Interpretação de Texto', 'Reading Comprehension'),
('Inglês', 'Compreensão e interpretação de texto', 'Reading Comprehension'),
('Inglês', 'Compreensão poética / Comunicação digital e distanciamento', 'Reading Comprehension'),
('Inglês', 'Conectivos e Conjunções', 'Conjunctions and Connectors'),
('Inglês', 'Conectivos e Verbos Modais', 'Modal Verbs'),
('Inglês', 'Conflito de anseios e sanidade mental', 'Conflito de Anseios'),
('Inglês', 'Conjunções e Conectivos', 'Conjunctions and Connectors'),
('Inglês', 'Culto à celebridade e marketing', 'Culto À Celebridade'),
('Inglês', 'Denotação e Conotação Lexical', 'Denotação'),
('Inglês', 'Direitos civis e representatividade', 'Direitos Civis'),
('Inglês', 'Discourse Markers / Conjunctions', 'Conjunctions and Connectors'),
('Inglês', 'Diversidade cultural e formação social', 'Diversidade Cultural'),
('Inglês', 'Expressões Idiomáticas (Idioms)', 'Vocabulary'),
('Inglês', 'Expressões Idiomáticas e Phrasal Verbs', 'Phrasal Verbs'),
('Inglês', 'Funções da Linguagem e Intenção Discursiva', 'Funções da Linguagem'),
('Inglês', 'Grammar & Discourse - Transition Words', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar & Sentence Structure', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar - Conditionals', 'Conditionals'),
('Inglês', 'Grammar - Imperative Form', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar - Interrogative Form', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar - Negative Structures', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar - Question Tags', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Articles', 'Articles and Determiners'),
('Inglês', 'Grammar / Comparative of Adjectives', 'Comparatives and Superlatives'),
('Inglês', 'Grammar / Conditionals', 'Conditionals'),
('Inglês', 'Grammar / Conjunctions & Discourse Markers', 'Conjunctions and Connectors'),
('Inglês', 'Grammar / Degrees of Comparison', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Irregular Plurals', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Modal Verbs', 'Modal Verbs'),
('Inglês', 'Grammar / Passive Voice', 'Passive Voice'),
('Inglês', 'Grammar / Plural of Nouns', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Prepositions', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Pronoun Reference', 'Pronouns'),
('Inglês', 'Grammar / Question Tags', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Relative Pronouns', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Verb Tenses', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Verb Tenses and Forms', 'Gramática e Estrutura da Frase'),
('Inglês', 'Grammar / Word Formation & Syntax', 'Word Formation'),
('Inglês', 'Gramática (Advérbios de Frequência)', 'Adjectives and Adverbs'),
('Inglês', 'Gramática (Artigos Definidos e Indefinidos)', 'Articles and Determiners'),
('Inglês', 'Gramática (Artigos Indefinidos)', 'Articles and Determiners'),
('Inglês', 'Gramática (Caso Possessivo / Relação de Posse)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Classes de Palavras / Adjetivos)', 'Adjectives and Adverbs'),
('Inglês', 'Gramática (Condicionais / Hipóteses)', 'Conditionals'),
('Inglês', 'Gramática (Conjugação Verbal - Simple Past)', 'Verb Tenses'),
('Inglês', 'Gramática (Formação de Perguntas no Past)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Gerúndio e Infinitivo)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Graus de Comparação / Superlativo)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Graus de Comparação dos Adjetivos)', 'Adjectives and Adverbs'),
('Inglês', 'Gramática (Graus dos Adjetivos)', 'Adjectives and Adverbs'),
('Inglês', 'Gramática (Modal Verbs)', 'Modal Verbs'),
('Inglês', 'Gramática (Ordem dos Advérbios)', 'Adjectives and Adverbs'),
('Inglês', 'Gramática (Plural dos Substantivos)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Preposições de Lugar e Direção)', 'Prepositions'),
('Inglês', 'Gramática (Preposições)', 'Prepositions'),
('Inglês', 'Gramática (Present Perfect)', 'Verb Tenses'),
('Inglês', 'Gramática (Pronomes Pessoais)', 'Pronouns'),
('Inglês', 'Gramática (Pronomes Relativos)', 'Pronouns'),
('Inglês', 'Gramática (Pronomes e Adjetivos Indefinidos)', 'Pronouns'),
('Inglês', 'Gramática (Question Words)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Referência Pronominal / Anáfora)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Substituição por Pronomes Pessoais)', 'Pronouns'),
('Inglês', 'Gramática (Tempos Verbais - Present Perfect)', 'Verb Tenses'),
('Inglês', 'Gramática (Tempos Verbais e Passiva)', 'Verb Tenses'),
('Inglês', 'Gramática (Tempos e Modos Verbais)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática (Verbos Modais / Identificação de Estrutura)', 'Modal Verbs'),
('Inglês', 'Gramática (Verbos Modais)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Classes de Palavras (-ing)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Conjunções Condicionais e Substituição', 'Conditionals'),
('Inglês', 'Gramática - Conjunções e Coesão', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Conjunções e conectivos', 'Conjunctions and Connectors'),
('Inglês', 'Gramática - Discurso indireto (Reported speech)', 'Reported Speech'),
('Inglês', 'Gramática - Estruturas Interrogativas', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Grau dos Adjetivos', 'Adjectives and Adverbs'),
('Inglês', 'Gramática - Graus de Comparação', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Inversão Concessiva e Estrutura Frasal', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Orações Subordinadas e Uso de Whether vs If', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Orações condicionais', 'Conditionals'),
('Inglês', 'Gramática - Plural e Concordância', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Possessivos', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Preposições', 'Prepositions'),
('Inglês', 'Gramática - Preposições em Contexto', 'Prepositions'),
('Inglês', 'Gramática - Pronomes reflexivos', 'Pronouns'),
('Inglês', 'Gramática - Pronominal e Referência', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Subjuntivo e orações com wish', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Tag Questions', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Tempos Verbais (Simple Past)', 'Verb Tenses'),
('Inglês', 'Gramática - Tempos Verbais e Voz Passiva', 'Verb Tenses'),
('Inglês', 'Gramática - Tempos e Modos Verbais', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática - Tempos verbais', 'Verb Tenses'),
('Inglês', 'Gramática - Verbos Modais e Expressões de Conselho', 'Modal Verbs'),
('Inglês', 'Gramática - Verbos modais', 'Modal Verbs'),
('Inglês', 'Gramática - Voz passiva', 'Passive Voice'),
('Inglês', 'Gramática Textual e Análise Crítica', 'Reading Comprehension'),
('Inglês', 'Gramática e Referência Anafórica', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Advérbios e Frequência', 'Adjectives and Adverbs'),
('Inglês', 'Gramática — Artigos Definidos e Indefinidos', 'Articles and Determiners'),
('Inglês', 'Gramática — Caso Genitivo', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Caso Genitivo (Possessive Case)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Classes de Palavras', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Concordância Verbal', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Condicionais', 'Conditionals'),
('Inglês', 'Gramática — Conectivos e Orações Adverbiais', 'Conjunctions and Connectors'),
('Inglês', 'Gramática — Estruturas Condicionais', 'Conditionals'),
('Inglês', 'Gramática — Graus de Comparação (Superlativo)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Graus dos Adjetivos', 'Adjectives and Adverbs'),
('Inglês', 'Gramática — Marcadores Discursivos / Conjunções', 'Conjunctions and Connectors'),
('Inglês', 'Gramática — Modais e Imperativo', 'Modal Verbs'),
('Inglês', 'Gramática — Preposições', 'Prepositions'),
('Inglês', 'Gramática — Pronomes', 'Pronouns'),
('Inglês', 'Gramática — Pronomes Pessoais e Possessivos', 'Pronouns'),
('Inglês', 'Gramática — Pronomes Relativos', 'Pronouns'),
('Inglês', 'Gramática — Quantificadores', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Quantificadores e Determinantes', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Question Tags', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Question Words', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Substantivos', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Substantivos Incontáveis', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Superlativo', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Tempos Verbais', 'Verb Tenses'),
('Inglês', 'Gramática — Tempos e Formas Verbais', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Verbos Modais', 'Modal Verbs'),
('Inglês', 'Gramática — Verbos e Concordância', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática — Voz Passiva', 'Passive Voice'),
('Inglês', 'Gramática: Concordância Verbal', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática: Conectivos e Expressões de Finalidade', 'Conjunctions and Connectors'),
('Inglês', 'Gramática: Graus do Adjetivo', 'Adjectives and Adverbs'),
('Inglês', 'Gramática: Graus dos Adjetivos (Comparativo)', 'Comparatives and Superlatives'),
('Inglês', 'Gramática: Orações Condicionais (If Clause)', 'Conditionals'),
('Inglês', 'Gramática: Pronomes Indefinidos e There to be', 'Pronouns'),
('Inglês', 'Gramática: Pronomes Relativos', 'Pronouns'),
('Inglês', 'Gramática: Pronomes e Referência Anafórica', 'Pronouns'),
('Inglês', 'Gramática: Referência Pronominal', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática: Respostas Curtas (Short Answers)', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática: Tempos Verbais e Emprego dos Tempos', 'Verb Tenses'),
('Inglês', 'Gramática: Verbos Irregulares', 'Gramática e Estrutura da Frase'),
('Inglês', 'Gramática: Verbos Modais', 'Modal Verbs'),
('Inglês', 'Inferência Textual', 'Reading Comprehension'),
('Inglês', 'Interpretação Poética e Relação Homem-Natureza', 'Reading Comprehension'),
('Inglês', 'Interpretação Textual e Canção', 'Reading Comprehension'),
('Inglês', 'Interpretação de Cartuns', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Compreensão Específica)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Compreensão Geral)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Compreensão Informativa)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Compreensão de Detalhes)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Compreensão de Tirinha)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Ideia Central)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Inferência)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Verdadeiro ou Falso)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto (Vocabulário / Adjetivos)', 'Adjectives and Adverbs'),
('Inglês', 'Interpretação de Texto - Compreensão e Inferência', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto / Análise Semiótica', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto / Compreensão Leitora', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto / Gêneros Textuais (Carta Editorial)', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto / Linguagem Digital e Meio Ambiente', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto / Marcadores Discursivos', 'Conjunctions and Connectors'),
('Inglês', 'Interpretação de Texto / Preconceito Linguístico e Identidade', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto e Apropriação Cultural', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto e Associação', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto e Compreensão Leitora', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto e Filosofia Social', 'Reading Comprehension'),
('Inglês', 'Interpretação de Texto e Tirinhas', 'Reading Comprehension'),
('Inglês', 'Interpretação de Textos e Pôsteres', 'Reading Comprehension'),
('Inglês', 'Interpretação de texto / Identidade e imigração', 'Reading Comprehension'),
('Inglês', 'Interpretação de texto / Redes sociais e saúde mental', 'Reading Comprehension'),
('Inglês', 'Interpretação de texto / Relações interpessoais e tecnologia', 'Reading Comprehension'),
('Inglês', 'Interpretação de texto poético e musical', 'Reading Comprehension'),
('Inglês', 'Interpretação do Vocabulário e Crítica Social', 'Vocabulary'),
('Inglês', 'Interpretação e Compreensão de Texto', 'Reading Comprehension'),
('Inglês', 'Leitura de Cartum e Linguagem Não Verbal', 'Leitura de Cartum'),
('Inglês', 'Leitura de infográficos e avisos', 'Leitura de Infográficos'),
('Inglês', 'Leitura de tirinha / Humor e quebra de expectativa', 'Leitura de Tirinha'),
('Inglês', 'Leitura e Interpretação de Cartum', 'Reading Comprehension'),
('Inglês', 'Leitura e Interpretação de Texto (Campanha Publicitária / Meio Ambiente)', 'Reading Comprehension'),
('Inglês', 'Leitura e Vocabulário em Romances', 'Vocabulary'),
('Inglês', 'Lexicologia e Semântica', 'Vocabulary'),
('Inglês', 'Linguagem Figurada e Metáforas', 'Linguagem Figurada'),
('Inglês', 'Linguagem publicitária e leitura visual', 'Linguagem Publicitária'),
('Inglês', 'Literatura e Estado Totalitário', 'Literatura'),
('Inglês', 'Morfologia (Formação de Palavras / Prefixos e Sufixos)', 'Word Formation'),
('Inglês', 'Parts of Speech / Word Classes', 'Gramática e Estrutura da Frase'),
('Inglês', 'Phrasal Verbs e Vocabulário', 'Phrasal Verbs'),
('Inglês', 'Plural dos Substantivos', 'Gramática e Estrutura da Frase'),
('Inglês', 'Plural dos Substantivos / Estrutura', 'Gramática e Estrutura da Frase'),
('Inglês', 'Poesia Contemporânea e Relações Sociais (Refugiados)', 'Poesia Contemporânea'),
('Inglês', 'Preposições e Expressões', 'Prepositions'),
('Inglês', 'Pronomes Indefinidos', 'Pronouns'),
('Inglês', 'Reading Comprehension & Text Goal', 'Reading Comprehension'),
('Inglês', 'Reading Comprehension / Comic Strip', 'Reading Comprehension'),
('Inglês', 'Reading Comprehension / Text Interpretation', 'Reading Comprehension'),
('Inglês', 'Recursos Estilísticos e Ironia', 'Recursos Estilísticos'),
('Inglês', 'Referência Pronominal', 'Gramática e Estrutura da Frase'),
('Inglês', 'Referência Pronominal / Anáfora', 'Gramática e Estrutura da Frase'),
('Inglês', 'Respostas Curtas / Estrutura Condicional', 'Conditionals'),
('Inglês', 'Semântica e Análise Contextual', 'Reading Comprehension'),
('Inglês', 'Sequenciamento e Cronologia', 'Sequenciamento'),
('Inglês', 'Subjetividade e percepção de lugares', 'Subjetividade'),
('Inglês', 'Substituição Pronomial / Referência', 'Substituição Pronomial'),
('Inglês', 'Tempos Verbais', 'Verb Tenses'),
('Inglês', 'Tempos Verbais (Past Perfect, Simple Past)', 'Verb Tenses'),
('Inglês', 'Tempos e Formas Verbais', 'Tempos'),
('Inglês', 'Text Comprehension', 'Reading Comprehension'),
('Inglês', 'Tipologia Textual (Gênero Textual / Review)', 'Reading Comprehension'),
('Inglês', 'Valores Culturais e Práticas Educativas', 'Valores Culturais'),
('Inglês', 'Variação Linguística e Hibridismo Cultural (Spanglish)', 'Variação Linguística'),
('Inglês', 'Verbos Modais', 'Modal Verbs'),
('Inglês', 'Verbos Modais e Expressões Equivalentes', 'Modal Verbs'),
('Inglês', 'Verbos Modais e Tempos Verbais', 'Verb Tenses'),
('Inglês', 'Vocabulary & Reference', 'Vocabulary'),
('Inglês', 'Vocabulary - Adverbs and Intensifiers', 'Adjectives and Adverbs'),
('Inglês', 'Vocabulary - Gender', 'Vocabulary'),
('Inglês', 'Vocabulary / Contextual Meaning', 'Vocabulary'),
('Inglês', 'Vocabulary / Prefixes and Word Formation', 'Word Formation'),
('Inglês', 'Vocabulary / Quantifiers and Determiners', 'Articles and Determiners'),
('Inglês', 'Vocabulary / Synonyms', 'Vocabulary'),
('Inglês', 'Vocabulary / Synonyms & Antonyms', 'Vocabulary'),
('Inglês', 'Vocabulário (Gênero dos Substantivos)', 'Vocabulary'),
('Inglês', 'Vocabulário (Significado Literal vs Figurado)', 'Vocabulary'),
('Inglês', 'Vocabulário - Sinonímia e Definições Lexicais', 'Vocabulary'),
('Inglês', 'Vocabulário / Semântica', 'Vocabulary'),
('Inglês', 'Vocabulário e Adjetivos', 'Adjectives and Adverbs'),
('Inglês', 'Vocabulário e Coesão Textual (Referência Pronomial)', 'Vocabulary'),
('Inglês', 'Vocabulário e Definição de Palavras', 'Vocabulary'),
('Inglês', 'Vocabulário e Expressões Idiomáticas', 'Vocabulary'),
('Inglês', 'Vocabulário e Phrasal Verbs', 'Phrasal Verbs'),
('Inglês', 'Vocabulário e Regência de Adjetivos', 'Adjectives and Adverbs'),
('Inglês', 'Vocabulário e Semântica Lexical', 'Vocabulary'),
('Inglês', 'Vocabulário e Significado Contextual', 'Vocabulary'),
('Inglês', 'Vocabulário e Sinonímia em Contexto', 'Vocabulary'),
('Inglês', 'Vocabulário e Sinônimos', 'Vocabulary'),
('Inglês', 'Vocabulário e estratégias de marketing', 'Vocabulary'),
('Inglês', 'Vocabulário e expressões idiomáticas', 'Vocabulary'),
('Literatura', 'Arcadismo e relação eu-lírico/natureza', 'Barroco e Arcadismo'),
('Literatura', 'Declínio Físico e Afeto em Natalia Polesso', 'Declínio Físico'),
('Literatura', 'Descrição narrativa / Mestiçagem e regionalismo', 'Gêneros e Análise Literária'),
('Literatura', 'Estilo machadiano / Inventário e rituais funèbres', 'Estilo Machadiano'),
('Literatura', 'Foco narrativo e perspectiva', 'Foco Narrativo'),
('Literatura', 'Função Social da Arte / Desestabilização', 'Função Social da Arte'),
('Literatura', 'Funções da linguagem / Emotiva na letra de música', 'Funções da Linguagem'),
('Literatura', 'Gênero crônica / Refração e escrita jornalística', 'Gênero Crônica'),
('Literatura', 'Identidade, Vulnerabilidade e Inclusão Social (Marcelino Freire)', 'Identidade'),
('Literatura', 'Intertextualidade e Releitura de Mitos', 'Gêneros e Análise Literária'),
('Literatura', 'Literatura Afro-Brasileira', 'Literatura Afro-brasileira'),
('Literatura', 'Literatura contemporânea e prosa narrativa', 'Literatura Contemporânea'),
('Literatura', 'Literatura contemporânea e relações de poder', 'Literatura Contemporânea'),
('Literatura', 'Literatura testemunhal / Carolina Maria de Jesus', 'Literatura Testemunhal'),
('Literatura', 'Metalinguagem e Crítica Social no Rap', 'Gêneros e Análise Literária'),
('Literatura', 'Metalinguagem e poética / Conceito de palavra', 'Gêneros e Análise Literária'),
('Literatura', 'Metalinguagem e processo de criação literária', 'Gêneros e Análise Literária'),
('Literatura', 'Modernismo (3ª geração) e psicologia dos personagens', 'Modernismo'),
('Literatura', 'Modernismo (geração de 45) e rigor formal', 'Modernismo'),
('Literatura', 'Modernismo / Graciliano Ramos e a Norma Culta vs Fala', 'Modernismo'),
('Literatura', 'Modernismo brasileiro', 'Modernismo'),
('Literatura', 'Modernismo e Contexto Social', 'Modernismo'),
('Literatura', 'Narrativa Contemporânea e Conflito', 'Literatura Contemporânea'),
('Literatura', 'Narrativa de memória / Violência e alusão literária', 'Gêneros e Análise Literária'),
('Literatura', 'Naturalismo / Determinismo biológico e instinto', 'Realismo e Naturalismo'),
('Literatura', 'Naturalismo / Pré-Modernismo (Carmen Dolores - A Luta)', 'Modernismo'),
('Literatura', 'Poesia / Identidade e Deslocamento', 'Gêneros e Análise Literária'),
('Literatura', 'Poesia / Vinicius de Moraes (*Feijoada à minha moda*)', 'Gêneros e Análise Literária'),
('Literatura', 'Poesia Contemporânea e Eu Lírico', 'Literatura Contemporânea'),
('Literatura', 'Poesia Contemporânea e Expressão Lírica', 'Literatura Contemporânea'),
('Literatura', 'Poesia Margem/Moderna e Construção Textual', 'Gêneros e Análise Literária'),
('Literatura', 'Poesia Parnasiana/Simbolista (Vicente de Carvalho)', 'Gêneros e Análise Literária'),
('Literatura', 'Poesia contemporânea e conflito de gerações', 'Literatura Contemporânea'),
('Literatura', 'Poesia contemporânea e memória', 'Literatura Contemporânea'),
('Literatura', 'Poesia contemporânea e metapoesia', 'Literatura Contemporânea'),
('Literatura', 'Poesia e Linguagem', 'Gêneros e Análise Literária'),
('Literatura', 'Poesia marginal/contemporânea e ironia', 'Literatura Contemporânea'),
('Literatura', 'Progressão Temática Narrativa', 'Gêneros e Análise Literária'),
('Literatura', 'Prosa Poética e Elementos Narrativos', 'Gêneros e Análise Literária'),
('Literatura', 'Prosa moderna / Carnaval e ambivalência moral', 'Gêneros e Análise Literária'),
('Literatura', 'Realismo / Crítica Social em Júlia Lopes de Almeida', 'Realismo e Naturalismo'),
('Literatura', 'Realismo / Ironia machadiana', 'Realismo e Naturalismo'),
('Literatura', 'Realismo / Machado de Assis (*Esaú e Jacó*)', 'Realismo e Naturalismo'),
('Literatura', 'Realismo e foco narrativo', 'Realismo e Naturalismo'),
('Literatura', 'Reescrita e Intertextualidade / Machado de Assis', 'Realismo e Naturalismo'),
('Literatura', 'Regionalismo / Afetividade e lirismo sertanejo', 'Regionalismo'),
('Literatura', 'Relações Familiares e Adoção em Julián Fuks', 'Relações Familiares'),
('Literatura', 'Romance Histórico-Social e Estrutura Agrária (Eliana Alves Cruz)', 'Romance Histórico-social'),
('Literatura', 'Romance de 30 / Drama dos retirantes', 'Romance de 30'),
('Literatura', 'Romantismo / Abolicionismo em Maria Firmina dos Reis', 'Romantismo'),
('Literatura', 'Romantismo / José de Alencar (*Senhora*)', 'Romantismo'),
('Literatura', 'Romantismo no Brasil (Inocência - Taunay)', 'Romantismo'),
('Literatura', 'Simbolismo (Soneto - Gilka Machado)', 'Parnasianismo e Simbolismo'),
('Literatura', 'Teatro brasileiro e engajamento social', 'Teatro Brasileiro'),
('Matemática', 'Análise Combinatória (Anagramas com Restrição)', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória (Identidade de Vandermonde)', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória (Permutação Circular)', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória (Princípio Fundamental)', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória - Arranjos', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória - Coloração', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória - Combinação', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Anagramas', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Arranjos e Permutações', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Caminhos em Grade', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Combinação Simples', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Combinação simples', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Combinações', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Contagem', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Contagem / Lógica', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Formação de Comissões', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Permutação com repetição', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Princípio Fundamental da Contagem', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória / Princípio Multiplicativo e Combinações', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória e Análise de Sinais', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória e Divisibilidade', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória e Lógica', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória e Probabilidade', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória e Probabilidade / Probabilidade', 'Análise Combinatória'),
('Matemática', 'Análise Combinatória — Contagem', 'Análise Combinatória'),
('Matemática', 'Análise Dimensional / Unidades de Medida', 'Grandezas e Medidas'),
('Matemática', 'Análise Dimensional e Proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Análise Gráfica / Leitura de Gráficos e Custos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Análise Gráfica de Funções', 'Funções'),
('Matemática', 'Análise Gráfica de Volume Acumulado', 'Geometria Espacial'),
('Matemática', 'Análise Gráfica e Estatística (IPCA)', 'Estatística'),
('Matemática', 'Análise Gráfica e Funções', 'Funções'),
('Matemática', 'Análise combinatória', 'Análise Combinatória'),
('Matemática', 'Análise de Dados e Tomada de Decisão', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Análise de Gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Análise de Gráficos de Barras', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Análise de Gráficos de Funções', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Análise de Gráficos e Estatística', 'Estatística'),
('Matemática', 'Análise de Proposições e Somatórios', 'Raciocínio Lógico'),
('Matemática', 'Aritmética (Máximo Divisor Comum - MDC)', 'Teoria dos Números'),
('Matemática', 'Aritmética (Porcentagem e Reajustes)', 'Porcentagem'),
('Matemática', 'Aritmética (Problemas de Trabalho em Conjunto)', 'Conjuntos Numéricos'),
('Matemática', 'Aritmética (Sequências e Médias)', 'Sequências e Recorrências'),
('Matemática', 'Aritmética (progressão aritmética e múltiplos)', 'Progressões'),
('Matemática', 'Aritmética - Decimais', 'Aritmética'),
('Matemática', 'Aritmética / Comparação de Opções de Custos', 'Aritmética'),
('Matemática', 'Aritmética / Multiplicação e Comparação de Dados', 'Aritmética'),
('Matemática', 'Aritmética / Operações Básicas', 'Aritmética'),
('Matemática', 'Aritmética / Razão e Proporção', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Aritmética / Razão e Velocidade Média', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Aritmética / Ritmo (Pace) e Média', 'Aritmética'),
('Matemática', 'Aritmética / Subtração com Números Decimais', 'Aritmética'),
('Matemática', 'Aritmética Modular e Restos', 'Aritmética'),
('Matemática', 'Aritmética Residual e Calendários', 'Teoria dos Números'),
('Matemática', 'Aritmética e Cinemática (Movimento Uniforme)', 'Aritmética'),
('Matemática', 'Aritmética e Conjuntos Numéricos', 'Conjuntos Numéricos'),
('Matemática', 'Aritmética e Divisibilidade', 'Teoria dos Números'),
('Matemática', 'Aritmética e Interpretação de Dados', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Aritmética e Notação Científica', 'Potenciação e Radiciação'),
('Matemática', 'Aritmética e Otimização', 'Funções'),
('Matemática', 'Aritmética e Teoria dos Números', 'Teoria dos Números'),
('Matemática', 'Aritmética e expressões de proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Aritmética e Álgebra (Divisibilidade)', 'Teoria dos Números'),
('Matemática', 'Aritmética — Conjuntos Numéricos e Dízimas', 'Conjuntos Numéricos'),
('Matemática', 'Aritmética — Divisores de um Número Natural', 'Aritmética'),
('Matemática', 'Aritmética — Propriedades do MMC e MDC', 'Teoria dos Números'),
('Matemática', 'Aritmética: Máximo Divisor Comum (MDC)', 'Teoria dos Números'),
('Matemática', 'Binômio de Newton', 'Análise Combinatória'),
('Matemática', 'Cinemática e Equações', 'Equações e Inequações'),
('Matemática', 'Cinemática e Proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Conceito de Função', 'Funções'),
('Matemática', 'Conjuntos / Princípio da Inclusão-Exclusão', 'Conjuntos Numéricos'),
('Matemática', 'Conjuntos Numéricos e Módulo', 'Conjuntos Numéricos'),
('Matemática', 'Conjuntos Numéricos e Operações', 'Conjuntos Numéricos'),
('Matemática', 'Conjuntos Numéricos e Racionalização', 'Conjuntos Numéricos'),
('Matemática', 'Conjuntos Numéricos e Reta Real', 'Conjuntos Numéricos'),
('Matemática', 'Conversão de unidades de medida', 'Grandezas e Medidas'),
('Matemática', 'Cálculo Diferencial (Otimização)', 'Funções'),
('Matemática', 'Cálculo Diferencial (Taxas Relacionadas)', 'Cálculo Diferencial e Integral'),
('Matemática', 'Cálculo Integral (Volume de Sólido de Revolução)', 'Geometria Espacial'),
('Matemática', 'Decomposição em Frações Parciais e Identidades', 'Conjuntos Numéricos'),
('Matemática', 'Divisão Proporcional', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Dominio de Funções e Inequações', 'Funções'),
('Matemática', 'Domínio de Funções e Inequações Quociente', 'Funções'),
('Matemática', 'Dízimas Periódicas e Números Racionais', 'Conjuntos Numéricos'),
('Matemática', 'Dízimas Periódicas e Operações Numéricas', 'Conjuntos Numéricos'),
('Matemática', 'Equação Logarítmica', 'Equações e Inequações'),
('Matemática', 'Equação do 2º Grau e Potenciação/Radiciação', 'Equações e Inequações'),
('Matemática', 'Equação do 2º Grau e Relações de Girard', 'Equações e Inequações'),
('Matemática', 'Equação do 2º Grau e Resolução de Problemas', 'Equações e Inequações'),
('Matemática', 'Equações Diofantinas e Sistemas de 1º Grau', 'Equações e Inequações'),
('Matemática', 'Equações Irracionais', 'Equações e Inequações'),
('Matemática', 'Equações do 1º Grau e Aritmética', 'Equações e Inequações'),
('Matemática', 'Equações do 1º Grau e Sistemas', 'Equações e Inequações'),
('Matemática', 'Equações do 2º Grau e Álgebra', 'Equações e Inequações'),
('Matemática', 'Equações e Inequações (Modelagem)', 'Equações e Inequações'),
('Matemática', 'Equações e Inequações do 1º Grau', 'Equações e Inequações'),
('Matemática', 'Equações e Proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Equações e Sistemas do 1º Grau', 'Equações e Inequações'),
('Matemática', 'Equações e Vazão', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Equações, Inequações e Álgebra', 'Equações e Inequações'),
('Matemática', 'Escala', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Escala Numérica', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Escala e Inequações', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Escala e porcentagem', 'Porcentagem'),
('Matemática', 'Estatística (Gráficos e Média)', 'Estatística'),
('Matemática', 'Estatística (Medidas de Dispersão)', 'Estatística'),
('Matemática', 'Estatística (Medidas de Tendência Central)', 'Estatística'),
('Matemática', 'Estatística (Moda e Mediana)', 'Estatística'),
('Matemática', 'Estatística (Média Ponderada)', 'Estatística'),
('Matemática', 'Estatística (Média e Histograma)', 'Estatística'),
('Matemática', 'Estatística (Média, Mediana e Moda)', 'Estatística'),
('Matemática', 'Estatística (Média, Moda e Mediana)', 'Estatística'),
('Matemática', 'Estatística (medidas de dispersão - desvio padrão)', 'Estatística'),
('Matemática', 'Estatística (média aritmética)', 'Estatística'),
('Matemática', 'Estatística (média e interpretação de tabelas)', 'Estatística'),
('Matemática', 'Estatística - Leitura Gráfica', 'Estatística'),
('Matemática', 'Estatística - Margem de Erro', 'Estatística'),
('Matemática', 'Estatística - Mediana', 'Estatística'),
('Matemática', 'Estatística - Média Aritmética', 'Estatística'),
('Matemática', 'Estatística - Média Ponderada', 'Estatística'),
('Matemática', 'Estatística / Análise Conjunta de Gráficos', 'Estatística'),
('Matemática', 'Estatística / Análise Gráfica e Probabilidade', 'Probabilidade'),
('Matemática', 'Estatística / Análise de variância e amplitude', 'Estatística'),
('Matemática', 'Estatística / Desvio padrão e variabilidade', 'Estatística'),
('Matemática', 'Estatística / Distribuição de Frequências', 'Estatística'),
('Matemática', 'Estatística / Interpretação de Gráficos de Demanda e Estoque', 'Estatística'),
('Matemática', 'Estatística / Interpretação de Gráficos e Porcentagem', 'Estatística'),
('Matemática', 'Estatística / Leitura crítica de infográficos', 'Estatística'),
('Matemática', 'Estatística / Leitura de Gráficos', 'Estatística'),
('Matemática', 'Estatística / Mediana', 'Estatística'),
('Matemática', 'Estatística / Medidas de Tendência Central', 'Estatística'),
('Matemática', 'Estatística / Medidas de Tendência Central (Mediana)', 'Estatística'),
('Matemática', 'Estatística / Média Aritmética', 'Estatística'),
('Matemática', 'Estatística / Média Ponderada', 'Estatística'),
('Matemática', 'Estatística / Média ponderada', 'Estatística'),
('Matemática', 'Estatística / Média, Mediana e Moda', 'Estatística'),
('Matemática', 'Estatística / Porcentagem', 'Estatística'),
('Matemática', 'Estatística / Porcentagem e Arrecadação', 'Estatística'),
('Matemática', 'Estatística / Probabilidade e Valor Esperado', 'Probabilidade'),
('Matemática', 'Estatística / Produção Agrícola e Gráficos de Linha', 'Estatística'),
('Matemática', 'Estatística / Progressão Aritmética', 'Estatística'),
('Matemática', 'Estatística / Regressão e Reta de Tendência', 'Estatística'),
('Matemática', 'Estatística / Velocidade Média', 'Estatística'),
('Matemática', 'Estatística e Análise de Gráficos', 'Estatística'),
('Matemática', 'Estatística e Dispersão', 'Estatística'),
('Matemática', 'Estatística e Interpolação Linear', 'Estatística'),
('Matemática', 'Estatística e Médias', 'Estatística'),
('Matemática', 'Estatística e Método de Borda', 'Estatística'),
('Matemática', 'Estatística e Porcentagem', 'Estatística'),
('Matemática', 'Estatística e Probabilidade', 'Probabilidade'),
('Matemática', 'Estatística e cálculo de reposição', 'Estatística'),
('Matemática', 'Estudo das Funções e Gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Estudo das Funções — Função Quadrática', 'Função Quadrática'),
('Matemática', 'Estudo das Raízes da Equação do 2º Grau', 'Equações e Inequações'),
('Matemática', 'Estudo do Domínio de Funções', 'Funções'),
('Matemática', 'Fatoração Prime e MMC', 'Teoria dos Números'),
('Matemática', 'Fatoração de Polinômios e Produtos Notáveis', 'Polinômios'),
('Matemática', 'Fatoração e Expressões Algébricas', 'Álgebra'),
('Matemática', 'Fatoração e Frações Algébricas', 'Conjuntos Numéricos'),
('Matemática', 'Fatoração e Produtos Notáveis', 'Álgebra'),
('Matemática', 'Frações Continuadas', 'Conjuntos Numéricos'),
('Matemática', 'Fundamentos / Conjuntos / Números Reais', 'Conjuntos Numéricos'),
('Matemática', 'Função Afim / Custo de Produção', 'Função Afim'),
('Matemática', 'Função Afim / Sistemas de Equações do 1º Grau', 'Função Afim'),
('Matemática', 'Função Afim e Modelo Linear', 'Função Afim'),
('Matemática', 'Função Afim e Variação Percentual', 'Porcentagem'),
('Matemática', 'Função Exponencial', 'Logaritmos e Exponenciais'),
('Matemática', 'Função Exponencial / Crescimento populacional e meia-vida', 'Logaritmos e Exponenciais'),
('Matemática', 'Função Exponencial / Progressão Geométrica', 'Progressões'),
('Matemática', 'Função Exponencial e Logaritmo', 'Logaritmos e Exponenciais'),
('Matemática', 'Função Exponencial e Progressão Geométrica', 'Progressões'),
('Matemática', 'Função Maior Inteiro (Piso) e Números Reais', 'Funções'),
('Matemática', 'Função Quadrática - Parábola', 'Função Quadrática'),
('Matemática', 'Função Quadrática / Modelagem de lucro', 'Função Quadrática'),
('Matemática', 'Função Quadrática / Vértice da parábola e valor máximo', 'Função Quadrática'),
('Matemática', 'Função Quadrática e Aplicações', 'Função Quadrática'),
('Matemática', 'Função Quadrática e Geometria', 'Geometria Plana'),
('Matemática', 'Função Quadrática e Otimização', 'Função Quadrática'),
('Matemática', 'Função Quadrática e Parábola', 'Função Quadrática'),
('Matemática', 'Função Trigonômétrica / Seno e Cosseno em fenômenos periódicos', 'Trigonometria'),
('Matemática', 'Função afim (taxa de variação)', 'Função Afim'),
('Matemática', 'Função do 1º Grau / Gráficos e interseção', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Função do 1º Grau / Interpretação de tarifas', 'Função Afim'),
('Matemática', 'Função do 1º Grau e Análise de Gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Função exponencial e logaritmos', 'Logaritmos e Exponenciais'),
('Matemática', 'Funções (1º e 2º Graus no Plano Cartesiano)', 'Funções'),
('Matemática', 'Funções (Função Afim)', 'Função Afim'),
('Matemática', 'Funções / Análise Gráfica de Variáveis', 'Funções'),
('Matemática', 'Funções / Definição e Conceito de Função', 'Funções'),
('Matemática', 'Funções / Exponencial', 'Logaritmos e Exponenciais'),
('Matemática', 'Funções / Função Quadrática', 'Função Quadrática'),
('Matemática', 'Funções / Gráficos de Lucro', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Funções / Gráficos de Vazão', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Funções / Logaritmos e Função Quadrática', 'Logaritmos e Exponenciais'),
('Matemática', 'Funções / Modelagem Algébrica', 'Funções'),
('Matemática', 'Funções Exponenciais e Logaritmos', 'Logaritmos e Exponenciais'),
('Matemática', 'Funções Exponenciais e Logarítmicas', 'Logaritmos e Exponenciais'),
('Matemática', 'Funções Logarítmicas / Escala Richter', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Funções Quadráticas e Suas Raízes', 'Função Quadrática'),
('Matemática', 'Funções Trigonométricas', 'Trigonometria'),
('Matemática', 'Funções Trigonométricas / Análise Gráfica', 'Trigonometria'),
('Matemática', 'Funções de proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Funções do 1º Grau', 'Função Afim'),
('Matemática', 'Funções e Equações / Problemas de 1º Grau', 'Funções'),
('Matemática', 'Funções e Função Quadrática', 'Função Quadrática'),
('Matemática', 'Funções e Gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Geometria Analítica (Circunferência de Apolônio)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Circunferência)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Cônicas)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Distância Ponto-Reta)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Hipérbole e Propriedade Refletora)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Inequações no Plano)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica (Retas e Paralelogramos)', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica - Hipérbole', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica / Equação da Circunferência', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica / Equação da Reta', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica / Equação da Reta Mediatriz', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica / Ponto e Reta', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica / Retas e Divisão de Segmentos', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica Tridimensional', 'Geometria Analítica'),
('Matemática', 'Geometria Analítica e Otimização', 'Geometria Analítica'),
('Matemática', 'Geometria Espacial (Cilindro e Cubo)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Cilindro e Racionamento)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Cilindros e Hélices)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Empacotamento)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Tronco de Cone e Cilindro)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Tronco de Cone e Razão de Volumes)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Visualização Tridimensional)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial (Áreas e Poliedros)', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial - Calota Esférica', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial - Escala Volumétrica', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial - Prismas', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial - Volumes', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Cilindros', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Cones', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Conversão de Unidades de Volume', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Esferas', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Esferas e captação de água', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Faces e Simetria de Poliedros', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Otimização', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Otimização de Custos', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Paralelepípedo', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Paralelepípedo e caixas', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Pirâmides', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Planificação de sólidos', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Poliedros', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Princípio de Cavalieri', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Prismas e Razão de Volumes', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Projeção Ortogonal', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Projeção ortogonal', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Projeções Ortogonais', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Projeções Ortogonais em Eixos 3D', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Relação de Euler e Poliedros', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Sólidos Compostos e Área', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Sólidos de Revolução', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Tronco de Cone', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Tronco de cone', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Volume de Cilindro e Cubo', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Volume de Cilindros e Prismas', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Volume de Paralelepípedo Retângulo', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Volume de cilindro e prisma', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial / Volume do Cilindro', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial de Posição', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial e Densidade', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial e Gráficos', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial e Inequações', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial e Plana / Inscrição de Cilindro em Prisma', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial e Polinômios', 'Geometria Espacial'),
('Matemática', 'Geometria Espacial: Área de Superfície', 'Geometria Espacial'),
('Matemática', 'Geometria Plana (Arco Capaz)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Circunferência Inscrita e Ângulos)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Coordenadas Polares)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Coroa Circular)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Círculos e Potência de Ponto)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Círculos e Tangentes)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Escala e Áreas)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Lei dos Cossenos)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Lugar Geométrico)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Perímetro e Setor Circular)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Polígonos Regulares e Áreas)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Posições Relativas entre Círculos)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Relações Métricas e Semelhança)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Semelhança e Razão de Áreas)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Setor Circular)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Triângulo Equilátero e Radiciação)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Triângulos e Pontos Notáveis)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Triângulos)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Área)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Áreas de Figuras Planas)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Áreas e Trigonometria)', 'Geometria Plana'),
('Matemática', 'Geometria Plana (Áreas e Triângulos)', 'Geometria Plana'),
('Matemática', 'Geometria Plana - Otimização', 'Geometria Plana'),
('Matemática', 'Geometria Plana - Transformações', 'Geometria Plana'),
('Matemática', 'Geometria Plana - Áreas', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Circuncentro e Triângulo Equilátero', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Circunferência e Polígonos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Comprimento de Circunferência', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Comprimento de Correia', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Congruência de Triângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Círculo e perímetro de roda', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Densidade Populacional', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Ladrilhamento', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Orientação e Deslocamento em Malha', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Polígonos Regulares', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Polígonos regulares e ângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Quadriláteros e Triângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Retas Paralelas e Ângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Semelhança de Triângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Semelhança de Triângulos e Pitágoras', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Semelhança de triângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Tangência e Circunferências', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Telhados', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Teorema de Pitágoras', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Triângulos e Razões Trigonométricas', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Triângulos e Relações Métricas', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Área de Setor Circular', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Área de Triângulos e Trigonometria', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Área de figuras compostas', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Área do Retângulo', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Área do Semicírculo', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas de Figuras Planas', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas de Polígonos Regulares', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas de Quadriláteros', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas de setores circulares', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas e Conversão de Unidades', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Áreas e Perímetros', 'Geometria Plana'),
('Matemática', 'Geometria Plana / Ângulos e Bissetrizes', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Cinemática Média', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Espacial (Área)', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Função Quadrática / Otimização', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Mínimos de Funções', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Otimização', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Planificação', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Progressão Geométrica', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Trigonometria', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Trigonometria no Triângulo', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Áreas', 'Geometria Plana'),
('Matemática', 'Geometria Plana e Ângulos na Circunferência', 'Geometria Plana'),
('Matemática', 'Geometria Plana — Circunferência e Relações Métricas', 'Geometria Plana'),
('Matemática', 'Geometria Plana — Áreas de Figuras Planas', 'Geometria Plana'),
('Matemática', 'Geometria Plana — Áreas e Círculo Inscrito', 'Geometria Plana'),
('Matemática', 'Geometria Plana — Áreas e Razões Trigo', 'Geometria Plana'),
('Matemática', 'Geometria Plana: Polígonos e Ângulos', 'Geometria Plana'),
('Matemática', 'Geometria Plana: Áreas e Relações Métricas', 'Geometria Plana'),
('Matemática', 'Geometria analítica', 'Geometria Analítica'),
('Matemática', 'Geometria analítica e função afim', 'Geometria Analítica'),
('Matemática', 'Geometria analítica e otimização de tempo', 'Geometria Analítica'),
('Matemática', 'Geometria de Posição e Orientação', 'Geometria Plana'),
('Matemática', 'Geometria e Porcentagem (Rampa)', 'Geometria Plana'),
('Matemática', 'Geometria e Trajetórias', 'Geometria Plana'),
('Matemática', 'Geometria espacial', 'Geometria Espacial'),
('Matemática', 'Geometria espacial (projeção ortogonal)', 'Geometria Espacial'),
('Matemática', 'Geometria espacial (volume de paralelepípedo)', 'Geometria Espacial'),
('Matemática', 'Geometria espacial (volume de sólidos compostos)', 'Geometria Espacial'),
('Matemática', 'Geometria plana', 'Geometria Plana'),
('Matemática', 'Geometria plana (área de figuras) e equações', 'Geometria Plana'),
('Matemática', 'Geometria plana e cálculo de área parabólica', 'Geometria Plana'),
('Matemática', 'Geometria plana e distância entre pontos (equidistância)', 'Geometria Analítica'),
('Matemática', 'Grafos e Redes / Rotas e matrizes', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Grandezas Proporcionais (Vazão)', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Grandezas Proporcionais, Unidades e Vazão', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Grandezas e Análise Dimensional', 'Grandezas e Medidas'),
('Matemática', 'Grandezas e Medidas / Consumo de Combustível', 'Grandezas e Medidas'),
('Matemática', 'Grandezas e Medidas / Densidade Superficial', 'Grandezas e Medidas'),
('Matemática', 'Grandezas e Medidas / Vazão', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Inequações / Geometria', 'Geometria Plana'),
('Matemática', 'Inequações Produto e Quociente', 'Equações e Inequações'),
('Matemática', 'Inequações Racionais e Polinomiais', 'Equações e Inequações'),
('Matemática', 'Inequações do 1º Grau', 'Equações e Inequações'),
('Matemática', 'Interpretação de Gráficos e Funções', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Interpretação de gráficos e taxa de variação (vazão)', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Interseção de Circunferências e Áreas', 'Geometria Plana'),
('Matemática', 'Interseção de Reta e Parábola', 'Função Quadrática'),
('Matemática', 'Leitura de Gráficos / Balança Comercial', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Leitura de Instrumentos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Leitura de gráficos e porcentagem', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Leitura e Análise de Gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Leitura e interpretação de gráficos', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Logaritmos', 'Logaritmos e Exponenciais'),
('Matemática', 'Logaritmos / Escala Richter e decibéis', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Logaritmos / Funções', 'Logaritmos e Exponenciais'),
('Matemática', 'Logaritmos e Matemática Financeira', 'Matemática Financeira'),
('Matemática', 'Lógica / Formação de Códigos Numéricos', 'Raciocínio Lógico'),
('Matemática', 'Lógica e Sequências Numéricas', 'Progressões'),
('Matemática', 'Matemática Financeira (Juros Compostos)', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira - Juros Compostos', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Comparação de Preços', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Cálculo de Lucro', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Descontos e equivalência', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Financiamento', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Inflação e poder de compra', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Juros simples e compostos', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Lucro e Despesas', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira / Otimização', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira e Logaritmos', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira e Porcentagem', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira e Problemas', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira e Progressão Geométrica', 'Matemática Financeira'),
('Matemática', 'Matemática Financeira e Razão/Proporção', 'Matemática Financeira'),
('Matemática', 'Matrizes e Determinantes', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Matrizes e Determinantes (Autovalores)', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Matrizes e Operações', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Matrizes e Sistemas Lineares', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Matrizes e determinantes', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Matrizes e Álgebra Linear', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Modelagem Matemática e Análise de Opções', 'Funções'),
('Matemática', 'Movimento Uniforme e Razão', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Notação Científica', 'Potenciação e Radiciação'),
('Matemática', 'Notação Científica e Ampliação', 'Potenciação e Radiciação'),
('Matemática', 'Números Complexos (Forma Trigonométrica)', 'Trigonometria'),
('Matemática', 'Números Complexos / Módulo e Argumento', 'Números Complexos'),
('Matemática', 'Números Complexos / Operações e Conjugado', 'Números Complexos'),
('Matemática', 'Números Racionais e Frações Equivalentes', 'Conjuntos Numéricos'),
('Matemática', 'Números complexos', 'Números Complexos'),
('Matemática', 'Operações com Conjuntos Finitos', 'Conjuntos Numéricos'),
('Matemática', 'Operações com Dízimas e Potências', 'Conjuntos Numéricos'),
('Matemática', 'Operações com Frações / Números Mistos', 'Conjuntos Numéricos'),
('Matemática', 'Orientação Espacial e Coordenadas', 'Orientação Espacial'),
('Matemática', 'Otimização Financeira', 'Funções'),
('Matemática', 'Otimização de Custos', 'Funções'),
('Matemática', 'Otimização e Custos', 'Funções'),
('Matemática', 'Polinômios (Soma dos Coeficientes)', 'Polinômios'),
('Matemática', 'Polinômios (Teorema do Resto)', 'Polinômios'),
('Matemática', 'Polinômios e Geometria', 'Geometria Plana'),
('Matemática', 'Polinômios e Identidade Polinomial', 'Polinômios'),
('Matemática', 'Polinômios e Relações Geométricas', 'Polinômios'),
('Matemática', 'Polinômios e equações algébricas', 'Equações e Inequações'),
('Matemática', 'Porcentagem - Taxa de Crescimento', 'Porcentagem'),
('Matemática', 'Porcentagem / Conversão Decimal', 'Porcentagem'),
('Matemática', 'Porcentagem / Equação de Concentração e Misturas', 'Porcentagem'),
('Matemática', 'Porcentagem / Matemática Financeira', 'Matemática Financeira'),
('Matemática', 'Porcentagem Sucessiva', 'Porcentagem'),
('Matemática', 'Porcentagem e Análise Gráfica', 'Porcentagem'),
('Matemática', 'Porcentagem e Conceitos', 'Porcentagem'),
('Matemática', 'Porcentagem e Descontos Sucessivos', 'Matemática Financeira'),
('Matemática', 'Porcentagem e Equações', 'Porcentagem'),
('Matemática', 'Porcentagem e Estatística', 'Estatística'),
('Matemática', 'Porcentagem e Estatística / Análise de gráficos', 'Estatística'),
('Matemática', 'Porcentagem e Frações', 'Porcentagem'),
('Matemática', 'Porcentagem e Matemática Comercial', 'Porcentagem'),
('Matemática', 'Porcentagem e Matemática Financeira', 'Matemática Financeira'),
('Matemática', 'Porcentagem e Misturas', 'Porcentagem'),
('Matemática', 'Porcentagem e Proporcionalidade', 'Porcentagem'),
('Matemática', 'Porcentagem e Proporcionalidade em Tabelas', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Porcentagem e Proporção', 'Porcentagem'),
('Matemática', 'Porcentagem e equações de 1º grau', 'Porcentagem'),
('Matemática', 'Porcentagem e matemática financeira', 'Matemática Financeira'),
('Matemática', 'Porcentagem, Razão e Proporção', 'Porcentagem'),
('Matemática', 'Potenciação e Equações Exponenciais', 'Logaritmos e Exponenciais'),
('Matemática', 'Potenciação e Expressões Numéricas', 'Potenciação e Radiciação'),
('Matemática', 'Probabilidade (Eventos Independentes)', 'Probabilidade'),
('Matemática', 'Probabilidade (Probabilidade Simples)', 'Probabilidade'),
('Matemática', 'Probabilidade - Campo Minado', 'Probabilidade'),
('Matemática', 'Probabilidade / Complementar', 'Probabilidade'),
('Matemática', 'Probabilidade / Estatística', 'Probabilidade'),
('Matemática', 'Probabilidade / Eventos independentes', 'Probabilidade');

COMMIT;
