-- ============================================================================
-- BatCaverna — Migration 011 (Parte 1 de 5): Estrutura e Assuntos Canônicos
-- ============================================================================
BEGIN;

-- 1. Funde duplicatas exatas antes de criar restrição única
CREATE TEMP TABLE fusao_duplicata AS
SELECT id AS id_velho,
       FIRST_VALUE(id) OVER (PARTITION BY materia_id, nome ORDER BY id) AS id_novo
FROM assuntos;

DELETE FROM fusao_duplicata WHERE id_velho = id_novo;

UPDATE questoes t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE bizus t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE concurso_assuntos t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE user_progresso t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE videoaulas t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE teoria_conteudo t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;
UPDATE plano_itens t SET assunto_id = f.id_novo FROM fusao_duplicata f WHERE t.assunto_id = f.id_velho;

DELETE FROM assuntos a USING fusao_duplicata f WHERE f.id_velho = a.id;

DROP TABLE IF EXISTS fusao_duplicata;

CREATE UNIQUE INDEX IF NOT EXISTS uniq_assunto_materia_nome
  ON assuntos(materia_id, nome);

-- 2. Criação da tabela auxiliar persistente para receber os lotes de mapa
CREATE TABLE IF NOT EXISTS _mapa_taxonomia_temp (
  materia   TEXT NOT NULL,
  antigo    TEXT NOT NULL,
  canonico  TEXT NOT NULL
);

TRUNCATE TABLE _mapa_taxonomia_temp;

-- 3. Garantir que todo assunto canônico existe na tabela assuntos
INSERT INTO assuntos (materia_id, nome)
SELECT DISTINCT m.id, v.canonico
FROM (VALUES
  ('Artes', 'Análise do Cartaz Publicitário'),
  ('Artes', 'Arte'),
  ('Artes', 'Arte Conceitual'),
  ('Artes', 'Arte Contemporânea'),
  ('Artes', 'Arte Moderna'),
  ('Artes', 'Arte Popular Brasileira'),
  ('Artes', 'Artes Visuais'),
  ('Artes', 'Campanha Institucional'),
  ('Artes', 'Campanha Publicitária'),
  ('Artes', 'Elementos da Linguagem Dramática'),
  ('Artes', 'Esporte Eletrônico'),
  ('Artes', 'Festival Folclórico de Parintins'),
  ('Artes', 'História da Arte'),
  ('Artes', 'Histórias em Quadrinhos'),
  ('Artes', 'Inclusão Transgênero no Esporte Olímpico'),
  ('Artes', 'Literatura de Cordel'),
  ('Artes', 'Maneirismo'),
  ('Artes', 'Manguebeat'),
  ('Artes', 'Manifestações Folclóricas'),
  ('Artes', 'Minimalismo'),
  ('Artes', 'Movimentos Artísticos'),
  ('Artes', 'Mudança Lexical'),
  ('Artes', 'Música'),
  ('Artes', 'Patrimônio e Cultura Popular'),
  ('Artes', 'Releitura'),
  ('Artes', 'Saúde Mental'),
  ('Artes', 'Sociologia do Esporte'),
  ('Artes', 'Teatro e Dança'),
  ('Atualidades', 'Acesso À Informação'),
  ('Atualidades', 'Ciência e Tecnologia'),
  ('Atualidades', 'Inteligência Coletiva'),
  ('Atualidades', 'Software Livre'),
  ('Biologia', 'Biologia Molecular'),
  ('Biologia', 'Bioquímica'),
  ('Biologia', 'Botânica'),
  ('Biologia', 'Citologia'),
  ('Biologia', 'Ecologia'),
  ('Biologia', 'Embriologia e Histologia'),
  ('Biologia', 'Etologia'),
  ('Biologia', 'Evolução'),
  ('Biologia', 'Fisiologia Humana'),
  ('Biologia', 'Genética'),
  ('Biologia', 'Microbiologia e Doenças'),
  ('Biologia', 'Tipagem Sanguínea'),
  ('Biologia', 'Toxicologia'),
  ('Biologia', 'Virologia'),
  ('Biologia', 'Zoologia'),
  ('Ciências Humanas', 'Acumulação de Riqueza'),
  ('Ciências Humanas', 'Amor Fati'),
  ('Ciências Humanas', 'Atividade Mineradora'),
  ('Ciências Humanas', 'Brasil Colônia'),
  ('Ciências Humanas', 'Brasil República'),
  ('Ciências Humanas', 'Cartografia'),
  ('Ciências Humanas', 'Ciclo Sedimentar'),
  ('Ciências Humanas', 'Climatologia'),
  ('Ciências Humanas', 'Condição de Transitoriedade'),
  ('Ciências Humanas', 'Cotidiano Urbano'),
  ('Ciências Humanas', 'Cultura e Identidade'),
  ('Ciências Humanas', 'Desigualdade e Estratificação'),
  ('Ciências Humanas', 'Diplomacia'),
  ('Ciências Humanas', 'Energia e Recursos'),
  ('Ciências Humanas', 'Escola Nova'),
  ('Ciências Humanas', 'Espiritualidade Franciscana'),
  ('Ciências Humanas', 'Filosofia Política'),
  ('Ciências Humanas', 'Formas de Resistência'),
  ('Ciências Humanas', 'Globalização'),
  ('Ciências Humanas', 'Globalização e Economia'),
  ('Ciências Humanas', 'Hidrografia'),
  ('Ciências Humanas', 'Hierarquias Sociais'),
  ('Ciências Humanas', 'História Contemporânea'),
  ('Ciências Humanas', 'História Militar do Brasil'),
  ('Ciências Humanas', 'História do Brasil'),
  ('Ciências Humanas', 'Idade Média'),
  ('Ciências Humanas', 'Indústria'),
  ('Ciências Humanas', 'Luta de Classes'),
  ('Ciências Humanas', 'Modais de Transporte'),
  ('Ciências Humanas', 'Método Dialético'),
  ('Ciências Humanas', 'Perfil Carcerário'),
  ('Ciências Humanas', 'Pluralidade de Demandas Sociais na Revolução Inglesa'),
  ('Ciências Humanas', 'Protagonismo Indígena'),
  ('Ciências Humanas', 'Questões Ambientais'),
  ('Ciências Humanas', 'Regionalização'),
  ('Ciências Humanas', 'Rituais Tradicionais'),
  ('Ciências Humanas', 'Saberes Tradicionais'),
  ('Ciências Humanas', 'Segurança Hídrica'),
  ('Ciências Humanas', 'Teoria do Conhecimento'),
  ('Ciências Humanas', 'Trabalho e Sociedade'),
  ('Ciências Humanas', 'Transição Social'),
  ('Ciências Humanas', 'Urbanização'),
  ('Ciências da Natureza', 'Astronomia'),
  ('Ciências da Natureza', 'Atomística e Tabela Periódica'),
  ('Ciências da Natureza', 'Bioquímica'),
  ('Ciências da Natureza', 'Botânica'),
  ('Ciências da Natureza', 'Citologia'),
  ('Ciências da Natureza', 'Dinâmica'),
  ('Ciências da Natureza', 'Ecologia'),
  ('Ciências da Natureza', 'Eletrodinâmica'),
  ('Ciências da Natureza', 'Eletromagnetismo'),
  ('Ciências da Natureza', 'Eletroquímica'),
  ('Ciências da Natureza', 'Estequiometria'),
  ('Ciências da Natureza', 'Evolução'),
  ('Ciências da Natureza', 'Fisiologia Humana'),
  ('Ciências da Natureza', 'Funções Inorgânicas'),
  ('Ciências da Natureza', 'Física Moderna'),
  ('Ciências da Natureza', 'Gases'),
  ('Ciências da Natureza', 'Genética'),
  ('Ciências da Natureza', 'Hidrostática'),
  ('Ciências da Natureza', 'Meio Ambiente'),
  ('Ciências da Natureza', 'Microbiologia e Doenças'),
  ('Ciências da Natureza', 'Ondulatória'),
  ('Ciências da Natureza', 'Química Orgânica'),
  ('Ciências da Natureza', 'S-tungstênio'),
  ('Ciências da Natureza', 'Separação de Misturas'),
  ('Ciências da Natureza', 'Termodinâmica'),
  ('Ciências da Natureza', 'Óptica'),
  ('Educação Física', 'Esporte e Prática Esportiva'),
  ('Educação Física', 'Esportes Individuais'),
  ('Educação Física', 'História e Sociologia do Esporte'),
  ('Educação Física', 'Jogos, Lazer e Cultura Corporal'),
  ('Educação Física', 'Padrões Estéticos'),
  ('Educação Física', 'Práticas Corporais'),
  ('Educação Física', 'Relações de Gênero'),
  ('Educação Física', 'Saúde e Qualidade de Vida'),
  ('Educação Física', 'Valores Olímpicos'),
  ('Filosofia', 'Dualismo Cartesiano'),
  ('Filosofia', 'Dualismo Metafísico'),
  ('Filosofia', 'Estocismo'),
  ('Filosofia', 'Estética'),
  ('Filosofia', 'Filosofia Antiga'),
  ('Filosofia', 'Filosofia Contemporânea'),
  ('Filosofia', 'Filosofia Grega'),
  ('Filosofia', 'Filosofia Medieval'),
  ('Filosofia', 'Filosofia Política'),
  ('Filosofia', 'Filosofia Pré-socrática'),
  ('Filosofia', 'Filosofia do Direito'),
  ('Filosofia', 'Geopolítica'),
  ('Filosofia', 'Historicidade'),
  ('Filosofia', 'Lógica'),
  ('Filosofia', 'Natureza da Atividade Filosófica'),
  ('Filosofia', 'Niilismo Contemporâneo'),
  ('Filosofia', 'Relação Homem-natureza'),
  ('Filosofia', 'Teoria do Conhecimento'),
  ('Filosofia', 'Utilitarismo'),
  ('Filosofia', 'Ética e Moral'),
  ('Física', 'Cinemática'),
  ('Física', 'Conservação'),
  ('Física', 'Dinâmica'),
  ('Física', 'Eletrodinâmica'),
  ('Física', 'Eletromagnetismo'),
  ('Física', 'Eletrostática'),
  ('Física', 'Estática'),
  ('Física', 'Fontes de Energia'),
  ('Física', 'Física Experimental'),
  ('Física', 'Física Geral'),
  ('Física', 'Física Moderna'),
  ('Física', 'Gravitação'),
  ('Física', 'Hidrostática'),
  ('Física', 'Impulso e Quantidade de Movimento'),
  ('Física', 'Mecânica'),
  ('Física', 'Movimento Harmônico Simples'),
  ('Física', 'Notação Científica'),
  ('Física', 'Ondulatória'),
  ('Física', 'Termodinâmica'),
  ('Física', 'Termologia e Calorimetria'),
  ('Física', 'Trabalho, Energia e Potência'),
  ('Física', 'Óptica'),
  ('Geografia', 'Agropecuária e Espaço Rural'),
  ('Geografia', 'Agrotóxicos'),
  ('Geografia', 'Biomas e Vegetação'),
  ('Geografia', 'Cartografia'),
  ('Geografia', 'Climatologia'),
  ('Geografia', 'Direitos Territoriais Indígenas'),
  ('Geografia', 'Domínios Morfoclimáticos'),
  ('Geografia', 'Ecologia Humana'),
  ('Geografia', 'Economia Global'),
  ('Geografia', 'Energia e Recursos'),
  ('Geografia', 'Espaço Público'),
  ('Geografia', 'Espaço Urbano Contemporâneo'),
  ('Geografia', 'Função Social da Propriedade'),
  ('Geografia', 'Geografia Agrária'),
  ('Geografia', 'Geografia Cultural'),
  ('Geografia', 'Geografia Econômica'),
  ('Geografia', 'Geografia Técnica'),
  ('Geografia', 'Geomorfologia e Relevo'),
  ('Geografia', 'Geopolítica'),
  ('Geografia', 'Gestão Territorial'),
  ('Geografia', 'Globalização e Economia'),
  ('Geografia', 'Hidrogeografia'),
  ('Geografia', 'Hidrografia'),
  ('Geografia', 'Imperialismo'),
  ('Geografia', 'Inclusão Digital'),
  ('Geografia', 'Indústria'),
  ('Geografia', 'Organização Político-administrativa'),
  ('Geografia', 'População e Demografia'),
  ('Geografia', 'Processos Cársticos'),
  ('Geografia', 'Questões Ambientais'),
  ('Geografia', 'Regulação do Espaço Urbano'),
  ('Geografia', 'Revolução Verde'),
  ('Geografia', 'Saúde Pública'),
  ('Geografia', 'Sensoriamento Remoto'),
  ('Geografia', 'Transformação da Paisagem'),
  ('Geografia', 'Transportes'),
  ('Geografia', 'Urbanização'),
  ('Geografia', 'Verticalização'),
  ('História', 'América Pré-colombiana'),
  ('História', 'Brasil Colônia'),
  ('História', 'Brasil Império'),
  ('História', 'Brasil República'),
  ('História', 'Colonização da América'),
  ('História', 'Comércio dos Regatões na Amazônia'),
  ('História', 'Conflitos no Oriente Médio'),
  ('História', 'Conhecimento'),
  ('História', 'Conquista da América'),
  ('História', 'Círio de Nazaré'),
  ('História', 'Direitos Civis Nos EUA'),
  ('História', 'Direitos Reprodutivos'),
  ('História', 'Etnocentrismo'),
  ('História', 'Expansão Marítima'),
  ('História', 'Expedições Científicas'),
  ('História', 'Guerra Fria'),
  ('História', 'Guerras Mundiais'),
  ('História', 'História Contemporânea'),
  ('História', 'História Moderna'),
  ('História', 'História da Arquitetura'),
  ('História', 'História da África'),
  ('História', 'História das Mentalidades'),
  ('História', 'História do Brasil'),
  ('História', 'História do Trabalho'),
  ('História', 'Idade Antiga'),
  ('História', 'Idade Moderna'),
  ('História', 'Idade Média'),
  ('História', 'Inquisição'),
  ('História', 'Modernização Tecnológica no Final do Século XIX'),
  ('História', 'Movimento Abolicionista'),
  ('História', 'Movimento Abolicionista na Arte'),
  ('História', 'Movimentos Emancipacionistas'),
  ('História', 'Obras Públicas no Nordeste'),
  ('História', 'Ocupação da Amazônia'),
  ('História', 'Patrimônio'),
  ('História', 'Revoluções'),
  ('Inglês', 'Adjectives and Adverbs'),
  ('Inglês', 'Articles and Determiners'),
  ('Inglês', 'Comparatives and Superlatives'),
  ('Inglês', 'Conditionals'),
  ('Inglês', 'Conflito de Anseios'),
  ('Inglês', 'Conjunctions and Connectors'),
  ('Inglês', 'Culto À Celebridade'),
  ('Inglês', 'Denotação'),
  ('Inglês', 'Direitos Civis'),
  ('Inglês', 'Diversidade Cultural'),
  ('Inglês', 'Funções da Linguagem'),
  ('Inglês', 'Gramática e Estrutura da Frase'),
  ('Inglês', 'Leitura de Cartum'),
  ('Inglês', 'Leitura de Infográficos'),
  ('Inglês', 'Leitura de Tirinha'),
  ('Inglês', 'Linguagem Figurada'),
  ('Inglês', 'Linguagem Publicitária'),
  ('Inglês', 'Literatura'),
  ('Inglês', 'Modal Verbs'),
  ('Inglês', 'Morfologia: Plural de Substantivos'),
  ('Inglês', 'Passive Voice'),
  ('Inglês', 'Phrasal Verbs'),
  ('Inglês', 'Poesia Contemporânea'),
  ('Inglês', 'Prepositions'),
  ('Inglês', 'Pronouns'),
  ('Inglês', 'Reading Comprehension'),
  ('Inglês', 'Recursos Estilísticos'),
  ('Inglês', 'Reported Speech'),
  ('Inglês', 'Sequenciamento'),
  ('Inglês', 'Subjetividade'),
  ('Inglês', 'Substituição Pronomial'),
  ('Inglês', 'Tempos'),
  ('Inglês', 'Valor Semântico do Modo Imperativo'),
  ('Inglês', 'Valores Culturais'),
  ('Inglês', 'Variação Linguística'),
  ('Inglês', 'Verb Tenses'),
  ('Inglês', 'Vocabulary'),
  ('Inglês', 'Word Formation'),
  ('Literatura', 'Adaptação Literária em Quadrinhos'),
  ('Literatura', 'Barroco e Arcadismo'),
  ('Literatura', 'Declínio Físico'),
  ('Literatura', 'Estilo Machadiano'),
  ('Literatura', 'Foco Narrativo'),
  ('Literatura', 'Função Social da Arte'),
  ('Literatura', 'Funções da Linguagem'),
  ('Literatura', 'Gênero Crônica'),
  ('Literatura', 'Gêneros e Análise Literária'),
  ('Literatura', 'Identidade'),
  ('Literatura', 'Literatura Afro-brasileira'),
  ('Literatura', 'Literatura Contemporânea'),
  ('Literatura', 'Literatura Testemunhal'),
  ('Literatura', 'Literatura da Ditadura Militar'),
  ('Literatura', 'Modernismo'),
  ('Literatura', 'Parnasianismo e Simbolismo'),
  ('Literatura', 'Realismo e Naturalismo'),
  ('Literatura', 'Regionalismo'),
  ('Literatura', 'Relações Familiares'),
  ('Literatura', 'Romance Histórico-social'),
  ('Literatura', 'Romance de 30'),
  ('Literatura', 'Romantismo'),
  ('Literatura', 'Teatro Brasileiro'),
  ('Matemática', 'Análise Combinatória'),
  ('Matemática', 'Análise Gráfica'),
  ('Matemática', 'Análise de Gráficos e Tabelas'),
  ('Matemática', 'Aritmética'),
  ('Matemática', 'Conjuntos Numéricos'),
  ('Matemática', 'Cálculo Diferencial e Integral'),
  ('Matemática', 'Equações e Inequações'),
  ('Matemática', 'Estatística'),
  ('Matemática', 'Função Afim'),
  ('Matemática', 'Função Quadrática'),
  ('Matemática', 'Funções'),
  ('Matemática', 'Geometria Analítica'),
  ('Matemática', 'Geometria Espacial'),
  ('Matemática', 'Geometria Plana'),
  ('Matemática', 'Grandezas e Medidas'),
  ('Matemática', 'Logaritmos e Exponenciais'),
  ('Matemática', 'Matemática Financeira'),
  ('Matemática', 'Matrizes, Determinantes e Sistemas'),
  ('Matemática', 'Movimento Circular Uniforme'),
  ('Matemática', 'Números Complexos'),
  ('Matemática', 'Orientação Espacial'),
  ('Matemática', 'Polinômios'),
  ('Matemática', 'Porcentagem'),
  ('Matemática', 'Potenciação e Radiciação'),
  ('Matemática', 'Probabilidade'),
  ('Matemática', 'Progressões'),
  ('Matemática', 'Raciocínio Lógico'),
  ('Matemática', 'Razão, Proporção e Regra de Três'),
  ('Matemática', 'Saúde'),
  ('Matemática', 'Sequências e Recorrências'),
  ('Matemática', 'Teoria dos Números'),
  ('Matemática', 'Trigonometria'),
  ('Matemática', 'Álgebra'),
  ('Português', 'Acentuação Gráfica'),
  ('Português', 'Adequação Vocabular'),
  ('Português', 'Adjunto Adverbial'),
  ('Português', 'Alegoria Política Nos Anos 1970'),
  ('Português', 'Análise Crítica da Linguagem'),
  ('Português', 'Análise Discursiva'),
  ('Português', 'Análise Linguística'),
  ('Português', 'Análise Textual'),
  ('Português', 'Análise de Discurso'),
  ('Português', 'Análise de Discurso Digital'),
  ('Português', 'Análise de Discurso Publicitário'),
  ('Português', 'Análise de Linguagem Mista'),
  ('Português', 'Análise de Linguagem Verbal'),
  ('Português', 'Análise de Tiras'),
  ('Português', 'Análise do Discurso e Argumentação'),
  ('Português', 'Arte Memorial'),
  ('Português', 'Aspectos Sociais da Saúde'),
  ('Português', 'Ativismo Digital'),
  ('Português', 'Campanha Publicitária de Saúde Pública'),
  ('Português', 'Campanhas Comunitárias'),
  ('Português', 'Campanhas de Conscientização'),
  ('Português', 'Ciclo Hidrológico'),
  ('Português', 'Circulação de Informações'),
  ('Português', 'Classificação dos Advérbios'),
  ('Português', 'Coesão e Coerência'),
  ('Português', 'Colocação Pronominal'),
  ('Português', 'Comparação Textual'),
  ('Português', 'Comunicação Digital'),
  ('Português', 'Comunicação Publicitária Social'),
  ('Português', 'Concordância'),
  ('Português', 'Condição Feminina no Século XIX'),
  ('Português', 'Crase'),
  ('Português', 'Crônica'),
  ('Português', 'Cultura'),
  ('Português', 'Dança Contemporânea'),
  ('Português', 'Democratização do Esporte'),
  ('Português', 'Dialeto Social'),
  ('Português', 'Discurso Digital'),
  ('Português', 'Discurso Direto'),
  ('Português', 'Discurso Intimidador'),
  ('Português', 'Divisão de Informações Sem Imprensa'),
  ('Português', 'Divulgação Científica'),
  ('Português', 'Documentários'),
  ('Português', 'Emprego do Artigo Definido'),
  ('Português', 'Estratégias Argumentativas em Divulgação Científica'),
  ('Português', 'Estrutura de Prefácio em Quadrinhos'),
  ('Português', 'Estética Brasiliense'),
  ('Português', 'Exposição Parental'),
  ('Português', 'Ficção Urbana dos Anos 1950'),
  ('Português', 'Figuras de Linguagem'),
  ('Português', 'Fonologia'),
  ('Português', 'Função Emotiva'),
  ('Português', 'Funções da Linguagem'),
  ('Português', 'Gramática'),
  ('Português', 'Gênero Notícia'),
  ('Português', 'Gênero Piada'),
  ('Português', 'Gênero Rede Social'),
  ('Português', 'Gênero Reportagem'),
  ('Português', 'Gênero Resenha'),
  ('Português', 'Gêneros'),
  ('Português', 'Gêneros Digitais'),
  ('Português', 'Gêneros Literários'),
  ('Português', 'Gêneros de Conscientização Pública'),
  ('Português', 'Gêneros e Tipologia Textual'),
  ('Português', 'Hibridismo Cultural'),
  ('Português', 'História'),
  ('Português', 'História dos Meios de Comunicação'),
  ('Português', 'Identidade Cultural'),
  ('Português', 'Imersão Lírica'),
  ('Português', 'Imprensa Histórica'),
  ('Português', 'Impressionismo na Prosa Poética'),
  ('Português', 'Infografia'),
  ('Português', 'Inteligência Artificial'),
  ('Português', 'Interpretação de Texto'),
  ('Português', 'Linguagem'),
  ('Português', 'Linguagem Publicitária'),
  ('Português', 'Linguagem Verbal'),
  ('Português', 'Lirismo'),
  ('Português', 'Lirismo Contemporâneo'),
  ('Português', 'Literatura'),
  ('Português', 'Marcas Informais'),
  ('Português', 'Morfologia'),
  ('Português', 'Morfossintaxe'),
  ('Português', 'Multilinguismo'),
  ('Português', 'Multimodalidade'),
  ('Português', 'Mídias Digitais'),
  ('Português', 'Notícias'),
  ('Português', 'Níveis de Linguagem'),
  ('Português', 'Oralidade Vs. Escrita'),
  ('Português', 'Oratória Acadêmica'),
  ('Português', 'Orientação Pediátrica'),
  ('Português', 'Ortografia'),
  ('Português', 'Patrimônio Linguístico'),
  ('Português', 'Pontuação'),
  ('Português', 'Pop Art'),
  ('Português', 'Postura Crítica Frente À Informação Midiática'),
  ('Português', 'Preservação do Patrimônio Linguístico'),
  ('Português', 'Projeto Poético'),
  ('Português', 'Prosa Contemporânea'),
  ('Português', 'Prosa Narrativa'),
  ('Português', 'Prosa de Ficção Contemporânea'),
  ('Português', 'Publicidade'),
  ('Português', 'Purismo Linguístico'),
  ('Português', 'Racismo'),
  ('Português', 'Recursos Gráficos'),
  ('Português', 'Recursos Linguísticos'),
  ('Português', 'Recursos de Empatia'),
  ('Português', 'Redes Sociais'),
  ('Português', 'Registros Formais'),
  ('Português', 'Regência'),
  ('Português', 'Relação Entre o Erudito'),
  ('Português', 'Relevância Estética'),
  ('Português', 'Reposicionamento Estético'),
  ('Português', 'Resenhas Críticas'),
  ('Português', 'Ritmo Acelerado'),
  ('Português', 'Semântica'),
  ('Português', 'Sintaxe'),
  ('Português', 'Sociolinguística'),
  ('Português', 'Tabu Linguístico'),
  ('Português', 'Tecnologia'),
  ('Português', 'Teoria Literária'),
  ('Português', 'Transformações Nas Experiências Lúdicas Infantis'),
  ('Português', 'Transitividade Verbal'),
  ('Português', 'Transposição de Discurso Direto'),
  ('Português', 'Variantes Linguísticas'),
  ('Português', 'Variação'),
  ('Português', 'Variação Linguística'),
  ('Português', 'Variação Pronominal'),
  ('Português', 'Verbos'),
  ('Português', 'Violência Colonial'),
  ('Português', 'Violência Institucional'),
  ('Português', 'Viés Racial Nas Mídias Digitais'),
  ('Química', 'Atomística e Tabela Periódica'),
  ('Química', 'Cinética Química'),
  ('Química', 'Densidade'),
  ('Química', 'Eletroquímica'),
  ('Química', 'Equilíbrio Químico'),
  ('Química', 'Estados da Matéria'),
  ('Química', 'Estequiometria'),
  ('Química', 'Estudo da Matéria'),
  ('Química', 'Fontes de Energia'),
  ('Química', 'Funções Inorgânicas'),
  ('Química', 'Físico-química'),
  ('Química', 'Físico-química de Surfactantes'),
  ('Química', 'Gases'),
  ('Química', 'História da Química'),
  ('Química', 'Indústria'),
  ('Química', 'Interações Intermoleculares'),
  ('Química', 'Ligações Químicas'),
  ('Química', 'Materiais'),
  ('Química', 'Métodos de Purificação'),
  ('Química', 'Métodos de Separação'),
  ('Química', 'Propriedades Coligativas'),
  ('Química', 'Propriedades Físicas dos Compostos Orgânicos'),
  ('Química', 'Química Ambiental'),
  ('Química', 'Química Orgânica'),
  ('Química', 'Química Verde'),
  ('Química', 'Radioatividade'),
  ('Química', 'Reações Químicas'),
  ('Química', 'Separação de Misturas'),
  ('Química', 'Soluções'),
  ('Química', 'Termoquímica'),
  ('Química', 'Ácidos, Bases e pH'),
  ('Sociologia', 'Ações Afirmativas'),
  ('Sociologia', 'Biografia'),
  ('Sociologia', 'Cidadania e Direitos'),
  ('Sociologia', 'Cultura e Identidade'),
  ('Sociologia', 'Desigualdade e Estratificação'),
  ('Sociologia', 'Estado e Poder'),
  ('Sociologia', 'Filosofia da Mente'),
  ('Sociologia', 'Foucault'),
  ('Sociologia', 'Função Social da Propriedade'),
  ('Sociologia', 'Impactos Sociais da Tecnologia Espacial'),
  ('Sociologia', 'Intolerância Religiosa'),
  ('Sociologia', 'Liderança Indígena'),
  ('Sociologia', 'Modernidade Urbana'),
  ('Sociologia', 'Movimentos Sociais'),
  ('Sociologia', 'Redes Sociais'),
  ('Sociologia', 'Relações'),
  ('Sociologia', 'Relações Étnico-raciais'),
  ('Sociologia', 'Religiosidade Popular'),
  ('Sociologia', 'Ritos de Passagem'),
  ('Sociologia', 'Saberes Tradicionais'),
  ('Sociologia', 'Saúde Pública'),
  ('Sociologia', 'Segregação Racial'),
  ('Sociologia', 'Sociedade Industrial'),
  ('Sociologia', 'Sociedade do Espetáculo'),
  ('Sociologia', 'Sociologia Ambiental'),
  ('Sociologia', 'Sociologia da Modernidade'),
  ('Sociologia', 'Tecnologia'),
  ('Sociologia', 'Teóricos Clássicos'),
  ('Sociologia', 'Trabalho e Sociedade'),
  ('Sociologia', 'Transformações Históricas do Dogma'),
  ('Sociologia', 'Utopia'),
  ('Sociologia', 'Violência e Segurança')
) AS v(materia, canonico)
JOIN materias m ON m.nome = v.materia
ON CONFLICT (materia_id, nome) DO NOTHING;


COMMIT;
