-- ============================================================================
-- BatCaverna — Migration 011 (Parte 2 de 5): Mapeamentos Lote 1/3
-- ============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS _mapa_taxonomia_temp (
  materia   TEXT NOT NULL,
  antigo    TEXT NOT NULL,
  canonico  TEXT NOT NULL
);

INSERT INTO _mapa_taxonomia_temp (materia, antigo, canonico) VALUES
('Artes', 'Análise do Cartaz Publicitário e Leitura', 'Análise do Cartaz Publicitário'),
('Artes', 'Arte Afro-brasileira e Multiculturalidade', 'Patrimônio e Cultura Popular'),
('Artes', 'Arte Contemporânea e Body Art', 'Arte Contemporânea'),
('Artes', 'Arte Contemporânea e Instalação', 'Arte Contemporânea'),
('Artes', 'Arte Contemporânea e Memória Colonial (Adriana Varejão)', 'Arte Contemporânea'),
('Artes', 'Arte Indígena / Cosmologia e Adornos', 'Patrimônio e Cultura Popular'),
('Artes', 'Arte Indígena e Escultura Sacra (Bancos Tukano e Kamayurá)', 'Artes Visuais'),
('Artes', 'Arte Moderna e Ressignificação de Objetos / Readymade', 'Arte Moderna'),
('Artes', 'Arte Popular Brasileira e Materialidade (Ilha do Ferro - AL)', 'Arte Popular Brasileira'),
('Artes', 'Arte conceitual / Diálogo com o Ready-made', 'Arte Conceitual'),
('Artes', 'Arte concreta e matrizes afro-brasileiras', 'Patrimônio e Cultura Popular'),
('Artes', 'Arte contemporânea e interatividade', 'Arte Contemporânea'),
('Artes', 'Arte e Tecnologia (GPS Art)', 'Arte'),
('Artes', 'Artes Visuais Digitais e Redes Sociais', 'Artes Visuais'),
('Artes', 'Artes visuais e arte pública', 'Artes Visuais'),
('Artes', 'Campanha Institucional e Combate à Violência contra a Mulher', 'Campanha Institucional'),
('Artes', 'Campanha Publicitária e Direitos Humanos (UNICEF)', 'Campanha Publicitária'),
('Artes', 'Cerâmica Contemporânea x Tradicional', 'Arte Contemporânea'),
('Artes', 'Dança Contemporânea e Matrizes Afro-Brasileiras', 'Teatro e Dança'),
('Artes', 'Elementos da linguagem dramática (rubricas)', 'Elementos da Linguagem Dramática'),
('Artes', 'Escultura / Comparação entre Padrões Estéticos', 'Artes Visuais'),
('Artes', 'Esporte Eletrônico e Mercado Global', 'Esporte Eletrônico'),
('Artes', 'Festival Folclórico de Parintins e Esporte', 'Festival Folclórico de Parintins'),
('Artes', 'Fotografia / Processo Criativo e Acaso', 'Artes Visuais'),
('Artes', 'Grafite e arte urbana', 'Artes Visuais'),
('Artes', 'História da Arte Contemporânea e Representatividade (Dalton Paula)', 'Arte Contemporânea'),
('Artes', 'História da Arte e Perseguição Política (Lasar Segall)', 'História da Arte'),
('Artes', 'História e Difusão de Instrumentos Musicais', 'Música'),
('Artes', 'Histórias em Quadrinhos e Acessibilidade', 'Histórias em Quadrinhos'),
('Artes', 'Impressionismo na Arte Brasileira (Eliseu Visconti)', 'Movimentos Artísticos'),
('Artes', 'Inter-relação de Gêneros Musicais e Cultura Popular', 'Música'),
('Artes', 'Interdisciplinaridade na Música', 'Música'),
('Artes', 'Literatura de Cordel e Xilogravura', 'Literatura de Cordel'),
('Artes', 'Maneirismo / El Greco e distorção figurativa', 'Maneirismo'),
('Artes', 'Manguebeat / Hibridismo e renovação cultural', 'Manguebeat'),
('Artes', 'Manifestações Folclóricas e Regionais', 'Manifestações Folclóricas'),
('Artes', 'Minimalismo / Formas sintéticas no espaço', 'Minimalismo'),
('Artes', 'Mudança Lexical e Participação Social (Dicionário Michaelis)', 'Mudança Lexical'),
('Artes', 'Música Urbana Indígena (Rap Guarani-Kaiowá)', 'Música'),
('Artes', 'Música e Hibridismo Cultural no Pôr do Sol do Jacaré', 'Música'),
('Artes', 'Música popular brasileira e brasilidade', 'Música'),
('Artes', 'Patrimônio Imaterial e Cultura Afro-Amapaense (Marabaixo)', 'Patrimônio e Cultura Popular'),
('Artes', 'Releitura e Apropriação Artística', 'Releitura'),
('Artes', 'Representação do corpo e subjetividade moderna', 'Teatro e Dança'),
('Artes', 'Saúde Mental e Abuso no Esporte de Alto Rendimento', 'Saúde Mental'),
('Artes', 'Sociologia do Esporte e Lazer', 'Sociologia do Esporte'),
('Artes', 'Teatro de rua e manifestações cênicas', 'Teatro e Dança'),
('Artes', 'Vanguardas Europeias e Fotogramas', 'Movimentos Artísticos'),
('Artes', 'Vanguardas europeias e Expressionismo', 'Movimentos Artísticos'),
('Atualidades', 'Acesso à Informação e Análise de Dados', 'Acesso À Informação'),
('Atualidades', 'Direitos Humanos, Discriminação e Tecnologia', 'Ciência e Tecnologia'),
('Atualidades', 'Impactos da Tecnologia e Aplicativos', 'Ciência e Tecnologia'),
('Atualidades', 'Inteligência Coletiva e Redes de Conhecimento', 'Inteligência Coletiva'),
('Atualidades', 'Software Livre e Democratização do Conhecimento', 'Software Livre'),
('Biologia', 'Biologia Celular (Ciclo Celular e Câncer)', 'Citologia'),
('Biologia', 'Biologia Molecular (Código Genético)', 'Biologia Molecular'),
('Biologia', 'Biologia Molecular - Estrutura do DNA', 'Genética'),
('Biologia', 'Biomas Brasileiros', 'Ecologia'),
('Biologia', 'Bioquímica / Enzimas e Desnaturação', 'Bioquímica'),
('Biologia', 'Bioquímica / Enzimas e denaturação térmica', 'Bioquímica'),
('Biologia', 'Bioquímica / Fotossíntese Oxigênica e Anoxigênica', 'Bioquímica'),
('Biologia', 'Bioquímica / Processos Biotecnológicos', 'Bioquímica'),
('Biologia', 'Bioquímica / Respiração Celular', 'Citologia'),
('Biologia', 'Biotecnologia / Enzimas de restrição e DNA recombinante', 'Genética'),
('Biologia', 'Biotecnologia / Fitorremediação', 'Genética'),
('Biologia', 'Biotecnologia / Organismos Transgênicos', 'Genética'),
('Biologia', 'Biotecnologia / Transcriptase Reversa (RT-PCR)', 'Genética'),
('Biologia', 'Biotecnologia e Meio Ambiente', 'Genética'),
('Biologia', 'Biotecnologia e Saúde', 'Genética'),
('Biologia', 'Botânica (Anatomia Vegetal / Condução de Seiva)', 'Botânica'),
('Biologia', 'Botânica (Evolução das Plantas)', 'Evolução'),
('Biologia', 'Botânica (Hormônios Vegetais)', 'Fisiologia Humana'),
('Biologia', 'Botânica (Polinização)', 'Botânica'),
('Biologia', 'Botânica / Condução de seiva e transpiração', 'Botânica'),
('Biologia', 'Botânica e Biomas Brasileiros (Mangue)', 'Ecologia'),
('Biologia', 'Botânica e Fotossíntese', 'Bioquímica'),
('Biologia', 'Botânica e Reprodução Vegetal', 'Botânica'),
('Biologia', 'Ciclos Biogeoquímicos / Reações Redox', 'Ecologia'),
('Biologia', 'Ciclos Biogeoquímicos e Biogás', 'Ecologia'),
('Biologia', 'Citologia (Divisão Celular)', 'Citologia'),
('Biologia', 'Citologia - Membrana Plasmática', 'Citologia'),
('Biologia', 'Citologia - Osmose', 'Citologia'),
('Biologia', 'Citologia / Citoesqueleto', 'Citologia'),
('Biologia', 'Citologia / Divisão celular e meiose', 'Citologia'),
('Biologia', 'Citologia / Organelas Celulares', 'Citologia'),
('Biologia', 'Citologia / Orgânulos Celulares', 'Citologia'),
('Biologia', 'Citologia / Testes Antitumorais', 'Citologia'),
('Biologia', 'Citologia e Organelas Celulares', 'Citologia'),
('Biologia', 'Citologia — Membrana plasmática e estrutura celular', 'Citologia'),
('Biologia', 'Cytologia e Histologia (Organelas Celulares)', 'Citologia'),
('Biologia', 'Ecologia (Biorremediação)', 'Ecologia'),
('Biologia', 'Ecologia (Ciclo do Nitrogênio)', 'Ecologia'),
('Biologia', 'Ecologia (Ciclos Biogeoquímicos)', 'Ecologia'),
('Biologia', 'Ecologia (Conservação e Fluxo Gênico)', 'Ecologia'),
('Biologia', 'Ecologia (Relações Ecológicas)', 'Ecologia'),
('Biologia', 'Ecologia - Bioacumulação', 'Ecologia'),
('Biologia', 'Ecologia - Ciclos Biogeoquímicos', 'Ecologia'),
('Biologia', 'Ecologia - Impactos Ambientais', 'Ecologia'),
('Biologia', 'Ecologia - Interações Ecológicas', 'Ecologia'),
('Biologia', 'Ecologia / Bioacumulação e Tecido Adiposo', 'Ecologia'),
('Biologia', 'Ecologia / Biogeografia e Espécies Endêmicas', 'Ecologia'),
('Biologia', 'Ecologia / Biomas Brasileiros e Adaptações', 'Ecologia'),
('Biologia', 'Ecologia / Cadeias Alimentares e Toxinas', 'Ecologia'),
('Biologia', 'Ecologia / Ciclo do Carbono e Mudanças Climáticas', 'Ecologia'),
('Biologia', 'Ecologia / Ciclo do Nitrogênio', 'Ecologia'),
('Biologia', 'Ecologia / Espécies Invasoras e Biodiversidade', 'Ecologia'),
('Biologia', 'Ecologia / Eutrofização e Destino de Resíduos Orgânicos', 'Ecologia'),
('Biologia', 'Ecologia / Impactos Ambientais', 'Ecologia'),
('Biologia', 'Ecologia / Impactos Ambientais do Petróleo', 'Ecologia'),
('Biologia', 'Ecologia / Impactos ambientais e bioacumulação', 'Ecologia'),
('Biologia', 'Ecologia / Impactos do Saneamento nas Arboviroses', 'Ecologia'),
('Biologia', 'Ecologia / Lipossolubilidade de Tóxicos', 'Ecologia'),
('Biologia', 'Ecologia / Mimetismo', 'Ecologia'),
('Biologia', 'Ecologia / Poluição das Águas', 'Ecologia'),
('Biologia', 'Ecologia / Sucessão Ecológica', 'Ecologia'),
('Biologia', 'Ecologia e Agroflorestas', 'Ecologia'),
('Biologia', 'Ecologia e Bioenergética (Fotossíntese)', 'Ecologia'),
('Biologia', 'Ecologia e Ciclo do Carbono', 'Ecologia'),
('Biologia', 'Ecologia e Controle Populacional', 'Ecologia'),
('Biologia', 'Ecologia e Meio Ambiente', 'Ecologia'),
('Biologia', 'Ecologia — Relações ecológicas interespecíficas', 'Ecologia'),
('Biologia', 'Embriologia (Fecundação e Reação Acrossômica)', 'Embriologia e Histologia'),
('Biologia', 'Evolução / Seleção natural e resistência', 'Evolução'),
('Biologia', 'Evolução e Bioquímica Celular', 'Evolução'),
('Biologia', 'Evolução e Especiação', 'Evolução'),
('Biologia', 'Evolução e Reprodução dos Mamíferos', 'Evolução'),
('Biologia', 'Fisiologia Animal (Musculatura e Metabolismo Aeróbio)', 'Bioquímica'),
('Biologia', 'Fisiologia Animal e Ecológica', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Comparada e Adaptação', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana (Metabolismo Energético)', 'Bioquímica'),
('Biologia', 'Fisiologia Humana (Sistema Digestório)', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana (Sistema Reprodutor e Hormônios)', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana - Sangue', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana - Visão', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana / Sistema Digestório', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana / Sistema Digestório e pH', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana / Visão e Óptica Olhar', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana / Vitaminas e Avitaminoses', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana e Saúde', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Humana e Sistema Endócrino', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Muscular / Fibras Brancas e Vermelhas', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Sensorial e Genética (Visão)', 'Genética'),
('Biologia', 'Fisiologia Vegetal / Fitormônios e amadurecimento', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Vegetal / Fotossíntese', 'Bioquímica'),
('Biologia', 'Fisiologia Vegetal e Condução de Seiva', 'Fisiologia Humana'),
('Biologia', 'Fisiologia Vegetal e Nitrogênio', 'Fisiologia Humana'),
('Biologia', 'Genética (Aneuploidias e Meiose)', 'Genética'),
('Biologia', 'Genética - Herança Ligada ao Sexo', 'Genética'),
('Biologia', 'Genética / Alterações Cromossômicas', 'Genética'),
('Biologia', 'Genética / Biotecnologia', 'Genética'),
('Biologia', 'Genética / Equilíbrio de Hardy-Weinberg', 'Genética'),
('Biologia', 'Genética / Herança Genética e Codominância', 'Genética'),
('Biologia', 'Genética / Herança Ligada ao Sexo', 'Genética'),
('Biologia', 'Genética / Leis de Mendel e Cruzamentos', 'Genética'),
('Biologia', 'Genética / Mutações e heredograma', 'Genética'),
('Biologia', 'Genética Molecular (Eletroforese de DNA)', 'Genética'),
('Biologia', 'Genética e Biologia Molecular', 'Genética'),
('Biologia', 'Genética e Biotecnologia (Vacinas de RNAm)', 'Genética'),
('Biologia', 'Genética e Conceitos Fundamentais', 'Genética'),
('Biologia', 'Genética e Meiose (Recombinação)', 'Genética'),
('Biologia', 'Genética — Heredogramas e herança autossômica dominante', 'Genética'),
('Biologia', 'Hematologia e Terapias Celulares', 'Citologia'),
('Biologia', 'Histologia e Fisiologia — Tecido nervoso e condução do impulso', 'Fisiologia Humana'),
('Biologia', 'Imunologia', 'Fisiologia Humana'),
('Biologia', 'Imunologia / Mecanismo de Vacinas', 'Fisiologia Humana'),
('Biologia', 'Imunologia / Mecanismos de Ação das Vacinas', 'Fisiologia Humana'),
('Biologia', 'Imunologia / Vacinas versus Soros', 'Fisiologia Humana'),
('Biologia', 'Imunologia e Probióticos', 'Fisiologia Humana'),
('Biologia', 'Imunologia — Vacinas e resposta imunitária', 'Fisiologia Humana'),
('Biologia', 'Microbiologia / Controle bacteriano e antibióticos', 'Microbiologia e Doenças'),
('Biologia', 'Microbiologia / Respiração Celular e Fermentação', 'Citologia'),
('Biologia', 'Microbiologia e Doenças Humanas', 'Microbiologia e Doenças'),
('Biologia', 'Microbiologia e Farmacologia', 'Microbiologia e Doenças'),
('Biologia', 'Microbiologia e Virologia', 'Microbiologia e Doenças'),
('Biologia', 'Parasitologia (Leishmaniose)', 'Microbiologia e Doenças'),
('Biologia', 'Parasitologia / Densidade', 'Microbiologia e Doenças'),
('Biologia', 'Parasitologia e Imunologia', 'Fisiologia Humana'),
('Biologia', 'Relações Ecológicas', 'Ecologia'),
('Biologia', 'Saúde Pública / Doenças Parasitárias e Vetores', 'Microbiologia e Doenças'),
('Biologia', 'Saúde Pública / Parasitologia e Cuidados Alimentares', 'Microbiologia e Doenças'),
('Biologia', 'Saúde Pública e Parasitologia', 'Microbiologia e Doenças'),
('Biologia', 'Saúde Pública — Doenças infecciosas e parasitoses humanas', 'Microbiologia e Doenças'),
('Biologia', 'Taxonomia e Filogenia', 'Evolução'),
('Biologia', 'Tipagem Sanguínea (Sistemas ABO e Rh)', 'Tipagem Sanguínea'),
('Biologia', 'Toxicologia e Doses Letais', 'Toxicologia'),
('Biologia', 'Virologia e Saúde', 'Virologia'),
('Biologia', 'Zoologia / Artrópodes', 'Zoologia'),
('Biologia', 'Zoologia / Artrópodes e Mudas (Ecdise)', 'Zoologia'),
('Biologia', 'Zoologia / Artrópodes e vetores de doenças', 'Microbiologia e Doenças'),
('Biologia', 'Zoologia / Comportamento Animal', 'Zoologia'),
('Biologia', 'Zoologia / Fisiologia Animal / Adaptações de Aves', 'Fisiologia Humana'),
('Biologia', 'Zoologia e Ecologia (Desenvolvimento dos Insetos)', 'Ecologia'),
('Biologia', 'Zoologia e Hábitos Alimentares', 'Zoologia'),
('Ciências Humanas', 'Acumulação de riqueza e ideologia do mérito', 'Acumulação de Riqueza'),
('Ciências Humanas', 'Amor fati e crítica à tradição cristã', 'Amor Fati'),
('Ciências Humanas', 'Ascetismo medieval e desvalorização corpórea', 'Idade Média'),
('Ciências Humanas', 'Atividade mineradora e rompimento de vínculos locais', 'Atividade Mineradora'),
('Ciências Humanas', 'Brasil Colônia (Invasões Holandesas)', 'Brasil Colônia'),
('Ciências Humanas', 'Brasil Colônia (Período Joanino)', 'Brasil Colônia'),
('Ciências Humanas', 'Catástrofes urbanas e renovação das práticas sociais', 'Urbanização'),
('Ciências Humanas', 'Ciclo sedimentar e processos geomorfológicos', 'Ciclo Sedimentar'),
('Ciências Humanas', 'Clima e fatores climáticos', 'Climatologia'),
('Ciências Humanas', 'Condição de transitoriedade e refugiados', 'Condição de Transitoriedade'),
('Ciências Humanas', 'Cotidiano urbano e hierarquias sociais na escravidão', 'Cotidiano Urbano'),
('Ciências Humanas', 'Crise política e reação popular na morte de Vargas', 'Brasil República'),
('Ciências Humanas', 'Diplomacia e proibição do tráfico de escravizados', 'Diplomacia'),
('Ciências Humanas', 'Divisão internacional do trabalho e lixo eletrônico', 'Globalização e Economia'),
('Ciências Humanas', 'Era Populista / Governo JK e industrialização', 'Indústria'),
('Ciências Humanas', 'Era Vargas (Revolução de 1930)', 'Brasil República'),
('Ciências Humanas', 'Era Vargas / Segunda Guerra Mundial', 'Brasil República'),
('Ciências Humanas', 'Escola Nova e acesso igualitário baseado no mérito', 'Escola Nova'),
('Ciências Humanas', 'Espiritualidade franciscana e língua vulgar', 'Espiritualidade Franciscana'),
('Ciências Humanas', 'Estado Novo e levantamento de dados territoriais', 'Brasil República'),
('Ciências Humanas', 'Formas de resistência e contratação de escravizados', 'Formas de Resistência'),
('Ciências Humanas', 'Geografia Econômica e Neoliberalismo', 'Globalização'),
('Ciências Humanas', 'Geografia Urbana', 'Urbanização'),
('Ciências Humanas', 'Gestão urbana participativa e associações de bairro', 'Urbanização'),
('Ciências Humanas', 'Globalização e revolução técnico-científica', 'História Contemporânea'),
('Ciências Humanas', 'Hidrografia Brasileira', 'História do Brasil'),
('Ciências Humanas', 'Hidrografia e bacias hidrográficas', 'Hidrografia'),
('Ciências Humanas', 'Hierarquia urbana e redes de transporte', 'Urbanização'),
('Ciências Humanas', 'Hierarquias sociais e caracterização de minorias', 'Hierarquias Sociais'),
('Ciências Humanas', 'Indústria nacional e subordinação tecnológica', 'Indústria'),
('Ciências Humanas', 'Instituições de ensino e formação de identidades', 'Cultura e Identidade'),
('Ciências Humanas', 'Luta de classes e oposição de interesses', 'Luta de Classes'),
('Ciências Humanas', 'Matriz Energética', 'Energia e Recursos'),
('Ciências Humanas', 'Medicina colonial e conjugação de saberes empíricos', 'Brasil Colônia'),
('Ciências Humanas', 'Melhoramento genético e adaptação ambiental', 'Questões Ambientais'),
('Ciências Humanas', 'Metafísica e unidade essencial do conhecimento', 'Teoria do Conhecimento'),
('Ciências Humanas', 'Movimento de translação e projeção de sombras', 'Cartografia'),
('Ciências Humanas', 'Mulheres na ciência e estratificação social', 'Desigualdade e Estratificação'),
('Ciências Humanas', 'Método dialético e investigação filosófica', 'Método Dialético'),
('Ciências Humanas', 'Passividade social e crítica cultural', 'Cultura e Identidade'),
('Ciências Humanas', 'Pedagogia dos costumes e artefatos culturais', 'Cultura e Identidade'),
('Ciências Humanas', 'Perfil carcerário e inclusão social', 'Perfil Carcerário'),
('Ciências Humanas', 'Período Colonial / Invasões estrangeiras', 'Brasil Colônia'),
('Ciências Humanas', 'Pluralidade de demandas sociais na Revolução Inglesa', 'Pluralidade de Demandas Sociais na Revolução Inglesa'),
('Ciências Humanas', 'Políticas de conservação de bens culturais', 'Filosofia Política'),
('Ciências Humanas', 'Protagonismo indígena e novas tecnologias', 'Protagonismo Indígena'),
('Ciências Humanas', 'Práticas místicas e patrimônio cultural regional', 'Cultura e Identidade'),
('Ciências Humanas', 'Reconfiguração urbana e competitividade global', 'Urbanização'),
('Ciências Humanas', 'Reestruturação produtiva e precarização laboral', 'Trabalho e Sociedade'),
('Ciências Humanas', 'Regionalização e órgãos de desenvolvimento regional (SUDAM)', 'Regionalização'),
('Ciências Humanas', 'Relações de trabalho e saúde pós-expediente', 'Trabalho e Sociedade'),
('Ciências Humanas', 'República Oligárquica / Economia cafeeira e industrialização', 'Brasil República'),
('Ciências Humanas', 'República Populista (Governo Dutra)', 'Brasil República'),
('Ciências Humanas', 'República Populista (Governo JK)', 'Brasil República'),
('Ciências Humanas', 'Rituais tradicionais e coesão social', 'Rituais Tradicionais'),
('Ciências Humanas', 'Saberes tradicionais e conservação ambiental', 'Questões Ambientais'),
('Ciências Humanas', 'Saberes tradicionais e experiência perceptiva', 'Saberes Tradicionais'),
('Ciências Humanas', 'Segundo Reinado (Guerra do Paraguai)', 'História Militar do Brasil'),
('Ciências Humanas', 'Segundo Reinado / Guerra do Paraguai', 'História Militar do Brasil'),
('Ciências Humanas', 'Segurança hídrica e acesso equitativo aos recursos', 'Segurança Hídrica'),
('Ciências Humanas', 'Sociedade industrial e necessidades criadas', 'Indústria'),
('Ciências Humanas', 'Supressão de identidades e repressão cultural', 'Cultura e Identidade'),
('Ciências Humanas', 'Territorialização industrial e enclaves operários', 'Indústria'),
('Ciências Humanas', 'Transformação da paisagem geográfica urbana', 'Urbanização'),
('Ciências Humanas', 'Transição social e descompassos institucionais', 'Transição Social'),
('Ciências da Natureza', 'Astronomia e Astrofísica', 'Astronomia'),
('Ciências da Natureza', 'Atomística (Isótopos, Isóbaros e Isótonos)', 'Atomística e Tabela Periódica'),
('Ciências da Natureza', 'Bioquímica e Isometria', 'Bioquímica'),
('Ciências da Natureza', 'Botânica e Anatomia Vegetal', 'Botânica'),
('Ciências da Natureza', 'Cinemática e Dinâmica', 'Dinâmica'),
('Ciências da Natureza', 'Cinemática e Movimento Circular', 'Dinâmica'),
('Ciências da Natureza', 'Citologia (Organelas Celulares)', 'Citologia'),
('Ciências da Natureza', 'Dinâmica e Leis de Newton', 'Dinâmica'),
('Ciências da Natureza', 'Ecologia (Sucessão Ecológica)', 'Ecologia'),
('Ciências da Natureza', 'Ecologia e saúde pública (doenças)', 'Ecologia'),
('Ciências da Natureza', 'Eletrodinâmica e Circuitos', 'Eletrodinâmica'),
('Ciências da Natureza', 'Eletrodinâmica e Medidores Elétricos', 'Eletrodinâmica'),
('Ciências da Natureza', 'Eletroquímica (Pilhas)', 'Eletroquímica'),
('Ciências da Natureza', 'Evolução e Biologia Evolutiva', 'Evolução'),
('Ciências da Natureza', 'Fisiologia Cardíaca', 'Fisiologia Humana'),
('Ciências da Natureza', 'Fisiologia Humana (Trocas Gasosas)', 'Gases'),
('Ciências da Natureza', 'Fisiologia Humana e Comparada', 'Fisiologia Humana'),
('Ciências da Natureza', 'Funções Inorgânicas e Nomenclatura', 'Funções Inorgânicas'),
('Ciências da Natureza', 'Genética e Biologia Molecular', 'Estequiometria'),
('Ciências da Natureza', 'Genética e Histologia (Diferenciação Celular)', 'Genética'),
('Ciências da Natureza', 'Hidrostática (Vasos Comunicantes)', 'Hidrostática'),
('Ciências da Natureza', 'Meio Ambiente e Sustentabilidade', 'Meio Ambiente'),
('Ciências da Natureza', 'Microbiologia e Genética Bacteriana', 'Genética'),
('Ciências da Natureza', 'Ondas e Acústica', 'Ondulatória'),
('Ciências da Natureza', 'Ondulatória (Ondas Estacionárias)', 'Ondulatória'),
('Ciências da Natureza', 'Parasitologia Humana', 'Microbiologia e Doenças'),
('Ciências da Natureza', 'Química Geral e Inorgânica', 'Funções Inorgânicas'),
('Ciências da Natureza', 'Química Orgânica (Funções e Polímeros)', 'Química Orgânica'),
('Ciências da Natureza', 'Radioatividade e Soluções (Meia-vida)', 'Física Moderna'),
('Ciências da Natureza', 'Reações químicas inorgânicas', 'Funções Inorgânicas'),
('Ciências da Natureza', 'S-Tungstênio / Propriedades dos elementos químicos', 'S-tungstênio'),
('Ciências da Natureza', 'Tabela Periódica e Propriedades', 'Atomística e Tabela Periódica'),
('Ciências da Natureza', 'Termodinâmica e Calorimetria', 'Termodinâmica'),
('Ciências da Natureza', 'Átomos e íons (número atômico)', 'Atomística e Tabela Periódica'),
('Ciências da Natureza', 'Óptica Geométrica (Refratometria)', 'Óptica'),
('Ciências da Natureza', 'Óptica e Espectroscopia', 'Óptica'),
('Educação Física', 'Aptidão Física e Saúde', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Determinantes Socioeconômicos e Saúde', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Esporte de Alto Rendimento e Mídia', 'Esporte e Prática Esportiva'),
('Educação Física', 'Esporte e representatividade feminina / Quebra de estereótipos', 'Esporte e Prática Esportiva'),
('Educação Física', 'Esporte paralímpico e saúde', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Esporte, Cultura e Jogos Indígenas', 'Jogos, Lazer e Cultura Corporal'),
('Educação Física', 'Esporte, Inclusão Social e Políticas Públicas (Parasurf)', 'Esporte e Prática Esportiva'),
('Educação Física', 'Esporte, sociedade e formação profissional', 'Esporte e Prática Esportiva'),
('Educação Física', 'Esporte-participação e inclusão social', 'Esporte e Prática Esportiva'),
('Educação Física', 'Esportes de aventura / Mountainboard', 'Esporte e Prática Esportiva'),
('Educação Física', 'Gênero e Desigualdade no Esporte', 'Esporte e Prática Esportiva'),
('Educação Física', 'Gênero e Práticas Corporais (Lutas)', 'Esportes Individuais'),
('Educação Física', 'Gêneros Textuais / Esporte Paralímpico', 'Esporte e Prática Esportiva'),
('Educação Física', 'Lutas e Práticas Corporais', 'Esportes Individuais'),
('Educação Física', 'Lutas vs. Brigas (Conceitos das Práticas Corporais)', 'Esportes Individuais'),
('Educação Física', 'Modalidades esportivas coletivas e tática', 'Esporte e Prática Esportiva'),
('Educação Física', 'Mídia e Esporte Telespetáculo', 'Esporte e Prática Esportiva'),
('Educação Física', 'Padrões Estéticos e Transtornos Alimentares', 'Padrões Estéticos'),
('Educação Física', 'Práticas Corporais e Relações de Gênero', 'Práticas Corporais'),
('Educação Física', 'Práticas corporais e saúde pública / Desigualdade socioeconômica', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Relações de gênero e práticas corporais', 'Relações de Gênero'),
('Educação Física', 'Saúde Mental no Esporte', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Saúde e Hábitos Saudáveis na Escola', 'Saúde e Qualidade de Vida'),
('Educação Física', 'Transformações Sociais no Esporte', 'Esporte e Prática Esportiva'),
('Educação Física', 'Transformações e Inclusões nos Jogos Olímpicos', 'História e Sociologia do Esporte'),
('Educação Física', 'Valores Olímpicos e Paralímpicos', 'Valores Olímpicos'),
('Filosofia', 'A Cidade Ideal e a Justiça em Platão (A República)', 'Filosofia Antiga'),
('Filosofia', 'Conceito de Democracia / Soberania Popular', 'Filosofia Política'),
('Filosofia', 'Dualismo Cartesiano e Fenomenologia do Corpo', 'Dualismo Cartesiano'),
('Filosofia', 'Dualismo Metafísico / Corpo e Alma', 'Dualismo Metafísico'),
('Filosofia', 'Empirismo e Retórica (David Hume vs. Sofistas/Platão)', 'Teoria do Conhecimento'),
('Filosofia', 'Epistemologia / Empirismo e Positivismo Lógico', 'Teoria do Conhecimento'),
('Filosofia', 'Epistemologia / Raciocínio Indutivo', 'Teoria do Conhecimento'),
('Filosofia', 'Epistemologia e Concepção de Natureza em Humboldt', 'Teoria do Conhecimento'),
('Filosofia', 'Epistemologia e Injustiça Epistêmica', 'Teoria do Conhecimento'),
('Filosofia', 'Escola de Frankfurt e Indústria Cultural (Adorno e Horkheimer)', 'Filosofia Contemporânea'),
('Filosofia', 'Estocismo / Sêneca e serenidade da alma', 'Estocismo'),
('Filosofia', 'Estética / Percepção e vivência estética', 'Estética'),
('Filosofia', 'Existencialismo / Finitude Humana', 'Filosofia Contemporânea'),
('Filosofia', 'Existencialismo e Condição Humana', 'Filosofia Contemporânea'),
('Filosofia', 'Filosofia Contemporânea / Conceito de Rizoma', 'Filosofia Contemporânea'),
('Filosofia', 'Filosofia Grega / Origem da Polis e Sofistas', 'Filosofia Grega'),
('Filosofia', 'Filosofia Helenística (Ceticismo)', 'Teoria do Conhecimento'),
('Filosofia', 'Filosofia Medieval e Argumento Ontológico', 'Lógica'),
('Filosofia', 'Filosofia Medieval e Livre-Arbritrio em Santo Agostinho', 'Filosofia Medieval'),
('Filosofia', 'Filosofia Política e Estado de Natureza', 'Filosofia Política'),
('Filosofia', 'Filosofia Pré-Socrática (Ontologia)', 'Filosofia Pré-socrática'),
('Filosofia', 'Filosofia da Educação e Ética (Paulo Freire)', 'Ética e Moral'),
('Filosofia', 'Filosofia do Direito e Coexistência Social', 'Filosofia do Direito'),
('Filosofia', 'Filosofia do Direito e Desobediência Civil (Jacques Derrida)', 'Filosofia do Direito'),
('Filosofia', 'Filosofia política / Hannah Arendt e o discurso', 'Filosofia Política'),
('Filosofia', 'Formas de Governo em Aristóteles (A Política)', 'Filosofia Política'),
('Filosofia', 'Geopolítica e Reforma do Conselho de Segurança da ONU', 'Geopolítica'),
('Filosofia', 'Historicidade e Dimensões dos Direitos Humanos (Norberto Bobbio)', 'Historicidade'),
('Filosofia', 'Indústria Cultural e Escola de Frankfurt', 'Filosofia Contemporânea'),
('Filosofia', 'Liberalismo Econômico e Ética (Adam Smith)', 'Ética e Moral'),
('Filosofia', 'Pré-Socráticos e a Dialética do Devir (Heráclito de Éfeso)', 'Filosofia Antiga'),
('Filosofia', 'Pré-socráticos / Cosmologia de Empédocles', 'Filosofia Antiga'),
('Filosofia', 'Racionalismo Cartesiano', 'Teoria do Conhecimento'),
('Filosofia', 'Relação Homem-Natureza e Ecoturismo', 'Relação Homem-natureza'),
('Filosofia', 'Utilitarismo (Jeremy Bentham)', 'Utilitarismo'),
('Filosofia', 'Ética Aristotélica / Virtude e Eudaimonia', 'Ética e Moral'),
('Filosofia', 'Ética Contemporânea e Tecnoética', 'Ética e Moral'),
('Filosofia', 'Ética Kantiana / Imperativo Categórico', 'Ética e Moral'),
('Filosofia', 'Ética do Altruísmo e Empatia (Clarice Lispector)', 'Ética e Moral'),
('Filosofia', 'Ética do Cuidado e Inclusão de Pessoas com Deficiência', 'Ética e Moral'),
('Filosofia', 'Ética do Perdão e Autonomia (Paul Ricoeur)', 'Ética e Moral'),
('Filosofia', 'Ética e Felicidade em Schopenhauer', 'Ética e Moral'),
('Filosofia', 'Ética e Hospitalidade em Jacques Derrida', 'Ética e Moral'),
('Filosofia', 'Ética utilitarista e racionalidade pragmática', 'Ética e Moral'),
('Física', 'Calorimetria', 'Termologia e Calorimetria'),
('Física', 'Calorimetria e Isolamento Térmico', 'Termologia e Calorimetria'),
('Física', 'Cinemática (Lançamento Vertical)', 'Cinemática'),
('Física', 'Cinemática (MRU e MRUV)', 'Cinemática'),
('Física', 'Cinemática (Movimento Retilíneo Variado)', 'Cinemática'),
('Física', 'Cinemática (Movimento Uniforme e Tempo de Viagem)', 'Cinemática'),
('Física', 'Cinemática / Análise de Gráficos do Movimento', 'Cinemática'),
('Física', 'Cinemática / Consumo e Velocidade Média', 'Cinemática'),
('Física', 'Cinemática / Lançamento Horizontal', 'Cinemática'),
('Física', 'Cinemática / Movimento Circular Uniforme', 'Dinâmica'),
('Física', 'Cinemática / Movimento Uniforme e Encontro', 'Cinemática'),
('Física', 'Cinemática / Movimento Uniformemente Variado', 'Cinemática'),
('Física', 'Cinemática / Movimento Variado e Frenagem', 'Cinemática'),
('Física', 'Cinemática / Velocidade Média', 'Cinemática'),
('Física', 'Cinemática / Vetores e Decomposição de Velocidades', 'Cinemática'),
('Física', 'Cinemática Vetorial', 'Cinemática'),
('Física', 'Cinemática e Conservação de Energia', 'Trabalho, Energia e Potência'),
('Física', 'Cinemática e Movimento Circular', 'Dinâmica'),
('Física', 'Cinemática e Movimento de Veículos', 'Cinemática'),
('Física', 'Cinemática e Percepção Visual', 'Cinemática'),
('Física', 'Cinemática — Movimento Uniforme e Uniformemente Variado', 'Cinemática'),
('Física', 'Conservação da Energia Mecânica / Força Centrípeta', 'Trabalho, Energia e Potência'),
('Física', 'Conservação de Energia', 'Trabalho, Energia e Potência'),
('Física', 'Conservação e Dissipação de Energia', 'Conservação'),
('Física', 'Dinâmica (Atrito e Leis de Newton)', 'Dinâmica'),
('Física', 'Dinâmica (Plano Inclinado)', 'Dinâmica'),
('Física', 'Dinâmica / Força de Atrito e Plano Inclinado', 'Dinâmica'),
('Física', 'Dinâmica do Movimento Circular', 'Dinâmica'),
('Física', 'Dinâmica e Estática', 'Estática'),
('Física', 'Dinâmica e Mecânica Clássica', 'Dinâmica'),
('Física', 'Dinâmica e Movimento Circular', 'Dinâmica'),
('Física', 'Dinâmica e Plano Inclinado', 'Dinâmica'),
('Física', 'Dinâmica — Movimento circular e força de atrito', 'Dinâmica'),
('Física', 'Eletricidade (Eletrodinâmica)', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica (Circuitos Elétricos)', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica (Potência Elétrica)', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica (Resistência Elétrica)', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica - Associação de Resistores', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica - Circuitos Elétricos', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica - Resistência Elétrica', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Circuitos Elétricos', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Circuitos Elétricos e Amperímetro', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Circuitos Elétricos e Pontes', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Circuitos com LED', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Circuitos elétricos e potência', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Divisor de Tensão', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Divisor de Tensão e Associação de Resistores', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Geradores e Associação de Geradores', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Geradores e Curto-Circuito', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Potência Elétrica e Dispositivos de Proteção', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica / Segunda Lei de Ohm', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica e Circuitos Elétricos', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica e Consumo de Energia', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica e Potência Mecânica', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica e Óptica / Lentes e Resistores', 'Eletrodinâmica'),
('Física', 'Eletrodinâmica — Circuitos em paralelo e potência elétrica', 'Eletrodinâmica'),
('Física', 'Eletromagnetismo (Indução Eletromagnética)', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo - Indução', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Campo Magnético de Fio Retilíneo', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Campos Elétrico e Magnético', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Força Elétrica e Deflexão de Cargas', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Indução Eletromagnética (Lei de Lenz)', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Indução Eletromagnética e Efeito Joule', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo / Movimento de Carga em Campo Magnético', 'Eletromagnetismo'),
('Física', 'Eletromagnetismo Aplicado à Medicina', 'Eletromagnetismo'),
('Física', 'Eletrostática (Capacitores e Dielétricos)', 'Eletrodinâmica'),
('Física', 'Eletrostática / Blindagem Eletrostática', 'Eletrostática'),
('Física', 'Eletrostática / Campo Elétrico', 'Eletrostática'),
('Física', 'Eletrostática / Carga Elétrica e Potencial Elétrico', 'Eletrostática'),
('Física', 'Eletrostática / Gaiola de Faraday', 'Eletrostática'),
('Física', 'Eletrostática e Conservação de Energia', 'Eletrostática'),
('Física', 'Eletrostática e Eletromagnetismo', 'Eletromagnetismo'),
('Física', 'Estática (Alavancas)', 'Estática'),
('Física', 'Estática (Polias e Roldanas)', 'Estática'),
('Física', 'Estática / Roldanas', 'Estática'),
('Física', 'Estática do Corpo Rígido', 'Estática'),
('Física', 'Estática e Dinâmica', 'Estática'),
('Física', 'Estática e Dinâmica (Plano Inclinado e Atrito)', 'Estática'),
('Física', 'Estática e Hidrostática / Princípio de Pascal', 'Hidrostática'),
('Física', 'Estática e Polias Móveis', 'Estática'),
('Física', 'Estática, Torque e Potência', 'Trabalho, Energia e Potência'),
('Física', 'Física Experimental / Algarismos Significativos', 'Física Experimental'),
('Física', 'Física Geral e Conceitual', 'Física Geral'),
('Física', 'Física Moderna / Dosimetria de Radiação', 'Física Moderna'),
('Física', 'Física Moderna / Efeito Fotoelétrico', 'Física Moderna'),
('Física', 'Física Moderna / Fissão Nuclear', 'Física Moderna'),
('Física', 'Física Moderna / Fótons e Quantização da Energia', 'Física Moderna'),
('Física', 'Física Moderna / Modelos Atômicos', 'Física Moderna'),
('Física', 'Física Moderna / Radiação de Corpo Negro', 'Física Moderna'),
('Física', 'Física Moderna / Raios X e Absorção', 'Física Moderna'),
('Física', 'Física Moderna e Nuclear', 'Física Moderna'),
('Física', 'Física Nuclear', 'Física Moderna'),
('Física', 'Gravitação / Leis de Kepler e Órbitas', 'Gravitação'),
('Física', 'Gravitação Universal (Sistemas Binários)', 'Gravitação'),
('Física', 'Gravitação Universal / Leis de Kepler', 'Gravitação'),
('Física', 'Gravitação universal', 'Gravitação'),
('Física', 'Hidrostática (Empuxo e Densidade)', 'Hidrostática'),
('Física', 'Hidrostática (Pressão Atmosférica)', 'Hidrostática'),
('Física', 'Hidrostática (Princípio de Arquimedes e Empuxo)', 'Hidrostática'),
('Física', 'Hidrostática (Vasos Comunicantes)', 'Hidrostática'),
('Física', 'Hidrostática / Empuxo e Aparente Peso', 'Hidrostática'),
('Física', 'Hidrostática / Pressão e Densidade', 'Hidrostática'),
('Física', 'Hidrostática / Princípio de Pascal', 'Hidrostática'),
('Física', 'Hidrostática e Impulso', 'Hidrostática'),
('Física', 'Hidrostática e Potência Mecânica', 'Hidrostática'),
('Física', 'Hidrostática — Princípio de Arquimedes e Empuxo', 'Hidrostática'),
('Física', 'Lançamento Oblíquo e Energia', 'Cinemática'),
('Física', 'Magnetismo / Força magnética sobre cargas', 'Eletromagnetismo'),
('Física', 'Mecânica (Centro de Massa e Velocidade Angular)', 'Cinemática'),
('Física', 'Mecânica (Cinemática Rotacional)', 'Cinemática'),
('Física', 'Mecânica (Energia Mecânica)', 'Trabalho, Energia e Potência'),
('Física', 'Mecânica (Terceira Lei de Newton)', 'Mecânica'),
('Física', 'Mecânica (Velocidade Média)', 'Cinemática'),
('Física', 'Mecânica - Centrifugação', 'Mecânica'),
('Física', 'Mecânica - Cinemática', 'Cinemática'),
('Física', 'Mecânica - Conservação de Energia', 'Trabalho, Energia e Potência'),
('Física', 'Mecânica - Leis de Newton e Segurança', 'Dinâmica'),
('Física', 'Mecânica / Centro de Massa e Equilíbrio', 'Estática'),
('Física', 'Mecânica / Conservação da Energia Mecânica', 'Trabalho, Energia e Potência'),
('Física', 'Mecânica / Estática de Sistemas e Polias', 'Estática'),
('Física', 'Mecânica / Estática do Ponto Material e Atrito', 'Estática'),
('Física', 'Mecânica / Impulso e Quantidade de Movimento', 'Impulso e Quantidade de Movimento'),
('Física', 'Mecânica / Leis de Newton e Força Normal', 'Dinâmica'),
('Física', 'Mecânica / Movimento Harmônico Simples (MHS)', 'Movimento Harmônico Simples'),
('Física', 'Mecânica / Trabalho e Energia Cinética', 'Trabalho, Energia e Potência'),
('Física', 'Mecânica / Trabalho e Potência mecânica', 'Trabalho, Energia e Potência'),
('Física', 'Mecânica / Vetores e Composição de Velocidades', 'Cinemática'),
('Física', 'Mecânica e Colisões Inelásticas', 'Impulso e Quantidade de Movimento'),
('Física', 'Mecânica e Transmissão de Movimento', 'Mecânica'),
('Física', 'Movimento Harmônico Simples (MHS)', 'Movimento Harmônico Simples'),
('Física', 'Ondas e Acústica / Interferência', 'Ondulatória'),
('Física', 'Ondas e Acústica / Tubos Sonoros', 'Ondulatória'),
('Física', 'Ondulatória (Batimentos e Fenômenos Sonoros)', 'Ondulatória'),
('Física', 'Ondulatória (Efeito Doppler)', 'Ondulatória'),
('Física', 'Ondulatória (Intensidade de Onda)', 'Ondulatória'),
('Física', 'Ondulatória (Interferência de Ondas)', 'Ondulatória'),
('Física', 'Ondulatória (Propriedades das Ondas)', 'Ondulatória'),
('Física', 'Ondulatória (Velocidade de Propagação em Cordas)', 'Ondulatória'),
('Física', 'Ondulatória (Velocidade do Som e Ecos)', 'Ondulatória'),
('Física', 'Ondulatória - Espectro Eletromagnético', 'Ondulatória'),
('Física', 'Ondulatória - Fibras Ópticas e Atenuação', 'Ondulatória'),
('Física', 'Ondulatória - Interferência Sonora', 'Ondulatória'),
('Física', 'Ondulatória / Acústica e Atenuação Sonora', 'Ondulatória'),
('Física', 'Ondulatória / Acústica e Nível Sonoro', 'Ondulatória'),
('Física', 'Ondulatória / Efeito Doppler', 'Ondulatória'),
('Física', 'Ondulatória / Equação Fundamental da Onda', 'Ondulatória'),
('Física', 'Ondulatória / Espectro Eletromagnético e Frequência', 'Ondulatória'),
('Física', 'Ondulatória / Fenômeno de Interferência e Ruído', 'Ondulatória'),
('Física', 'Ondulatória / Fenômenos Ondulatórios', 'Ondulatória'),
('Física', 'Ondulatória / Nível Sonoro em Decibéis', 'Ondulatória'),
('Física', 'Ondulatória / Refração e Equação Fundamental', 'Ondulatória'),
('Física', 'Ondulatória / Refração e dispersão da luz', 'Ondulatória'),
('Física', 'Ondulatória / Ressonância e Frequência', 'Ondulatória'),
('Física', 'Ondulatória e Acústica', 'Ondulatória'),
('Física', 'Ondulatória e Cinemática', 'Ondulatória'),
('Física', 'Ondulatória e Ondas Estacionárias', 'Ondulatória'),
('Física', 'Ondulatória e Óptica', 'Ondulatória'),
('Física', 'Ondulatória e Óptica (Difração)', 'Ondulatória'),
('Física', 'Oscilações (Movimento Harmônico Simples)', 'Movimento Harmônico Simples'),
('Física', 'Oscilações e MHS', 'Movimento Harmônico Simples'),
('Física', 'Propriedades dos Fluidos', 'Hidrostática'),
('Física', 'Termodinâmica (Ciclos e Máquinas Térmicas)', 'Termodinâmica'),
('Física', 'Termodinâmica (Trabalho Gasoso e Força Elástica)', 'Termodinâmica'),
('Física', 'Termodinâmica (Transformação Isovolumétrica)', 'Termodinâmica'),
('Física', 'Termodinâmica / Ciclo de Otto', 'Termodinâmica'),
('Física', 'Termodinâmica / Ciclos e Rendimento', 'Termodinâmica'),
('Física', 'Termodinâmica / Diagrama de Fases', 'Termodinâmica'),
('Física', 'Termodinâmica / Máquinas térmicas e Ciclo de Carnot', 'Termodinâmica'),
('Física', 'Termodinâmica / Propagação de calor e isolamento', 'Termodinâmica'),
('Física', 'Termodinâmica / Transformações Gasosas', 'Termodinâmica'),
('Física', 'Termodinâmica e Espectro de Luz', 'Óptica'),
('Física', 'Termodinâmica e Termologia', 'Termodinâmica'),
('Física', 'Termologia (Calor Latente e Sensível)', 'Termologia e Calorimetria'),
('Física', 'Termologia (Calorimetria e Trocas de Calor)', 'Termologia e Calorimetria'),
('Física', 'Termologia (Calorimetria)', 'Termologia e Calorimetria'),
('Física', 'Termologia (Dilatação Térmica)', 'Termologia e Calorimetria'),
('Física', 'Termologia - Potência Térmica', 'Termologia e Calorimetria'),
('Física', 'Termologia / Calorimetria', 'Termologia e Calorimetria'),
('Física', 'Termologia / Escalas e Grandezas Físicas', 'Termologia e Calorimetria'),
('Física', 'Termologia / Mudanças de Estado', 'Termologia e Calorimetria'),
('Física', 'Termologia / Processos de Transmissão de Calor', 'Termologia e Calorimetria'),
('Física', 'Termologia / Transmissão de Calor', 'Termologia e Calorimetria'),
('Física', 'Termologia / Trocas de Calor e Mudança de Fase', 'Termologia e Calorimetria'),
('Física', 'Termologia e Condução Térmica', 'Termologia e Calorimetria'),
('Física', 'Termologia e Potência / Eficiência Energética', 'Termologia e Calorimetria'),
('Física', 'Termologia — Calorimetria e trocas de calor', 'Termologia e Calorimetria'),
('Física', 'Termometria', 'Termologia e Calorimetria'),
('Física', 'Termometria / Escalas Termométricas', 'Termologia e Calorimetria'),
('Física', 'Termometria / Sensibilidade de Sensores de Temperatura', 'Termologia e Calorimetria'),
('Física', 'Termometria e Escalas Termométricas', 'Termologia e Calorimetria'),
('Física', 'Trabalho e Energia (Centro de Massa)', 'Trabalho, Energia e Potência'),
('Física', 'Transmissão de Movimento Circular', 'Dinâmica'),
('Física', 'Vetores / Composição de Movimentos e Velocidade Relativa', 'Cinemática'),
('Física', 'Óptica Geométrica', 'Óptica'),
('Física', 'Óptica Geométrica (Dispersão da Luz)', 'Óptica'),
('Física', 'Óptica Geométrica / Espelhos Côncavos (Mirascópio)', 'Óptica'),
('Física', 'Óptica Geométrica / Espelhos Esféricos', 'Óptica'),
('Física', 'Óptica Geométrica / Lentes Esféricas', 'Óptica'),
('Física', 'Óptica Geométrica / Lentes delgadas e correção visual', 'Óptica'),
('Física', 'Óptica Geométrica / Visão e Lentes Corretivas', 'Óptica'),
('Física', 'Óptica Geométrica e Física', 'Óptica'),
('Física', 'Óptica Geométrica e Refração', 'Óptica'),
('Física', 'Óptica Geométrica — Refração da luz e profundidade aparente', 'Óptica'),
('Física', 'Óptica e Radiação Infravermelha', 'Óptica'),
('Física', 'Óptica geométrica', 'Óptica'),
('Geografia', 'Agricultura familiar / PAA e mercado institucional', 'Agropecuária e Espaço Rural'),
('Geografia', 'Agronegócio Brasileiro e Capital Agroindustrial', 'Agropecuária e Espaço Rural'),
('Geografia', 'Agrotóxicos e Impactos nos Polinizadores', 'Agrotóxicos'),
('Geografia', 'Biogeografia (Biomas Brasileiros)', 'Biomas e Vegetação'),
('Geografia', 'Biomas Brasileiros (Hotspots / Cerrado)', 'Biomas e Vegetação'),
('Geografia', 'Biomas Brasileiros e Matriz Energética (Rios Voadores e Hidrelétricas)', 'Energia e Recursos'),
('Geografia', 'Biomas e Agroecologia (Sistema Cabruca)', 'Biomas e Vegetação'),
('Geografia', 'Blocos Econômicos (Parceria Transpacífica)', 'Geopolítica'),
('Geografia', 'Blocos econômicos / Mercosul e União Aduaneira', 'Geopolítica'),
('Geografia', 'Cartografia / Cálculo de escala', 'Cartografia'),
('Geografia', 'Cartografia e Anamorfose', 'Cartografia'),
('Geografia', 'Cartografia e Poder', 'Cartografia'),
('Geografia', 'Cartografia e Projeção Continental / Pangeia', 'Cartografia'),
('Geografia', 'Cartografia e Projeções Cartográficas', 'Cartografia'),
('Geografia', 'Cartografia e Relações Espaciais', 'Cartografia'),
('Geografia', 'Cidades Sustentáveis vs. Impactos Ambientais Urbanos', 'Urbanização'),
('Geografia', 'Climatologia (Massas de Ar)', 'Climatologia'),
('Geografia', 'Climatologia / Desmatamento e Chuvas na Amazônia', 'Questões Ambientais'),
('Geografia', 'Climatologia e Ciclones', 'Climatologia'),
('Geografia', 'Climatologia e Circulação Atmosférica (Dispersão de CO2)', 'Climatologia'),
('Geografia', 'Climatologia e Fatores de Aridez / Desertos', 'Climatologia'),
('Geografia', 'Climatologia e Massas de Ar', 'Climatologia'),
('Geografia', 'Climatologia e energia / Radiação solar no Brasil', 'Energia e Recursos'),
('Geografia', 'Cultura sertaneja e leitura do clima / Caatinga', 'Climatologia'),
('Geografia', 'Demografia e Fecundidade', 'População e Demografia'),
('Geografia', 'Demografia urbana / Movimento pendular', 'População e Demografia'),
('Geografia', 'Dinâmica Demográfica e Espaço Rural', 'Agropecuária e Espaço Rural'),
('Geografia', 'Dinâmica Populacional e Demografia', 'População e Demografia'),
('Geografia', 'Direitos territoriais indígenas e cultura', 'Direitos Territoriais Indígenas'),
('Geografia', 'Ecologia Humana e Antropização', 'Ecologia Humana'),
('Geografia', 'Economia global e redes / Desterritorialização da produção', 'Economia Global'),
('Geografia', 'Energia Geotérmica e Matriz Elétrica Brasileira', 'Energia e Recursos'),
('Geografia', 'Espaço Público e Democracia', 'Espaço Público'),
('Geografia', 'Espaço rural / Abastecimento e produção alimentar', 'Agropecuária e Espaço Rural'),
('Geografia', 'Função Social da Propriedade e Combate ao Trabalho Análogo à Escravidão', 'Função Social da Propriedade'),
('Geografia', 'Geografia Agrária e Expropriação Camponesa no Cerrado', 'Biomas e Vegetação'),
('Geografia', 'Geografia Agrária e Novas Ruralidades', 'Geografia Agrária'),
('Geografia', 'Geografia Cultural e Migração Nordestina (Feira de São Cristóvão)', 'População e Demografia'),
('Geografia', 'Geografia Cultural e Representação do Sertão', 'Geografia Cultural'),
('Geografia', 'Geografia Econômica e Mudanças Climáticas (Navegação no Rio Reno)', 'Climatologia'),
('Geografia', 'Geografia Econômica — Mineração e jazidas minerais no Brasil', 'Energia e Recursos'),
('Geografia', 'Geografia Econômica — Modernização agrícola e agronegócio', 'Agropecuária e Espaço Rural'),
('Geografia', 'Geografia Econômica — Neoliberalismo e Plano Real', 'Geografia Econômica'),
('Geografia', 'Geografia Física — Biomas e vegetação do Brasil', 'Biomas e Vegetação'),
('Geografia', 'Geografia Física — Climatologia e massas de ar', 'Climatologia'),
('Geografia', 'Geografia Humana — Demografia e evolução populacional brasileira', 'População e Demografia'),
('Geografia', 'Geografia Militar e Relevo', 'Geomorfologia e Relevo'),
('Geografia', 'Geografia Técnica / Circulação e Fluxos no Espaço', 'Geografia Técnica'),
('Geografia', 'Geografia Urbana', 'Urbanização'),
('Geografia', 'Geografia Urbana e Movimento Pendular', 'Urbanização'),
('Geografia', 'Geografia Urbana e Segregação Socioambiental', 'Urbanização'),
('Geografia', 'Geologia / Tectônica de Placas e Abalos Sísmicos', 'Geomorfologia e Relevo'),
('Geografia', 'Geologia da Amazônia / Escudos cristalinos e minérios', 'Geomorfologia e Relevo'),
('Geografia', 'Geologia e Estruturas da Terra', 'Geomorfologia e Relevo'),
('Geografia', 'Geomorfologia / Tectonismo e vulcanismo', 'Geomorfologia e Relevo'),
('Geografia', 'Geomorfologia e Relevo Brasileiro', 'Geomorfologia e Relevo'),
('Geografia', 'Geomorfologia e Tectônica de Placas (Himalaia)', 'Geomorfologia e Relevo'),
('Geografia', 'Geopolítica / Hegemonia dos EUA e recursos estratégicos', 'Geopolítica'),
('Geografia', 'Geopolítica Europeia (Macedônia do Norte e Balcãs)', 'Geopolítica'),
('Geografia', 'Geopolítica contemporânea / Anexação da Crimeia', 'Geopolítica'),
('Geografia', 'Geopolítica da China e Ocupação Territorial em Xinjiang', 'Geopolítica'),
('Geografia', 'Geopolítica e Blocos Econômicos', 'Geopolítica'),
('Geografia', 'Geopolítica e Crises Humanitárias', 'Geopolítica'),
('Geografia', 'Geopolítica e Mar da China Meridional', 'Geopolítica'),
('Geografia', 'Geopolítica e blocos econômicos', 'Geopolítica'),
('Geografia', 'Gestão Territorial e Reservas Extrativistas', 'Gestão Territorial'),
('Geografia', 'Globalização e Divisão Internacional do Trabalho', 'Globalização e Economia'),
('Geografia', 'Governança Climática e Pressão Empresarial / COP-26', 'Climatologia'),
('Geografia', 'Hidrogeografia e Dessalinização', 'Hidrogeografia'),
('Geografia', 'Hidrografia e Gestão de Recursos Hídricos', 'Hidrografia'),
('Geografia', 'Hidrografia e impactos ambientais urbanos', 'Questões Ambientais'),
('Geografia', 'Hidrografia urbana / Impermeabilização do solo', 'Urbanização'),
('Geografia', 'Hidrologia / Dinâmica de Inundações e Relevo', 'Geomorfologia e Relevo'),
('Geografia', 'Hidrologia Urbana', 'Urbanização'),
('Geografia', 'Hierarquia Urbana e Redes de Cidades', 'Urbanização'),
('Geografia', 'Impactos Ambientais Globais e Antropoceno', 'Questões Ambientais'),
('Geografia', 'Impactos Ambientais da Pesca Industrial', 'Indústria'),
('Geografia', 'Impactos Ambientais e Espaço Vivido', 'Questões Ambientais'),
('Geografia', 'Impactos ambientais no semiárido / Salinização do solo', 'Questões Ambientais'),
('Geografia', 'Imperialismo e Ciência Geográfica', 'Imperialismo'),
('Geografia', 'Inclusão Digital e Valorização da Economia Local', 'Inclusão Digital'),
('Geografia', 'Industrialização do Brasil', 'Indústria'),
('Geografia', 'Logística de Transportes e Agronegócio', 'Agropecuária e Espaço Rural'),
('Geografia', 'Migrações Forçadas e Refugiados', 'População e Demografia'),
('Geografia', 'Migrações Internacionais e Globalização', 'Globalização e Economia'),
('Geografia', 'Migrações Internacionais e Xenofobia', 'População e Demografia'),
('Geografia', 'Organismos Internacionais / Conselho de Segurança da ONU', 'Geopolítica'),
('Geografia', 'Organização Político-Administrativa', 'Organização Político-administrativa'),
('Geografia', 'Pedologia e Clima Tropical', 'Climatologia'),
('Geografia', 'Planejamento Urbano e Mudanças Climáticas', 'Climatologia'),
('Geografia', 'Povos tradicionais / Povo Kambeba e o rio Solimões', 'Hidrografia'),
('Geografia', 'Processo de Urbanização', 'Urbanização'),
('Geografia', 'Processos Cársticos e Intemperismo Químico (Voçorocas / Dolinas / Sinkholes)', 'Processos Cársticos'),
('Geografia', 'Questão Agrária e Desmatamento na Amazônia', 'Questões Ambientais'),
('Geografia', 'Questões Ambientais e Créditos de Carbono', 'Questões Ambientais'),
('Geografia', 'Reestruturação Global da Indústria e Cadeia de Valor', 'Indústria'),
('Geografia', 'Revolução Verde e Uso de Defensivos Agrícolas (Agrotóxicos)', 'Revolução Verde'),
('Geografia', 'Saúde Pública e Conceito de Saúde (ou Questões Ambientais)', 'Saúde Pública'),
('Geografia', 'Segregação socioespacial e urbanização', 'Urbanização'),
('Geografia', 'Sensoriamento Remoto e Albedo', 'Sensoriamento Remoto'),
('Geografia', 'Sensoriamento Remoto e Prevenção no Bioma Cerrado', 'Biomas e Vegetação'),
('Geografia', 'Transformação da Paisagem / Geotecnologias', 'Transformação da Paisagem'),
('Geografia', 'Transição Energética e Mineração de Terras-Raras (Carro Elétrico)', 'Energia e Recursos'),
('Geografia', 'Transportes e Modernização Portuária', 'Transportes'),
('Geografia', 'Urbanização / Êxodo rural e macrocefalia', 'Urbanização'),
('Geografia', 'Urbanização e Dinâmicas Demográficas (''Êxodo Urbano'' Seletivo)', 'Urbanização'),
('Geografia', 'Urbanização e Metropolização', 'Urbanização'),
('Geografia', 'Verticalização e Produção do Espaço Urbano (Salvador-BA)', 'Verticalização'),
('História', 'América Pré-Colombiana / Saberes científicos e culturais', 'América Pré-colombiana'),
('História', 'Anos JK e Desenvolvimento Brasileiro', 'História do Brasil'),
('História', 'Antiguidade Clássica (Expansão Romana)', 'Idade Antiga'),
('História', 'Antiguidade e Idade Média (Oriente Médio e Grécia)', 'Idade Antiga'),
('História', 'Brasil Colonial (Alianças Indígenas)', 'Brasil Colônia'),
('História', 'Brasil Colonial e Expropriação', 'Brasil Colônia'),
('História', 'Brasil Colônia e Catequização (São Benedito)', 'Brasil Colônia'),
('História', 'Brasil Império (Lei Saraiva / Reforma Eleitoral de 1881)', 'Brasil Império'),
('História', 'Brasil Império (Período Regencial)', 'Brasil Império'),
('História', 'Brasil Império (Processo Abolicionista)', 'Brasil Império'),
('História', 'Brasil Império / Organização dos trabalhadores', 'Brasil Império'),
('História', 'Brasil Império e sociedade escravista', 'Brasil Império'),
('História', 'Brasil Republicano e Política', 'Brasil República'),
('História', 'Brasil República (Era Vargas)', 'Brasil República'),
('História', 'Brasil República (Nova República)', 'Brasil República'),
('História', 'Brasil República (República Velha)', 'Brasil República'),
('História', 'Brasil no Comércio Internacional Sec. XX', 'História do Brasil'),
('História', 'Chegada do Cinema no Brasil e Percepções Sociais', 'História do Brasil'),
('História', 'Cidade Medieval e Economia Urbana', 'Idade Média'),
('História', 'Colonização da América e Bartolomeu de Las Casas', 'Colonização da América'),
('História', 'Comunidades Quilombolas e a Constituição de 1988', 'Brasil República'),
('História', 'Conflitos no Oriente Médio e Declaração Balfour', 'Conflitos no Oriente Médio'),
('História', 'Conhecimento e Trabalho nas Escrituras Sagradas', 'Conhecimento'),
('História', 'Cruzadas e Espiritualidade Leiga na Idade Média', 'Idade Média'),
('História', 'Cultura Popular e Dança de Salão na Idade Moderna', 'Idade Moderna'),
('História', 'Círio de Nazaré e Patrimônio Imaterial', 'Círio de Nazaré'),
('História', 'Direitos Civis nos EUA', 'Direitos Civis Nos EUA'),
('História', 'Direitos Reprodutivos e Pílula Anticoncepcional', 'Direitos Reprodutivos'),
('História', 'Ditadura Militar Argentina e Mães da Praça de Maio', 'Brasil República'),
('História', 'Ditadura Militar e o "Milagre Econômico"', 'Brasil República'),
('História', 'Ditadura Militar no Brasil e Repressão', 'Brasil República'),
('História', 'Ditaduras Militares e Operação Condor', 'Brasil República'),
('História', 'Era Vargas / República Populista (Atentado da Rua Tonelero em 1954)', 'Brasil República'),
('História', 'Era Vargas e Justiça do Trabalho', 'Brasil República'),
('História', 'Escravidão e Comércio Urbano no Brasil', 'História do Brasil'),
('História', 'Estado Novo / Censura e Departamento de Imprensa e Propaganda', 'Brasil República'),
('História', 'Estado Novo / Propaganda Oficial do DIP', 'Brasil República'),
('História', 'Estado Novo e Política de Imigração', 'Brasil República'),
('História', 'Etnocentrismo e Ritual Antropofágico (Tupinambás)', 'Etnocentrismo'),
('História', 'Etnocentrismo no Brasil Colônia', 'Brasil Colônia'),
('História', 'Expansão Marítima e Colonização', 'Expansão Marítima'),
('História', 'Expedições Científicas e Imperialismo (Rússia na América do Sul - 1914)', 'Expedições Científicas'),
('História', 'Geografia do Brasil (Classificação Climática do IBGE)', 'História do Brasil'),
('História', 'Geografia do Brasil (Complexos Geoeconômicos)', 'História do Brasil'),
('História', 'Geografia do Brasil (Demografia e Bônus Demográfico)', 'História do Brasil'),
('História', 'Geografia do Brasil (Divisão Regional)', 'História do Brasil'),
('História', 'Geografia do Brasil (Domínios Morfoclimáticos)', 'História do Brasil'),
('História', 'Geografia do Brasil (Estatuto da Cidade)', 'História do Brasil'),
('História', 'Geografia do Brasil (Industrialização)', 'História do Brasil'),
('História', 'Geografia do Brasil (Infraestrutura e Transportes)', 'História do Brasil'),
('História', 'Geografia do Brasil (Matriz Energética)', 'História do Brasil'),
('História', 'Geografia do Brasil (Rede Urbana e Cidades Globais)', 'História do Brasil'),
('História', 'Geografia do Brasil (Relevo - Classificação de Ross)', 'História do Brasil'),
('História', 'Geografia do Brasil (Unidades de Conservação)', 'História do Brasil'),
('História', 'Geografia do Brasil - Demografia', 'História do Brasil'),
('História', 'Geografia do Brasil - Geopolítica e Integração', 'História do Brasil'),
('História', 'Geografia do Brasil - Impactos Ambientais Urbanos', 'História do Brasil'),
('História', 'Geografia do Brasil - Recursos e Matriz Energética', 'História do Brasil'),
('História', 'Guerra Fria e Conflito Koreano', 'Guerra Fria'),
('História', 'Guerra Fria e Patrimônio Histórico (Muro de Berlim)', 'Guerra Fria'),
('História', 'Guerra Fria e Relações Internacionais', 'Guerra Fria'),
('História', 'Historiografia Afro-Brasileira e Antirracismo', 'História do Brasil'),
('História', 'História Contemporânea (Revolução Islâmica)', 'História Contemporânea'),
('História', 'História Medieval / Instituição Universitária', 'Idade Média'),
('História', 'História Moderna e Crise Florestal Europeia', 'História Moderna'),
('História', 'História contemporânea e Direitos Humanos', 'História Contemporânea'),
('História', 'História da Arquitetura e Relações de Gênero (Lina Bo Bardi)', 'História da Arquitetura'),
('História', 'História da educação feminina / Brasil Império', 'Brasil Império'),
('História', 'História da medicina / Escravidão e Iluminismo', 'Idade Moderna'),
('História', 'História da África e redes de comércio', 'História da África'),
('História', 'História das Mentalidades e Costumes (O Uso do Garfo)', 'História das Mentalidades'),
('História', 'História do Brasil (Economia Colonial)', 'Brasil Colônia'),
('História', 'História do Brasil (Era Vargas e Trabalhismo)', 'Brasil República'),
('História', 'História do Brasil (Era Vargas)', 'Brasil República'),
('História', 'História do Brasil (Escravidão Colonial)', 'Brasil Colônia'),
('História', 'História do Brasil (Expansão Territorial e Colonização)', 'História do Brasil'),
('História', 'História do Brasil (Governo FHC e Privatizações)', 'História do Brasil'),
('História', 'História do Brasil (Guerra dos Mascates)', 'História do Brasil'),
('História', 'História do Brasil (Império e Movimentos Sociais)', 'Brasil Império'),
('História', 'História do Brasil (Invasões Francesas)', 'História do Brasil'),
('História', 'História do Brasil (Organização Militar)', 'História do Brasil'),
('História', 'História do Brasil (Período Pré-Colonial)', 'Brasil Colônia'),
('História', 'História do Brasil (Revoltas do Período Regencial)', 'Brasil Império'),
('História', 'História do Brasil (Revolução Pernambucana de 1817)', 'História do Brasil'),
('História', 'História do Brasil - Era Vargas e Segunda Guerra', 'Brasil República'),
('História', 'História do Brasil - Período Colonial', 'Brasil Colônia'),
('História', 'História do Brasil - Primeira República', 'Brasil República'),
('História', 'História do Brasil - Primeiro e Segundo Reinado', 'Brasil Império'),
('História', 'História do Brasil Colônia e Arte Barroca (Chinesices)', 'Brasil Colônia'),
('História', 'História do Brasil Império e Letramento Feminino', 'Brasil Império'),
('História', 'História do Brasil — Era Vargas e o Governo Democrático (1951-54)', 'Brasil República'),
('História', 'História do Brasil — Governo JK e o Desenvolvimentismo', 'História do Brasil'),
('História', 'História do Brasil — Nova República e Governo FHC', 'Brasil República'),
('História', 'História do Brasil — Primeira República / República Velha', 'Brasil República'),
('História', 'História do Brasil — Processo de Independência e Período Joanino', 'Brasil Império'),
('História', 'História do Brasil — Transição do Império para a República', 'Brasil Império'),
('História', 'História do Pensamento Ambiental Brasileiro', 'História do Brasil'),
('História', 'História do trabalho / Instituição do Primeiro de Maio', 'História do Trabalho'),
('História', 'Idade Moderna e Mercantilismo (Veneza e Comércio Mediterrâneo)', 'Idade Moderna'),
('História', 'Idade Média / Papel da realeza e caridade', 'Idade Média'),
('História', 'Idade Média e Ordens Religiosas', 'Idade Média'),
('História', 'Iluminismo / Espaços de Sociabilidade (Salões e Cafés)', 'Idade Moderna'),
('História', 'Iluminismo / Reivindicação dos Direitos da Mulher', 'Idade Moderna'),
('História', 'Iluminismo e Antigo Regime', 'Idade Moderna'),
('História', 'Imprensa e Transferência da Corte Portuguesa ao Brasil (1808)', 'História do Brasil'),
('História', 'Inquisição / Rituais de fé e disciplina social', 'Inquisição'),
('História', 'Instituições Assistenciais no Colonialismo (Roda dos Expostos)', 'Brasil Colônia'),
('História', 'Movimentos Emancipacionistas (1798 x 1789)', 'Movimentos Emancipacionistas'),
('História', 'Movimentos Sociais na Revolução Industrial / Capitão Swing', 'Idade Moderna');

COMMIT;
