BEGIN;

CREATE TABLE IF NOT EXISTS _mapa_taxonomia_temp (
  materia   TEXT NOT NULL,
  antigo    TEXT NOT NULL,
  canonico  TEXT NOT NULL
);

INSERT INTO _mapa_taxonomia_temp (materia, antigo, canonico) VALUES
('Matemática', 'Probabilidade / Lançamento de Dados', 'Probabilidade'),
('Matemática', 'Probabilidade / Permutação', 'Análise Combinatória'),
('Matemática', 'Probabilidade / Porcentagem e Análise de Dados', 'Probabilidade'),
('Matemática', 'Probabilidade / Probabilidade condicional', 'Probabilidade'),
('Matemática', 'Probabilidade / Probabilidade simples', 'Probabilidade'),
('Matemática', 'Probabilidade Binomial', 'Probabilidade'),
('Matemática', 'Probabilidade Sem Reposição', 'Probabilidade'),
('Matemática', 'Probabilidade Total', 'Probabilidade'),
('Matemática', 'Probabilidade de Eventos Independentes', 'Probabilidade'),
('Matemática', 'Probabilidade e Combinatória', 'Análise Combinatória'),
('Matemática', 'Probabilidade e Equação do 1º Grau', 'Probabilidade'),
('Matemática', 'Probabilidade e Geometria Plana', 'Geometria Plana'),
('Matemática', 'Probabilidade e Princípio da Casa dos Pombos', 'Probabilidade'),
('Matemática', 'Probabilidade e Teoria dos Conjuntos', 'Probabilidade'),
('Matemática', 'Probabilidade em Tabuleiro', 'Probabilidade'),
('Matemática', 'Problemas com Frações e Porcentagem', 'Porcentagem'),
('Matemática', 'Progressão Aritmética (P.A.)', 'Progressões'),
('Matemática', 'Progressão Aritmética (PA)', 'Progressões'),
('Matemática', 'Progressão Geométrica', 'Progressões'),
('Matemática', 'Progressão Geométrica (PG)', 'Progressões'),
('Matemática', 'Progressão Geométrica e Logaritmos', 'Progressões'),
('Matemática', 'Progressão Geométrica e Áreas', 'Progressões'),
('Matemática', 'Progressões (Série Geométrica Infinita)', 'Progressões'),
('Matemática', 'Progressões / Geometria', 'Geometria Plana'),
('Matemática', 'Progressões e Torneios', 'Progressões'),
('Matemática', 'Proporcionalidade e Física', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Proporcionalidade e Produtividade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Raciocínio Lógico (Equivalências)', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio Lógico (Números Figurados)', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio Lógico / Propriedades Numéricas', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio Lógico e Calendários', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio Lógico e Jogos de Tabuleiro', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio Lógico-Matemático', 'Raciocínio Lógico'),
('Matemática', 'Raciocínio lógico e capacidade de combustível', 'Raciocínio Lógico'),
('Matemática', 'Radiciação e Operações com Radicais', 'Potenciação e Radiciação'),
('Matemática', 'Radiciação e Potenciação', 'Potenciação e Radiciação'),
('Matemática', 'Radiciação e Radicais Duplos', 'Potenciação e Radiciação'),
('Matemática', 'Razão e Proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção - Engrenagens', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Consumo médio de combustível', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Densidade Demográfica', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Divisão Proporcional', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Divisão proporcional', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Eficiência', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Escala de Área', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Escala e conversão de unidades', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Escalas', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Escalas Volumétricas', 'Geometria Espacial'),
('Matemática', 'Razão e Proporção / Frações', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Manipulação Algébrica', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Regra de três composta', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão e Proporção / Volumes', 'Geometria Espacial'),
('Matemática', 'Razão e proporção', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, Proporção e Escala', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, Proporção e Misturas', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, Proporção e Movimento', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, Proporção e Porcentagem', 'Porcentagem'),
('Matemática', 'Razão, Proporção e Vazão', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, proporção e ordenação', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Razão, área e taxa de crescimento', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Regra de Três Composta', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Regra de Três e Lógica Operacional', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Relações Métricas e Aproximações', 'Geometria Plana'),
('Matemática', 'Saúde e Fisiologia (Matemática aplicada)', 'Saúde'),
('Matemática', 'Sequências / Progressões', 'Progressões'),
('Matemática', 'Sequências e Progressões', 'Progressões'),
('Matemática', 'Sequências e Progressões (PA)', 'Progressões'),
('Matemática', 'Sequências e Progressões / Progressão Aritmética (PA)', 'Progressões'),
('Matemática', 'Sequências numéricas (PA e PG)', 'Progressões'),
('Matemática', 'Sistema de numeração decimal e valor posicional', 'Teoria dos Números'),
('Matemática', 'Sistemas Lineares', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Sistemas Lineares e Racionalização', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Sistemas de Equações / Problemas do 1º grau', 'Equações e Inequações'),
('Matemática', 'Sistemas de Equações Lineares', 'Equações e Inequações'),
('Matemática', 'Sistemas de Equações Lineares e Área', 'Equações e Inequações'),
('Matemática', 'Sistemas de Equações do 1º Grau', 'Equações e Inequações'),
('Matemática', 'Sistemas de Numeração', 'Teoria dos Números'),
('Matemática', 'Sistemas de Numeração / Base binária e decimal', 'Teoria dos Números'),
('Matemática', 'Sistemas de Numeração e Base Binária', 'Teoria dos Números'),
('Matemática', 'Sistemas de Numeração e Lógica', 'Teoria dos Números'),
('Matemática', 'Sistemas de inequações', 'Equações e Inequações'),
('Matemática', 'Tabelas e Operações Matriciais', 'Análise de Gráficos e Tabelas'),
('Matemática', 'Teorema de Stewart e Lei dos Cossenos', 'Trigonometria'),
('Matemática', 'Teorema de Tales e Semelhança', 'Geometria Plana'),
('Matemática', 'Teoria dos Conjuntos', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Conjuntos (Diagrama de Venn)', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Conjuntos e Contagem', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Conjuntos e Diagrama de Venn', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Conjuntos e Diagramas de Venn', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Conjuntos e Probabilidade', 'Probabilidade'),
('Matemática', 'Teoria dos Conjuntos — Diagrama de Venn', 'Conjuntos Numéricos'),
('Matemática', 'Teoria dos Números (Equações Diofantinas)', 'Equações e Inequações'),
('Matemática', 'Teoria dos Números (MDC e MMC)', 'Teoria dos Números'),
('Matemática', 'Teoria dos Números e Divisibilidade', 'Teoria dos Números'),
('Matemática', 'Teoria dos Números e Paridade', 'Teoria dos Números'),
('Matemática', 'Teoria dos Números e Propriedades', 'Teoria dos Números'),
('Matemática', 'Teoria dos Números — Divisibilidade', 'Teoria dos Números'),
('Matemática', 'Teoria dos Números: Divisibilidade, MDC e MMC', 'Teoria dos Números'),
('Matemática', 'Trigonometria (Arco Duplo e Tangente)', 'Trigonometria'),
('Matemática', 'Trigonometria (Triângulo Retângulo)', 'Geometria Plana'),
('Matemática', 'Trigonometria / Equações Trigonométricas', 'Trigonometria'),
('Matemática', 'Trigonometria / Função Tangente e Transformações', 'Trigonometria'),
('Matemática', 'Trigonometria / Funções Trigonométricas', 'Trigonometria'),
('Matemática', 'Trigonometria / Identidades Trigonométricas', 'Trigonometria'),
('Matemática', 'Trigonometria / Inequações Trigonométricas', 'Trigonometria'),
('Matemática', 'Trigonometria / Lei dos Cossenos', 'Trigonometria'),
('Matemática', 'Trigonometria / Lei dos Cossenos e Vetores', 'Trigonometria'),
('Matemática', 'Trigonometria / Triângulo Retângulo', 'Geometria Plana'),
('Matemática', 'Trigonometria / Triângulo retângulo e razões', 'Geometria Plana'),
('Matemática', 'Trigonometria e Orientação Espacial', 'Trigonometria'),
('Matemática', 'Trigonometria e Polígonos', 'Geometria Plana'),
('Matemática', 'Trigonometria no Triângulo Qualquer', 'Geometria Plana'),
('Matemática', 'Trigonometria no Triângulo Retângulo', 'Geometria Plana'),
('Matemática', 'Unidades de Medida', 'Grandezas e Medidas'),
('Matemática', 'Unidades de Medida e Densidade', 'Grandezas e Medidas'),
('Matemática', 'Unidades de Medida e Proporção', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Valor Numérico e Composição de Funções', 'Funções'),
('Matemática', 'Álgebra (Equações Radicais)', 'Equações e Inequações'),
('Matemática', 'Álgebra (Equações e Fatoração)', 'Equações e Inequações'),
('Matemática', 'Álgebra (Identidade de Polinômios)', 'Polinômios'),
('Matemática', 'Álgebra (Inequações Fracionárias)', 'Equações e Inequações'),
('Matemática', 'Álgebra / Desigualdades e Simplificação', 'Álgebra'),
('Matemática', 'Álgebra / Equação do 1º Grau e Perdas Fixas', 'Equações e Inequações'),
('Matemática', 'Álgebra / Equação do 2º Grau', 'Equações e Inequações'),
('Matemática', 'Álgebra / Equações Fracionárias e Raízes', 'Equações e Inequações'),
('Matemática', 'Álgebra / Equações do 1º Grau e Redução de Custos', 'Equações e Inequações'),
('Matemática', 'Álgebra / Função Afim', 'Função Afim'),
('Matemática', 'Álgebra / Logaritmos e Equações Logarítmicas', 'Logaritmos e Exponenciais'),
('Matemática', 'Álgebra / Polinômios e Divisibilidade', 'Polinômios'),
('Matemática', 'Álgebra / Proporcionalidade Direta', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Álgebra / Sequências e Expressões Algébricas', 'Sequências e Recorrências'),
('Matemática', 'Álgebra Linear (Matrizes e Determinantes)', 'Matrizes, Determinantes e Sistemas'),
('Matemática', 'Álgebra e Binômio de Newton', 'Análise Combinatória'),
('Matemática', 'Álgebra e Equações', 'Equações e Inequações'),
('Matemática', 'Álgebra e Funções', 'Funções'),
('Matemática', 'Álgebra e Modelagem', 'Álgebra'),
('Matemática', 'Álgebra e Polinômios', 'Polinômios'),
('Matemática', 'Álgebra e Proporcionalidade', 'Razão, Proporção e Regra de Três'),
('Matemática', 'Álgebra e Sequências', 'Sequências e Recorrências'),
('Matemática', 'Álgebra e Sequências (Série Telescópica)', 'Sequências e Recorrências'),
('Matemática', 'Álgebra e Sistemas de Equações', 'Equações e Inequações'),
('Matemática', 'Álgebra — Fatoração e Expressões Algébricas', 'Álgebra'),
('Matemática', 'Álgebra — Fatoração e Simplificação', 'Álgebra'),
('Matemática', 'Álgebra: Equação do 2º Grau', 'Equações e Inequações'),
('Matemática', 'Áreas de Figuras Planas e Circulares', 'Geometria Plana'),
('Matemática', 'Áreas de Figuras Planas e Custo', 'Geometria Plana'),
('Matemática', 'Áreas de Polígonos e Razão entre Áreas', 'Geometria Plana'),
('Matemática', 'Áreas de Triângulos e Equação do 2º Grau', 'Geometria Plana'),
('Português', 'Acentuação gráfica', 'Acentuação Gráfica'),
('Português', 'Adequação vocabular e efeito de humor', 'Adequação Vocabular'),
('Português', 'Adjetivo / Flexão de Grau', 'Morfologia'),
('Português', 'Adjunto Adverbial e Circunstâncias', 'Adjunto Adverbial'),
('Português', 'Alegoria Política nos Anos 1970 (J. J. Veiga)', 'Alegoria Política Nos Anos 1970'),
('Português', 'Antonímia e Semântica', 'Semântica'),
('Português', 'Análise Comparativa de Textos e Estatuto do Idoso', 'Interpretação de Texto'),
('Português', 'Análise Crítica da Linguagem e Relações de Poder', 'Análise Crítica da Linguagem'),
('Português', 'Análise Discursiva e Estilística', 'Figuras de Linguagem'),
('Português', 'Análise Intertextual', 'Gêneros e Tipologia Textual'),
('Português', 'Análise Linguística e Gramática', 'Análise Linguística'),
('Português', 'Análise Sintática e Funções dos Termos', 'Sintaxe'),
('Português', 'Análise Sintática e Relações de Sentido', 'Sintaxe'),
('Português', 'Análise Textual - Coesão Referencial e Pronomes', 'Coesão e Coerência'),
('Português', 'Análise Textual e Subjetividade', 'Análise Textual'),
('Português', 'Análise de Discurso Digital e Perfis Automatizados', 'Análise de Discurso Digital'),
('Português', 'Análise de Discurso e Ponto de Vista', 'Análise de Discurso'),
('Português', 'Análise de Linguagem Mista e Chargística', 'Análise de Linguagem Mista'),
('Português', 'Análise de Linguagem Verbal e Não Verbal', 'Análise de Linguagem Verbal'),
('Português', 'Análise de Poesia e Modernismo', 'Literatura'),
('Português', 'Análise de Texto Publicitário e Função Social', 'Interpretação de Texto'),
('Português', 'Análise de Tiras e Linguagem Conotativa', 'Análise de Tiras'),
('Português', 'Análise de discurso publicitário', 'Análise de Discurso Publicitário'),
('Português', 'Análise de texto opinativo / Marcas de informalidade e metáfora', 'Figuras de Linguagem'),
('Português', 'Análise de textos mistos e infográficos', 'Interpretação de Texto'),
('Português', 'Análise discursiva / Inovação tecnológica e aprendizagem', 'Análise Discursiva'),
('Português', 'Análise do discurso e estratégias persuasivas', 'Análise do Discurso e Argumentação'),
('Português', 'Análise sintática dos termos da oração', 'Sintaxe'),
('Português', 'Argumentação e Campanhas de Conscientização no Trânsito', 'Análise do Discurso e Argumentação'),
('Português', 'Arte memorial e crise de refugiados', 'Arte Memorial'),
('Português', 'Ativismo Digital e Redes Sociais', 'Ativismo Digital'),
('Português', 'Campanhas de conscientização e proteção animal', 'Campanhas de Conscientização'),
('Português', 'Ciclo hidrológico e reservatórios de água doce', 'Ciclo Hidrológico'),
('Português', 'Circulação de Informações e História das Mídias', 'Circulação de Informações'),
('Português', 'Classes de Palavras e Pronomes', 'Morfologia'),
('Português', 'Classes de palavras (Morfologia)', 'Morfologia'),
('Português', 'Classificação de Orações Subordinadas', 'Sintaxe'),
('Português', 'Coesão Textual / Reiteração Lexical', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Anáfora', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Conjunções', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Elementos Anafóricos', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Intenção Comunicativa', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Sequenciação Narrativa', 'Coesão e Coerência'),
('Português', 'Coesão Textual e Verbo Vicário', 'Coesão e Coerência'),
('Português', 'Coesão e Elementos de Conexão', 'Coesão e Coerência'),
('Português', 'Coesão e Progressão Textual (Adriana Lisboa)', 'Coesão e Coerência'),
('Português', 'Coesão e coerência textual (relação condicional)', 'Coesão e Coerência'),
('Português', 'Coesão e ritmo narrativo / Estrutura do desabafo', 'Coesão e Coerência'),
('Português', 'Coesão textual e progressão temática', 'Coesão e Coerência'),
('Português', 'Coesão textual e retomada de informações', 'Coesão e Coerência'),
('Português', 'Coesão, Coerência e Linguagem Coloquial', 'Coesão e Coerência'),
('Português', 'Colocação Pronomial', 'Colocação Pronominal'),
('Português', 'Colocação pronominal', 'Colocação Pronominal'),
('Português', 'Comparação textual / Temática sobre animais de rua', 'Comparação Textual'),
('Português', 'Compreensão Textual e Tecnologias da Escrita', 'Interpretação de Texto'),
('Português', 'Compreensão e Interpretação de Texto', 'Interpretação de Texto'),
('Português', 'Compreensão e Interpretação de Texto em Prosa', 'Interpretação de Texto'),
('Português', 'Compreensão e interpretação de texto', 'Interpretação de Texto'),
('Português', 'Compreensão textual e impacto das mídias digitais', 'Interpretação de Texto'),
('Português', 'Comunicação Digital e Reação do Leitor', 'Comunicação Digital'),
('Português', 'Comunicação Publicitária Social e Violência Doméstica', 'Comunicação Publicitária Social'),
('Português', 'Concordância Nominal', 'Concordância'),
('Português', 'Concordância Verbal', 'Concordância'),
('Português', 'Concordância Verbal e Nominal', 'Concordância'),
('Português', 'Concordância e Flexão Nominais', 'Concordância'),
('Português', 'Concordância verbal', 'Concordância'),
('Português', 'Condição feminina no século XIX', 'Condição Feminina no Século XIX'),
('Português', 'Conjunções e Coesão Textual', 'Coesão e Coerência'),
('Português', 'Crase e Ortografia', 'Crase'),
('Português', 'Crônica e Narrativa Absurda', 'Crônica'),
('Português', 'Cultura e Tradição Indígena (Verbete Urucum / Povo Wajãpi)', 'Cultura'),
('Português', 'Dança contemporânea e mídias digitais', 'Dança Contemporânea'),
('Português', 'Democratização do esporte e inovações técnicas', 'Democratização do Esporte'),
('Português', 'Denotação e Conotação', 'Semântica'),
('Português', 'Dialeto Social e Patrimônio Linguístico', 'Dialeto Social'),
('Português', 'Direitos Humanos e Interpretação', 'Interpretação de Texto'),
('Português', 'Discurso Digital e Intolerância', 'Discurso Digital'),
('Português', 'Discurso Direto e Indireto', 'Discurso Direto'),
('Português', 'Discurso intimidador e relações de poder', 'Discurso Intimidador'),
('Português', 'Divisão de informações sem imprensa e credulidade', 'Divisão de Informações Sem Imprensa'),
('Português', 'Divulgação Científica e Titulação', 'Divulgação Científica'),
('Português', 'Documentários e originalidade cultural', 'Documentários'),
('Português', 'Emprego da crase', 'Crase'),
('Português', 'Emprego da vírgula e pontuação', 'Pontuação'),
('Português', 'Emprego de palavras e grafia', 'Ortografia'),
('Português', 'Emprego do Acento Indicativo de Crase', 'Crase'),
('Português', 'Estilística - Tipos de Discurso (Discurso Indireto Livre)', 'Figuras de Linguagem'),
('Português', 'Estilística / Recursos Figurados (Conotação)', 'Figuras de Linguagem'),
('Português', 'Estilística e Figuras de Linguagem', 'Figuras de Linguagem'),
('Português', 'Estilística e Funções da Linguagem', 'Figuras de Linguagem'),
('Português', 'Estilística — Conotação e Denotação', 'Figuras de Linguagem'),
('Português', 'Estilística — Figuras de Linguagem', 'Figuras de Linguagem'),
('Português', 'Estilística, Ironia e Bordões Linguísticos', 'Figuras de Linguagem'),
('Português', 'Estratégia de Progressão Textual e Interlocução', 'Coesão e Coerência'),
('Português', 'Estratégias Argumentativas e Persuasão em Textos Informativos', 'Análise do Discurso e Argumentação'),
('Português', 'Estrutura de prefácio em quadrinhos', 'Estrutura de Prefácio em Quadrinhos'),
('Português', 'Estrutura e Formação de Palavras', 'Morfologia'),
('Português', 'Estética brasiliense e mobiliário modernista', 'Estética Brasiliense'),
('Português', 'Exposição Parental e Privacidade', 'Exposição Parental'),
('Português', 'Ficção Urbana dos Anos 1950 (Lúcio Cardoso)', 'Ficção Urbana dos Anos 1950'),
('Português', 'Figuras de Linguagem - Hipérbole', 'Figuras de Linguagem'),
('Português', 'Figuras de Linguagem e Poética', 'Figuras de Linguagem'),
('Português', 'Figuras de linguagem', 'Figuras de Linguagem'),
('Português', 'Flexão e Classificação dos Substantivos', 'Morfologia'),
('Português', 'Fonologia e Contagem de Fonemas', 'Fonologia'),
('Português', 'Fonética e Fonologia / Acentuação e Tonicidade', 'Acentuação Gráfica'),
('Português', 'Formação de Palavras e Semântica', 'Morfologia'),
('Português', 'Função emotiva e subjetividade na crônica', 'Função Emotiva'),
('Português', 'Funções da Linguagem (Função Poética em Capa de Revista)', 'Funções da Linguagem'),
('Português', 'Funções da Linguagem / Função Referencial', 'Funções da Linguagem'),
('Português', 'Funções da Linguagem na Poesia Slam', 'Funções da Linguagem'),
('Português', 'Funções da linguagem', 'Funções da Linguagem'),
('Português', 'Funções da linguagem (metalinguagem)', 'Funções da Linguagem'),
('Português', 'Funções da linguagem / Interação textual', 'Funções da Linguagem'),
('Português', 'Funções sintáticas do pronome oblíquo', 'Morfologia'),
('Português', 'Gramática - Conjunções Aditivas e Correlações', 'Morfologia'),
('Português', 'Gramática - Conjunções Coordenativas Conclusivas', 'Morfologia'),
('Português', 'Gramática - Valor Semântico das Conjunções (Como Causal)', 'Morfologia'),
('Português', 'Gramática / Referência Pronomial', 'Gramática'),
('Português', 'Gramática Normativa e Regência', 'Regência'),
('Português', 'Gênero Reportagem / Saúde Pública', 'Gênero Reportagem'),
('Português', 'Gênero Resenha Crítica / Conectivos Adversativos', 'Coesão e Coerência'),
('Português', 'Gênero Textual Carta Aberta e Direitos Sociais', 'Gêneros e Tipologia Textual'),
('Português', 'Gênero notícia / Conscientização sobre saúde pública', 'Gênero Notícia'),
('Português', 'Gênero piada e análise linguística/social', 'Gênero Piada'),
('Português', 'Gênero rede social / Transparência pública', 'Gênero Rede Social'),
('Português', 'Gênero resenha / Análise crítica de documentário', 'Gênero Resenha'),
('Português', 'Gêneros Literários (Lírico e Formas Fixas)', 'Gêneros Literários'),
('Português', 'Gêneros Textuais (Bilhete e Crônica)', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros Textuais (Resenha)', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros Textuais e Discursivos', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros Textuais e Estratégias de Conscientização', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros Textuais e Sequência Injuntiva', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros Textuais e Suporte (Conto vs. Crônica)', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros de conscientização pública', 'Gêneros de Conscientização Pública'),
('Português', 'Gêneros digitais e segurança da informação', 'Gêneros Digitais'),
('Português', 'Gêneros e Discurso Social', 'Gêneros'),
('Português', 'Gêneros e Tipos Textuais', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros textuais (diário)', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros textuais (resenha crítica)', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros textuais (resenha/apresentação) e intenção comunicativa', 'Gêneros e Tipologia Textual'),
('Português', 'Gêneros textuais e cibercultura', 'Gêneros e Tipologia Textual'),
('Português', 'Hibridismo cultural e manifestações artísticas', 'Hibridismo Cultural'),
('Português', 'Hibridismo de gêneros textuais (poema-receita)', 'Gêneros e Tipologia Textual'),
('Português', 'História dos Meios de Comunicação (Rádio e Podcast)', 'História dos Meios de Comunicação'),
('Português', 'História e violência contra povos escravizados', 'História'),
('Português', 'Identidade Cultural e Patrimônio Linguístico', 'Identidade Cultural'),
('Português', 'Imersão lírica e saúde mental', 'Imersão Lírica'),
('Português', 'Imprensa histórica e preservação da memória', 'Imprensa Histórica'),
('Português', 'Infografia e impactos do uso de celulares', 'Infografia'),
('Português', 'Inteligência Artificial e Produção Literária', 'Inteligência Artificial'),
('Português', 'Interpretação comparativa de textos', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto (Análise de Canção)', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto (Humor e Ironia)', 'Figuras de Linguagem'),
('Português', 'Interpretação de Texto (Pressuposição)', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto - Compreensão Global e Ironia', 'Figuras de Linguagem'),
('Português', 'Interpretação de Texto / Intertexto', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto / Tecnologia e Saúde', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto Poético e Cultura', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto e Análise do Discurso', 'Análise do Discurso e Argumentação'),
('Português', 'Interpretação de Texto e Compreensão Leitora', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto e Esporte', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto e Estilística', 'Figuras de Linguagem'),
('Português', 'Interpretação de Texto e Foco Narrativo', 'Interpretação de Texto'),
('Português', 'Interpretação de Texto e Literatura', 'Literatura'),
('Português', 'Interpretação de texto', 'Interpretação de Texto'),
('Português', 'Interpretação de texto não verbal e publicitário', 'Interpretação de Texto'),
('Português', 'Interpretação de textos visuais (quadrinhos)', 'Interpretação de Texto'),
('Português', 'Interpretação e Análise Poética', 'Interpretação de Texto'),
('Português', 'Interpretação e Análise Textual', 'Interpretação de Texto'),
('Português', 'Interpretação e Compreensão Textual', 'Interpretação de Texto'),
('Português', 'Interpretação e Compreensão de Texto', 'Interpretação de Texto'),
('Português', 'Interpretação e Evolução Tecnológica da Escrita', 'Interpretação de Texto'),
('Português', 'Intertextualidade', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Análise Comparativa', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Análise Comparativa de Textos', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Diálogo entre Textos', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Movimentos Literários', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Representação de Gênero', 'Gêneros e Tipologia Textual'),
('Português', 'Intertextualidade e Tecnologia na Canção Brasileira', 'Gêneros e Tipologia Textual'),
('Português', 'Ironia e conformismo social', 'Figuras de Linguagem'),
('Português', 'Ironia e igualdade nas relações sociais', 'Figuras de Linguagem'),
('Português', 'Leitura crítica de mídias / Jogos e representatividade feminina', 'Interpretação de Texto'),
('Português', 'Leitura de Infográfico e Exposição nas Redes Sociais', 'Interpretação de Texto'),
('Português', 'Leitura e Interpretação de Linguagem Mista', 'Interpretação de Texto'),
('Português', 'Letramento Midiático e Leitura Crítica de Memes', 'Interpretação de Texto'),
('Português', 'Linguagem Coloquial e Expressões Idiomáticas', 'Semântica'),
('Português', 'Linguagem Publicitária / Campanhas Sociais', 'Linguagem Publicitária'),
('Português', 'Linguagem e tecnologia / Direitos autorais e ambiente virtual', 'Linguagem'),
('Português', 'Linguagem verbal e não verbal / Desconstrução de estereótipos', 'Linguagem Verbal'),
('Português', 'Linguística - Marcas da Oralidade e Conectivos Repetitivos (''daí'')', 'Coesão e Coerência'),
('Português', 'Lirismo Contemporâneo e Relações Amorosas', 'Lirismo Contemporâneo'),
('Português', 'Lirismo e angústia da distância amorosa', 'Lirismo'),
('Português', 'Literatura (Simbolismo - Características)', 'Literatura'),
('Português', 'Literatura (Simbolismo - Obras)', 'Literatura'),
('Português', 'Literatura Afro-Brasileira e Tradição Oral (Conceição Evaristo)', 'Literatura'),
('Português', 'Literatura Brasileira (Arcadismo / Epopeia)', 'Literatura'),
('Português', 'Literatura Brasileira (Realismo / Machado de Assis)', 'Literatura'),
('Português', 'Literatura Contemporânea Feminina (Identidade e Etnia)', 'Literatura'),
('Português', 'Literatura Contemporânea e Metáfora da Lavoura (Itamar Vieira Jr)', 'Figuras de Linguagem'),
('Português', 'Literatura Portuguesa', 'Literatura'),
('Português', 'Marcas informais e variações na letra de samba', 'Marcas Informais'),
('Português', 'Mecanismos de humor e ironia', 'Figuras de Linguagem'),
('Português', 'Modernismo - Primeira Geração (Mário de Andrade)', 'Literatura'),
('Português', 'Modernismo - Terceira Geração (Guimarães Rosa)', 'Literatura'),
('Português', 'Morfologia (Classes de Palavras / Pronome Reflexivo)', 'Morfologia'),
('Português', 'Morfologia (Classes de Palavras)', 'Morfologia'),
('Português', 'Morfologia (Plural dos Substantivos)', 'Morfologia'),
('Português', 'Morfologia (Processos de Formação de Palavras)', 'Morfologia'),
('Português', 'Morfologia (Tempos Verbais Compostos)', 'Morfologia'),
('Português', 'Morfologia - Adjetivo e locução adjetiva', 'Morfologia'),
('Português', 'Morfologia - Classes de Palavras e Morfofonética', 'Morfologia'),
('Português', 'Morfologia - Classes de palavras', 'Morfologia'),
('Português', 'Morfologia - Classes de palavras (Advérbio)', 'Morfologia'),
('Português', 'Morfologia - Conjugação verbal', 'Morfologia'),
('Português', 'Morfologia - Emprego dos verbos', 'Morfologia'),
('Português', 'Morfologia - Processos de formação de palavras', 'Morfologia'),
('Português', 'Morfologia - Substantivos', 'Morfologia'),
('Português', 'Morfologia / Advérbios e Locuções Adverbiais', 'Morfologia'),
('Português', 'Morfologia / Colocação e Emprego dos Pronominais', 'Morfologia'),
('Português', 'Morfologia / Conjunções Subordinativas', 'Morfologia'),
('Português', 'Morfologia / Processos de Formação de Palavras', 'Morfologia'),
('Português', 'Morfologia / Substantivos (Classificação de Gênero)', 'Morfologia'),
('Português', 'Morfologia / Verbos e Vozes Verbais', 'Morfologia'),
('Português', 'Morfologia e Advérbios', 'Morfologia'),
('Português', 'Morfologia e Classes de Palavras', 'Morfologia'),
('Português', 'Morfologia — Classes de Palavras', 'Morfologia'),
('Português', 'Morfologia — Conjugação e flexão verbal', 'Morfologia'),
('Português', 'Morfologia — Tempos e Modos Verbais', 'Morfologia'),
('Português', 'Morfossintaxe (Verbos Impessoais)', 'Verbos'),
('Português', 'Morfossintaxe e Classes de Palavras', 'Morfologia'),
('Português', 'Morfossintaxe e Conjunções', 'Morfologia'),
('Português', 'Morfossintaxe e Semântica', 'Semântica'),
('Português', 'Morfossintaxe e emprego dos tempos verbais', 'Verbos'),
('Português', 'Morfossintaxe — Análise morfossintática e classes gramaticais', 'Morfossintaxe'),
('Português', 'Morfossintaxe — Invariabilidade das palavras e flexão', 'Morfossintaxe'),
('Português', 'Morfossintaxe — Pronome Oblíquo com Valor Possessivo', 'Morfologia'),
('Português', 'Multilinguismo e Espaço Urbano', 'Multilinguismo'),
('Português', 'Multimodalidade e Linguagem Visual em Cartazes', 'Multimodalidade'),
('Português', 'Mídias Digitais e Comunicação / Podcast', 'Mídias Digitais'),
('Português', 'Norma Padrão e Variação Linguística', 'Variação Linguística'),
('Português', 'Norma-padrão e adequação linguística / Colocação pronominal', 'Colocação Pronominal'),
('Português', 'Notícias e formulações hipotéticas', 'Notícias'),
('Português', 'Níveis de Linguagem e Ironia (''Juridiquês'')', 'Figuras de Linguagem'),
('Português', 'Níveis de Linguagem e Registro', 'Níveis de Linguagem'),
('Português', 'Oralidade vs. Escrita e variação culta', 'Oralidade Vs. Escrita'),
('Português', 'Oratória Acadêmica e Discurso de Homenagem (Rui Barbosa)', 'Oratória Acadêmica'),
('Português', 'Orações Coordenadas', 'Sintaxe'),
('Português', 'Orações Reduzidas', 'Sintaxe'),
('Português', 'Orações Subordinadas Adverbiais', 'Sintaxe'),
('Português', 'Orações subordinadas substantivas', 'Sintaxe'),
('Português', 'Orientação pediátrica / Uso de telas na infância', 'Orientação Pediátrica'),
('Português', 'Ortografia - Acentuação gráfica', 'Acentuação Gráfica'),
('Português', 'Ortografia e Acentuação Gráfica / Morfologia', 'Acentuação Gráfica'),
('Português', 'Ortografia e Crase', 'Crase'),
('Português', 'Ortografia e Emprego do Hífen', 'Ortografia'),
('Português', 'Ortografia e Flexão Verbal', 'Ortografia'),
('Português', 'Ortografia e História da Língua Portuguesa', 'Variação Linguística'),
('Português', 'Ortografia e Semântica — Emprego de palavras e conectivos', 'Coesão e Coerência'),
('Português', 'Ortografia e homônimos/parônimos', 'Ortografia'),
('Português', 'Ortografia — Acentuação gráfica', 'Acentuação Gráfica'),
('Português', 'Patrimônio Linguístico e Cultura Afro-Brasileira (''Língua de Santo'')', 'Patrimônio Linguístico'),
('Português', 'Patrimônio linguístico e ditados populares', 'Patrimônio Linguístico'),
('Português', 'Período Composto e Coordenação', 'Sintaxe'),
('Português', 'Período composto (coordenação e subordinação)', 'Sintaxe'),
('Português', 'Plural dos Substantivos Compostos', 'Morfologia'),
('Português', 'Poesia Contemporânea', 'Literatura'),
('Português', 'Poesia de João Cabral de Melo Neto', 'Literatura'),
('Português', 'Polissemia e Metáfora (Roseana Murray)', 'Figuras de Linguagem'),
('Português', 'Pontuação - Emprego da Vírgula', 'Pontuação'),
('Português', 'Pontuação / Emprego da Vírgula', 'Pontuação'),
('Português', 'Pontuação e Elipse Verbal', 'Pontuação'),
('Português', 'Pontuação e Emprego da Vírgula', 'Pontuação'),
('Português', 'Pontuação e Regras Gramaticais', 'Pontuação'),
('Português', 'Pontuação e coesão textual', 'Coesão e Coerência'),
('Português', 'Pontuação e subentendido na minificção', 'Pontuação'),
('Português', 'Pontuação — Emprego da vírgula', 'Pontuação'),
('Português', 'Pop Art e erotização do corpo feminino', 'Pop Art'),
('Português', 'Postura crítica frente à informação midiática', 'Postura Crítica Frente À Informação Midiática'),
('Português', 'Preconceito Linguístico e Variedade Lusitana', 'Variação Linguística'),
('Português', 'Preconceito linguístico / Léxico e discriminação racial', 'Variação Linguística'),
('Português', 'Preservação do Patrimônio Linguístico e Cultural', 'Preservação do Patrimônio Linguístico'),
('Português', 'Pressupostos e Recursos Argumentativos (Pressão Estética Corporal)', 'Análise do Discurso e Argumentação'),
('Português', 'Projeto Poético e Emprego de Formas Verbais/Pronominais', 'Projeto Poético'),
('Português', 'Pronomes', 'Morfologia'),
('Português', 'Pronomes Relativos', 'Morfologia'),
('Português', 'Pronomes e conjunções', 'Morfologia'),
('Português', 'Prosa Narrativa e Memória Histórica (João Alphonsus)', 'Prosa Narrativa'),
('Português', 'Prosa de Ficção Contemporânea e Alegoria', 'Prosa de Ficção Contemporânea'),
('Português', 'Pré-Modernismo e Crítica à Escravidão (Olavo Bilac)', 'Literatura'),
('Português', 'Publicidade e Linguagem Não Verbal', 'Publicidade'),
('Português', 'Purismo linguístico e norma-padrão', 'Purismo Linguístico'),
('Português', 'Racismo e mitos de democracia racial', 'Racismo'),
('Português', 'Recursos Argumentativos', 'Análise do Discurso e Argumentação'),
('Português', 'Recursos Argumentativos na Denúncia do Racismo', 'Análise do Discurso e Argumentação'),
('Português', 'Recursos Coesivos e Sintaxe (Síntese Argumentativa)', 'Sintaxe'),
('Português', 'Recursos Estilísticos e Figuras de Linguagem', 'Figuras de Linguagem'),
('Português', 'Recursos Estilísticos e Metáforas', 'Figuras de Linguagem'),
('Português', 'Recursos Gráficos e Identidade Editorial', 'Recursos Gráficos'),
('Português', 'Recursos Linguísticos / Argumentação', 'Análise do Discurso e Argumentação'),
('Português', 'Recursos Linguísticos e Injunção', 'Recursos Linguísticos'),
('Português', 'Recursos Persuasivos / Intertextualidade Musical', 'Gêneros e Tipologia Textual'),
('Português', 'Recursos de Empatia e Aproximação com o Leitor', 'Recursos de Empatia'),
('Português', 'Recursos estilísticos (repetição e anáfora em crônica)', 'Figuras de Linguagem'),
('Português', 'Redes Sociais e Suporte Literário', 'Redes Sociais'),
('Português', 'Redes sociais e novos padrões de design', 'Redes Sociais'),
('Português', 'Reescrita de Frases e Semântica', 'Semântica'),
('Português', 'Reescritura de Frases / Sintaxe e Semântica', 'Sintaxe'),
('Português', 'Reescritura de Frases e Sintaxe', 'Sintaxe'),
('Português', 'Registros Formais e Norma-Padrão', 'Registros Formais'),
('Português', 'Regência Nominal', 'Regência'),
('Português', 'Regência Verbal', 'Regência'),
('Português', 'Regência Verbal e Emprego de Pronomes', 'Regência'),
('Português', 'Regência e Transitividade Verbal', 'Regência'),
('Português', 'Regência verbal', 'Regência'),
('Português', 'Relação Verbo-Visual e Léxico (Palavras Intraduzíveis)', 'Verbos'),
('Português', 'Relação entre o erudito e o popular na música', 'Relação Entre o Erudito'),
('Português', 'Relevância estética e histórica do choro brasileiro', 'Relevância Estética'),
('Português', 'Reposicionamento estético e reciclagem artística', 'Reposicionamento Estético'),
('Português', 'Resenhas críticas e opinião implícita', 'Resenhas Críticas'),
('Português', 'Ritmo acelerado e estratégias argumentativas', 'Ritmo Acelerado'),
('Português', 'Romantismo e representação idealizada do corpo', 'Literatura'),
('Português', 'Semântica - Expressões Locucionais, Populares e Sinonímia', 'Semântica'),
('Português', 'Semântica e Conectivos / Conjunções Coordenativas', 'Coesão e Coerência'),
('Português', 'Semântica e Conjunções', 'Morfologia'),
('Português', 'Semântica e Lexicologia', 'Semântica'),
('Português', 'Semântica e Léxico', 'Semântica'),
('Português', 'Semântica e Ortografia (Emprego de Palavras)', 'Ortografia'),
('Português', 'Semântica e Polissemia', 'Semântica'),
('Português', 'Semântica e Recursos Expressivos', 'Semântica'),
('Português', 'Semântica e Relações Léxicas', 'Semântica'),
('Português', 'Semântica e Sinonímia/Antonímia', 'Semântica'),
('Português', 'Semântica e Vocabulário', 'Semântica'),
('Português', 'Semântica e sinonímia', 'Semântica'),
('Português', 'Semântica e variação histórica da linguagem', 'Semântica'),
('Português', 'Semântica — Sinonímia no contexto', 'Semântica'),
('Português', 'Semântica, polissemia e adequação vocabular', 'Semântica'),
('Português', 'Sinestesia e expressão poética das cores', 'Semântica'),
('Português', 'Sintaxe (Adjunto Adnominal e Adverbial)', 'Sintaxe'),
('Português', 'Sintaxe (Adjunto Adnominal e Predicativo)', 'Sintaxe'),
('Português', 'Sintaxe (Aposto e Vocativo)', 'Sintaxe'),
('Português', 'Sintaxe (Complementos Verbais e Nominal)', 'Sintaxe'),
('Português', 'Sintaxe (Função do Pronome Relativo)', 'Sintaxe'),
('Português', 'Sintaxe (Funções Sintáticas)', 'Sintaxe'),
('Português', 'Sintaxe (Identificação do Sujeito)', 'Sintaxe'),
('Português', 'Sintaxe (Orações Subordinadas Substantivas)', 'Sintaxe'),
('Português', 'Sintaxe (Predicativo em Oração Sem Sujeito)', 'Sintaxe'),
('Português', 'Sintaxe (Predicativo)', 'Sintaxe'),
('Português', 'Sintaxe (Tipos de Sujeito)', 'Sintaxe'),
('Português', 'Sintaxe - Colocação Pronominal', 'Colocação Pronominal'),
('Português', 'Sintaxe - Concordância verbal', 'Concordância'),
('Português', 'Sintaxe - Crase', 'Crase'),
('Português', 'Sintaxe - Crase e Regência', 'Regência'),
('Português', 'Sintaxe - Funções sintáticas dos pronomes', 'Sintaxe'),
('Português', 'Sintaxe - Orações Subordinadas e Funções Sintáticas', 'Sintaxe'),
('Português', 'Sintaxe - Orações coordenadas', 'Sintaxe'),
('Português', 'Sintaxe - Orações subordinadas adjetivas', 'Sintaxe'),
('Português', 'Sintaxe - Orações subordinadas substantivas', 'Sintaxe'),
('Português', 'Sintaxe - Regência verbal', 'Regência'),
('Português', 'Sintaxe - Tipos de Sujeito', 'Sintaxe'),
('Português', 'Sintaxe - Tipos de predicado', 'Sintaxe'),
('Português', 'Sintaxe / Adjunto Adverbial', 'Sintaxe'),
('Português', 'Sintaxe / Aposto', 'Sintaxe'),
('Português', 'Sintaxe / Complemento Nominal e Adjunto Adnominal', 'Sintaxe'),
('Português', 'Sintaxe / Concordância Verbal e Nominal', 'Concordância'),
('Português', 'Sintaxe / Emprego Incorreto de Conjunção', 'Sintaxe'),
('Português', 'Sintaxe / Funções Sintáticas (Aposto e Adjunto)', 'Sintaxe'),
('Português', 'Sintaxe / Orações Coordenadas', 'Sintaxe'),
('Português', 'Sintaxe / Orações Subordinadas Substantivas', 'Sintaxe'),
('Português', 'Sintaxe / Predicativo do Sujeito e do Objeto', 'Sintaxe'),
('Português', 'Sintaxe / Regência Verbal', 'Regência'),
('Português', 'Sintaxe / Regência Verbal e Objetos', 'Regência'),
('Português', 'Sintaxe / Termos da Oração', 'Sintaxe'),
('Português', 'Sintaxe / Termos da Oração (Sujeito)', 'Sintaxe'),
('Português', 'Sintaxe / Tipos de Predicado', 'Sintaxe'),
('Português', 'Sintaxe da Oração (Análise Morfossintática)', 'Sintaxe'),
('Português', 'Sintaxe da Oração e do Período', 'Sintaxe'),
('Português', 'Sintaxe de Termos da Oração', 'Sintaxe'),
('Português', 'Sintaxe do Período Composto (Completiva Nominal)', 'Sintaxe'),
('Português', 'Sintaxe do Período — Orações Desenvolvidas', 'Sintaxe'),
('Português', 'Sintaxe dos Pronomes Oblíquos (Objeto Direto)', 'Sintaxe'),
('Português', 'Sintaxe dos Termos da Oração', 'Sintaxe'),
('Português', 'Sintaxe e Análise Morfossintática', 'Sintaxe'),
('Português', 'Sintaxe e Coesão Textual', 'Coesão e Coerência'),
('Português', 'Sintaxe e Conectivos — Paráfrase', 'Coesão e Coerência'),
('Português', 'Sintaxe e Gramática Aplicada', 'Sintaxe'),
('Português', 'Sintaxe e Reescrita de Frases', 'Sintaxe'),
('Português', 'Sintaxe e Regência / Crase', 'Regência'),
('Português', 'Sintaxe e Relações Textuais', 'Sintaxe'),
('Português', 'Sintaxe — Adjunto Adverbial e Valores Circunstanciais', 'Sintaxe'),
('Português', 'Sintaxe — Colocação pronominal', 'Colocação Pronominal'),
('Português', 'Sintaxe — Concordância e Sintaxe de Regência', 'Concordância'),
('Português', 'Sintaxe — Concordância verbal', 'Concordância'),
('Português', 'Sintaxe — Conectivos e Orações Adverbiais', 'Coesão e Coerência'),
('Português', 'Sintaxe — Emprego de Pronomes e Regência', 'Regência'),
('Português', 'Sintaxe — Emprego do sinal indicativo de crase', 'Crase'),
('Português', 'Sintaxe — Função Sintática do Pronome Relativo ''que''', 'Sintaxe'),
('Português', 'Sintaxe — Orações Subordinadas Adjetivas', 'Sintaxe'),
('Português', 'Sintaxe — Orações Subordinadas Substantivas', 'Sintaxe'),
('Português', 'Sintaxe — Orações subordinadas adjetivas e substantivas', 'Sintaxe'),
('Português', 'Sintaxe — Período composto por coordenação', 'Sintaxe'),
('Português', 'Sintaxe — Período composto por subordinação', 'Sintaxe'),
('Português', 'Sintaxe — Regência Verbal e Crase', 'Regência'),
('Português', 'Sintaxe — Regência verbal', 'Regência'),
('Português', 'Sintaxe — Sujeito e sua classificação', 'Sintaxe'),
('Português', 'Sintaxe — Termos integrantes e acessórios da oração', 'Sintaxe'),
('Português', 'Sintaxe — Tipos de Predicado e Termos da Oração', 'Sintaxe'),
('Português', 'Sintaxe — Vozes Verbais', 'Sintaxe'),
('Português', 'Sintaxe: Classificação do Sujeito', 'Sintaxe'),
('Português', 'Sociolinguística e inclusão digital / Perfil socioeconômico', 'Sociolinguística'),
('Português', 'Substantivos (Gênero e Classificação)', 'Morfologia'),
('Português', 'Subversão de Gêneros Textuais', 'Gêneros e Tipologia Textual'),
('Português', 'Tabu linguístico e variação lexical', 'Tabu Linguístico'),
('Português', 'Tecnologia e Detecção de Plágio', 'Tecnologia'),
('Português', 'Tecnologia e Inclusão Linguística / Aplicativo Linklado', 'Tecnologia'),
('Português', 'Tecnologia e acessibilidade / Disseminação do conhecimento', 'Tecnologia'),
('Português', 'Tempos e Modos Verbais', 'Verbos'),
('Português', 'Teoria Literária (Métrica e Versificação)', 'Teoria Literária'),
('Português', 'Textos — Compreensão de texto poético (Texto 2)', 'Interpretação de Texto'),
('Português', 'Textos — Compreensão e inferência textual (Texto 1)', 'Interpretação de Texto'),
('Português', 'Textos — Ideia central e linguagem do meme (Texto 3)', 'Interpretação de Texto'),
('Português', 'Textos — Intertextualidade e relação entre textos', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia Textual', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia Textual / Tipos de Discurso', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia Textual e Argumentação', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia Textual e Gêneros Literários (Crônica)', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia e Estrutura Textual', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia e Gêneros Textuais / Análise Literária', 'Gêneros e Tipologia Textual'),
('Português', 'Tipologia textual - Discurso direto e indireto', 'Gêneros e Tipologia Textual'),
('Português', 'Transformações nas experiências lúdicas infantis', 'Transformações Nas Experiências Lúdicas Infantis'),
('Português', 'Transposição de Discurso Direto/Indireto', 'Transposição de Discurso Direto'),
('Português', 'Vanguardas Europeias e Modernismo', 'Literatura'),
('Português', 'Variantes Linguísticas e Gramática', 'Variantes Linguísticas'),
('Português', 'Variação Linguística / Dialeto Regional', 'Variação Linguística'),
('Português', 'Variação Linguística Dialetal e Gastronomia', 'Variação Linguística'),
('Português', 'Variação Linguística Ocupacional / Técnica', 'Variação Linguística'),
('Português', 'Variação Linguística e Comunicação Médico-Paciente', 'Variação Linguística'),
('Português', 'Variação Linguística e História da Língua', 'Variação Linguística'),
('Português', 'Variação Linguística e Identidade', 'Variação Linguística'),
('Português', 'Variação Linguística e Preconceito', 'Variação Linguística'),
('Português', 'Variação Linguística na Libras', 'Variação Linguística'),
('Português', 'Variação Linguística na Publicidade', 'Variação Linguística'),
('Português', 'Variação e adequação linguística / Linguagem jurídica', 'Variação'),
('Português', 'Variação linguística e história da língua', 'Variação Linguística'),
('Português', 'Variação linguística e regionalismo', 'Variação Linguística'),
('Português', 'Variação linguística e variedades populares', 'Variação Linguística'),
('Português', 'Variação pronominal e diversidade linguística', 'Variação Pronominal'),
('Português', 'Variedade Linguística e Registro Popular', 'Variação Linguística'),
('Português', 'Variedades Linguísticas e Campo Lexical', 'Variação Linguística'),
('Português', 'Variedades Linguísticas e Norma-Padrão (Texto Jurídico/Lei)', 'Variação Linguística'),
('Português', 'Verbos (conjugação e flexão)', 'Verbos'),
('Português', 'Violência colonial e resistência afetiva', 'Violência Colonial'),
('Português', 'Violência institucional e sistema prisional', 'Violência Institucional'),
('Português', 'Viés Racial nas Mídias Digitais', 'Viés Racial Nas Mídias Digitais'),
('Português', 'Vocabulário e Semântica', 'Semântica'),
('Português', 'Vocativo', 'Sintaxe'),
('Português', 'Vozes Verbais', 'Verbos'),
('Química', 'Balanceamento de Equações Químicas', 'Reações Químicas'),
('Química', 'Cinética Química (Catálise)', 'Cinética Química'),
('Química', 'Cinética Química / Catalisadores', 'Cinética Química'),
('Química', 'Cinética Química / Catalisadores e Energia de Ativação', 'Cinética Química'),
('Química', 'Cinética Química / Nanotecnologia', 'Cinética Química'),
('Química', 'Classificação da Matéria e Misturas', 'Separação de Misturas'),
('Química', 'Cálculo Estequiométrico de Soluções', 'Estequiometria'),
('Química', 'Cálculos Estequiométricos', 'Estequiometria'),
('Química', 'Densidade e Identificação de Materiais', 'Densidade'),
('Química', 'Eletroquímica (Pilhas)', 'Eletroquímica'),
('Química', 'Eletroquímica - Eletrólise Aquosa', 'Eletroquímica'),
('Química', 'Eletroquímica - Pilhas', 'Eletroquímica'),
('Química', 'Eletroquímica / Célula de Combustível Microbiana', 'Eletroquímica'),
('Química', 'Eletroquímica / Diferença de Potencial', 'Eletroquímica'),
('Química', 'Eletroquímica / Pilhas e Potencial de Redução', 'Eletroquímica'),
('Química', 'Eletroquímica / Potencial Padrão de Redução e Pilhas', 'Eletroquímica'),
('Química', 'Eletroquímica e Potencial Misto', 'Eletroquímica'),
('Química', 'Equilíbrio Químico (Le Chatelier)', 'Equilíbrio Químico'),
('Química', 'Equilíbrio Químico / Le Chatelier', 'Equilíbrio Químico'),
('Química', 'Equilíbrio Químico / Princípio de Le Chatelier', 'Equilíbrio Químico'),
('Química', 'Equilíbrio Químico e Neutralização', 'Equilíbrio Químico'),
('Química', 'Equilíbrio Químico e pH', 'Equilíbrio Químico'),
('Química', 'Estados da Matéria e Transformações', 'Estados da Matéria'),
('Química', 'Estequiometria (Massa Molar e Hidratação)', 'Estequiometria'),
('Química', 'Estequiometria (Reagente Limitante e Gráficos)', 'Estequiometria'),
('Química', 'Estequiometria / Biogás e Combustíveis', 'Estequiometria'),
('Química', 'Estequiometria / Equação dos Gases Ideais e Rendimento', 'Estequiometria'),
('Química', 'Estequiometria / Reagente Limitante', 'Estequiometria'),
('Química', 'Estequiometria / Redução Aluminotérmica', 'Estequiometria'),
('Química', 'Estequiometria / Rendimento de reações', 'Estequiometria'),
('Química', 'Estequiometria e Reciclagem de Alumínio', 'Estequiometria'),
('Química', 'Estequiometria e Rendimento', 'Estequiometria'),
('Química', 'Estequiometria e Rendimento Reacional', 'Estequiometria'),
('Química', 'Estequiometria e Soluções', 'Estequiometria'),
('Química', 'Estequiometria e Titulação', 'Estequiometria'),
('Química', 'Estrutura Atômica (Atomística)', 'Atomística e Tabela Periódica'),
('Química', 'Estrutura Atômica - Modelo de Bohr', 'Atomística e Tabela Periódica'),
('Química', 'Estrutura Atômica / Luminescência (Fosforecência)', 'Atomística e Tabela Periódica'),
('Química', 'Estrutura Atômica e Tabela Periódica', 'Atomística e Tabela Periódica'),
('Química', 'Estrutura Atômica — Íons e isoeletronicidade', 'Atomística e Tabela Periódica'),
('Química', 'Estrutura e Modelos Atômicos', 'Atomística e Tabela Periódica'),
('Química', 'Estudo da Matéria — Gráficos de aquecimento e mudança de fase', 'Estudo da Matéria'),
('Química', 'Evolução dos Modelos Atômicos / Modelo de Bohr', 'Atomística e Tabela Periódica'),
('Química', 'Fontes de Energia e Combustão', 'Fontes de Energia'),
('Química', 'Funções Inorgânicas / Caráter ácido-base de sais', 'Ácidos, Bases e pH'),
('Química', 'Funções Inorgânicas e Neutralização', 'Ácidos, Bases e pH'),
('Química', 'Funções Inorgânicas — Classificação dos ácidos', 'Ácidos, Bases e pH'),
('Química', 'Funções Orgânicas', 'Química Orgânica'),
('Química', 'Funções Orgânicas / Solubilidade e polaridade', 'Química Orgânica'),
('Química', 'Físico-Química (Células Solares e Oxirredução)', 'Eletroquímica'),
('Química', 'Físico-Química (Isomeria e Fotoquímica)', 'Química Orgânica'),
('Química', 'Físico-Química / Equilíbrio Químico e Le Chatelier', 'Equilíbrio Químico'),
('Química', 'Físico-Química / Radioatividade e Tempo de Meia-Vida', 'Radioatividade'),
('Química', 'Físico-Química de Surfactantes (Sabões)', 'Físico-química de Surfactantes'),
('Química', 'Físico-Química e Micro-ondas', 'Físico-química'),
('Química', 'Gases Ideais / Equação de Clapeyron', 'Gases'),
('Química', 'Gases Perfeitos (Equação de Clapeyron)', 'Gases'),
('Química', 'História da Química / Representações e Fórmulas Químicas', 'História da Química'),
('Química', 'Impactos Ambientais / Poluição Térmica e Solubilidade', 'Soluções'),
('Química', 'Indústria Farmacêutica / Polímeros', 'Química Orgânica'),
('Química', 'Indústria e Processos Químicos', 'Indústria'),
('Química', 'Interações Intermoleculares e Adsorção', 'Interações Intermoleculares'),
('Química', 'Interações Intermoleculares e Polaridade', 'Ligações Químicas'),
('Química', 'Introdução à Química Orgânica / Conceito', 'Química Orgânica'),
('Química', 'Isomeria / Isomeria Plana e Espacial', 'Química Orgânica'),
('Química', 'Isomeria Espacial (Geométrica)', 'Química Orgânica'),
('Química', 'Ligação Química', 'Ligações Químicas'),
('Química', 'Ligação Química (Caráter Iônico e Eletronegatividade)', 'Ligações Químicas'),
('Química', 'Ligações Químicas e Tabela Periódica', 'Ligações Químicas'),
('Química', 'Materiais e Meio Ambiente', 'Materiais'),
('Química', 'Misturas — Métodos de separação de misturas', 'Separação de Misturas'),
('Química', 'Modelos Atômicos', 'Atomística e Tabela Periódica'),
('Química', 'Métodos de Purificação / Propriedades da Água Destilada', 'Métodos de Purificação'),
('Química', 'Métodos de Separação - Cromatografia', 'Métodos de Separação'),
('Química', 'Métodos de Separação de Misturas', 'Separação de Misturas'),
('Química', 'Processos de Separação de Misturas / Adsorção', 'Separação de Misturas'),
('Química', 'Propriedades Coligativas - Osmose Reversa', 'Propriedades Coligativas'),
('Química', 'Química Ambiental (Correção de Solo)', 'Química Ambiental'),
('Química', 'Química Ambiental / Estequiometria na Combustão', 'Estequiometria'),
('Química', 'Química Ambiental / Poluição', 'Química Ambiental'),
('Química', 'Química Ambiental / Polímeros', 'Química Orgânica'),
('Química', 'Química Ambiental / Tratamento de água e coagulação', 'Química Ambiental'),
('Química', 'Química Ambiental e Ciclo do Carbono', 'Química Ambiental'),
('Química', 'Química Ambiental e Polímeros', 'Química Orgânica'),
('Química', 'Química Ambiental e Segurança', 'Química Ambiental'),
('Química', 'Química Geral (Tabela Periódica)', 'Atomística e Tabela Periódica'),
('Química', 'Química Inorgânica (Dureza da Água)', 'Funções Inorgânicas'),
('Química', 'Química Orgânica (Estrutura de Tensoativos)', 'Química Orgânica'),
('Química', 'Química Orgânica (Hibridação do Carbono)', 'Química Orgânica'),
('Química', 'Química Orgânica (Hidrocarbonetos e Octanagem)', 'Química Orgânica'),
('Química', 'Química Orgânica (Isomeria Óptica)', 'Química Orgânica'),
('Química', 'Química Orgânica (Isomeria)', 'Química Orgânica'),
('Química', 'Química Orgânica (Nucleofilia e Reatividade)', 'Química Orgânica'),
('Química', 'Química Orgânica (Reações de Oxidação)', 'Química Orgânica'),
('Química', 'Química Orgânica (Substituição Nucleofílica)', 'Química Orgânica'),
('Química', 'Química Orgânica - Funções', 'Química Orgânica'),
('Química', 'Química Orgânica - Ozonólise', 'Química Orgânica'),
('Química', 'Química Orgânica / Biodegradabilidade', 'Química Orgânica'),
('Química', 'Química Orgânica / Caráter Ácido-Base de Compostos Orgânicos', 'Química Orgânica'),
('Química', 'Química Orgânica / Farmacologia', 'Química Orgânica'),
('Química', 'Química Orgânica / Funções Orgânicas', 'Química Orgânica'),
('Química', 'Química Orgânica / Funções Orgânicas e Fórmulas Moleculares', 'Química Orgânica'),
('Química', 'Química Orgânica / Interações Intermoleculares e Separação de Óleo', 'Química Orgânica'),
('Química', 'Química Orgânica / Polaridade e Solubilidade em Água', 'Química Orgânica'),
('Química', 'Química Orgânica / Reações Orgânicas de Descarboxilação', 'Química Orgânica'),
('Química', 'Química Orgânica / Separação de misturas', 'Química Orgânica'),
('Química', 'Química Orgânica e Lipofilia de Fármacos', 'Química Orgânica'),
('Química', 'Química Orgânica e Processos Industriais', 'Química Orgânica'),
('Química', 'Química Orgânica e Reações Ácido-Base (Brönsted-Lowry)', 'Química Orgânica'),
('Química', 'Radioatividade - Datação Carbono-14', 'Radioatividade'),
('Química', 'Radioatividade e Datação por Carbono-14', 'Radioatividade'),
('Química', 'Reações Inorgânicas e Precipitação', 'Funções Inorgânicas'),
('Química', 'Reações Químicas e Meio Ambiente', 'Reações Químicas'),
('Química', 'Reações Químicas — Balanceamento de equações', 'Reações Químicas'),
('Química', 'Reações de Oxirredução / Remediação de solos', 'Eletroquímica'),
('Química', 'Reações Ácido-Base Orgânicas', 'Química Orgânica'),
('Química', 'Separação de Misturas / Decantação', 'Separação de Misturas'),
('Química', 'Separação de Misturas / Propriedades Físicas', 'Separação de Misturas'),
('Química', 'Soluções / Concentração molar e diluição', 'Estequiometria'),
('Química', 'Soluções / Estequiometria', 'Estequiometria'),
('Química', 'Soluções e Densidade', 'Soluções'),
('Química', 'Tabela Periódica', 'Atomística e Tabela Periódica'),
('Química', 'Tabela Periódica - Eletronegatividade', 'Atomística e Tabela Periódica'),
('Química', 'Tabela Periódica — Distribuição eletrônica dos elementos', 'Atomística e Tabela Periódica'),
('Química', 'Termoquímica - Lei de Hess', 'Termoquímica'),
('Química', 'Termoquímica / Entalpia de reação', 'Termoquímica'),
('Química', 'Termoquímica e Estequiometria', 'Termoquímica'),
('Química', 'Termoquímica e Lei de Hess', 'Termoquímica'),
('Sociologia', 'Antropologia Política e Poder', 'Estado e Poder'),
('Sociologia', 'Ações Afirmativas e Discriminação Positiva de Gênero (Heleieth Saffioti)', 'Ações Afirmativas'),
('Sociologia', 'Biografia e História Social', 'Biografia'),
('Sociologia', 'Ciência Política e Modelos Democráticos', 'Estado e Poder'),
('Sociologia', 'Desigualdade Social e Fome no Brasil', 'Desigualdade e Estratificação'),
('Sociologia', 'Desigualdade social e direito ao lazer', 'Desigualdade e Estratificação'),
('Sociologia', 'Desigualdade social e exclusão digital / Pandemia', 'Desigualdade e Estratificação'),
('Sociologia', 'Direitos Humanos e Condição Feminina no Afeganistão', 'Cidadania e Direitos'),
('Sociologia', 'Direitos Indígenas e Patrimônio Cultural (ONU 2007)', 'Cidadania e Direitos'),
('Sociologia', 'Direitos humanos e cidadania / Condição de apátrida', 'Cidadania e Direitos'),
('Sociologia', 'Estado de Direito / Princípio da legalidade', 'Cidadania e Direitos'),
('Sociologia', 'Filosofia da Mente e Epistemologia', 'Filosofia da Mente'),
('Sociologia', 'Foucault / Sociedade disciplinar e controle', 'Foucault'),
('Sociologia', 'Globalização e Identidades Culturais (Stuart Hall)', 'Cultura e Identidade'),
('Sociologia', 'Indústria Cultural (Escola de Frankfurt)', 'Cultura e Identidade'),
('Sociologia', 'Interseccionalidade / Raça e gênero na extrema pobreza', 'Desigualdade e Estratificação'),
('Sociologia', 'Intolerância Religiosa e Religiões Afro-Brasileiras (Reginaldo Prandi)', 'Intolerância Religiosa'),
('Sociologia', 'Liderança Indígena e Matriarcado (Cacique Pequena / Jenipapo-Kanindé)', 'Liderança Indígena'),
('Sociologia', 'Modernidade Urbana e Liquidez das Relações (Paulinho da Viola - Sinal Fechado)', 'Modernidade Urbana'),
('Sociologia', 'Movimentos Sociais Contemporâneos / Interseccionalidade', 'Movimentos Sociais'),
('Sociologia', 'Movimentos sociais urbanos / Direito à moradia', 'Cidadania e Direitos'),
('Sociologia', 'Mundo do Trabalho / Contradições do Capitalismo', 'Trabalho e Sociedade'),
('Sociologia', 'Mundo do trabalho / Automação e desemprego estrutural', 'Trabalho e Sociedade'),
('Sociologia', 'Patrimônio Cultural Imaterial', 'Cultura e Identidade'),
('Sociologia', 'Patrimônio cultural / Memória do trabalho artesanal', 'Trabalho e Sociedade'),
('Sociologia', 'Poder e Microfísica da Disciplina (Michel Foucault)', 'Estado e Poder'),
('Sociologia', 'Precarização e Invisibilidade do Trabalho na Era Digital', 'Trabalho e Sociedade'),
('Sociologia', 'Redes sociais e saúde mental / Positividade tóxica', 'Redes Sociais'),
('Sociologia', 'Reestruturação Produtiva e Trabalho', 'Trabalho e Sociedade'),
('Sociologia', 'Relações e Estereótipos de Gênero', 'Relações'),
('Sociologia', 'Relações étnico-raciais / Racismo estrutural', 'Relações Étnico-raciais'),
('Sociologia', 'Religiosidade popular / Padre Cícero e Juazeiro', 'Religiosidade Popular'),
('Sociologia', 'Resistência indígena e identidade linguística / Povo Pataxó', 'Cultura e Identidade'),
('Sociologia', 'Ritos de Passagem e Memória Coletiva (Axexê)', 'Ritos de Passagem'),
('Sociologia', 'Saberes tradicionais / Paneleiras de Goiabeiras', 'Saberes Tradicionais'),
('Sociologia', 'Saúde Pública e Conceito de Saúde', 'Saúde Pública'),
('Sociologia', 'Segregação Racial e Apartheid', 'Segregação Racial'),
('Sociologia', 'Sociedade Industrial e Homem Unidimensional (Herbert Marcuse)', 'Sociedade Industrial'),
('Sociologia', 'Sociedade do Espetáculo e Mídia', 'Sociedade do Espetáculo'),
('Sociologia', 'Sociologia Ambiental e Ativismo Indígena', 'Sociologia Ambiental'),
('Sociologia', 'Sociologia Política e Participação Cidadã', 'Estado e Poder'),
('Sociologia', 'Sociologia da Modernidade e Tecnologia', 'Sociologia da Modernidade'),
('Sociologia', 'Sociologia do Conhecimento e Durkheim', 'Teóricos Clássicos'),
('Sociologia', 'Sociologia do Trabalho e Capitalismo', 'Trabalho e Sociedade'),
('Sociologia', 'Tecnologia e relações sociais / Estímulo à cooperação', 'Tecnologia'),
('Sociologia', 'Teoria Política e Contratualismo', 'Estado e Poder'),
('Sociologia', 'Trabalho e Relações Laborais', 'Trabalho e Sociedade'),
('Sociologia', 'Transformações Históricas do Dogma e Mercado Religioso', 'Transformações Históricas do Dogma'),
('Sociologia', 'Transmissão Cultural e Mídia (Novelas Brasileiras)', 'Cultura e Identidade'),
('Sociologia', 'Utopia e Mudança Social (Zygmunt Bauman)', 'Utopia'),
('Sociologia', 'Violência Patrimonial contra a Mulher (Lei Maria da Penha)', 'Violência e Segurança'),
('Sociologia', 'Violência doméstica / Ciclo da violência e feminicídio', 'Violência e Segurança'),
('Sociologia', 'Ética e Filosofia Política (Aristóteles)', 'Estado e Poder');

COMMIT;
