-- ============================================================================
-- BatCaverna — Seed do Banco de Questões: CN
-- Gerado automaticamente por scripts/gerar_seed_sql.py — NÃO EDITE À MÃO.
-- Questões neste arquivo: 32   |   Lote 2 de 2
--
-- Pré-requisitos: migrations 000 e 004 já aplicadas.
-- Idempotente: rodar de novo não duplica (ON CONFLICT em hash_conteudo).
-- ============================================================================

BEGIN;

CREATE TEMP TABLE stg_questoes (
  concurso_sigla    TEXT,
  materia_nome      TEXT,
  assunto_nome      TEXT,
  ano               INTEGER,
  dia_prova         TEXT,
  banca             TEXT,
  numero_ordem      INTEGER,
  numero_original   TEXT,
  area_conhecimento TEXT,
  dificuldade       TEXT,
  texto_base        TEXT,
  enunciado         TEXT,
  alternativas      JSONB,
  resposta_correta  TEXT,
  explicacao        TEXT,
  figura_descricao  TEXT,
  resolucao_passos  JSONB,
  resolucao_status  TEXT,
  precisa_resolucao BOOLEAN,
  anulada           BOOLEAN,
  hash_conteudo     TEXT,
  arquivo_origem    TEXT
) ON COMMIT DROP;

INSERT INTO stg_questoes VALUES
('CN', 'Português', 'Crase', 2026, '2º dia', 'SSPM - Marinha do Brasil', 19, '19', NULL, 'medio', 'Nas orações a seguir, retiradas dos textos propostos, podemos observar o correto uso do acento indicativo de crase: "E, à medida que vai sendo comido, vai acabando." (Texto I, §7); "Eu não quis confessar que não estava à altura da eternidade." (Texto II, §15); e "Depois começou a girar a bola, à procura de alguma coisa." (Texto III, §1).', 'Assinale a alternativa cuja sequência completa corretamente os espaços deixados no fragmento a seguir, de acordo com a ocorrência ou não do fenômeno da crase:

"A decisão que cabe _____ magistrada proferir certamente estremecerá _____ bases legais da luta pelo direito _____ vida, _____ saber, o mesmo dado _____ filhas de mães solo."', '[{"letra": "A", "texto": "à / às / à / a / a"}, {"letra": "B", "texto": "à / as / à / a / as"}, {"letra": "C", "texto": "a / às / à / a / às"}, {"letra": "D", "texto": "a / as / a / à / às"}, {"letra": "E", "texto": "à / as / à / a / às"}]', 'E', 'A sequência correta é: "cabe à magistrada" (preposição a + artigo a), "estremecerá as bases" (somente artigo plural), "direito à vida" (preposição a + artigo a), "a saber" (preposição antes de verbo) e "dado às filhas" (preposição a + artigo as).', NULL, NULL, 'resumida', FALSE, FALSE, '72afde7073fbe08315ed4f04cccf7d2411886d381537bf19a0f18a9f3a90ffe3', 'cn-2026-dia2.txt'),
('CN', 'Português', 'Funções da Linguagem', 2026, '2º dia', 'SSPM - Marinha do Brasil', 20, '20', NULL, 'medio', '(Utilizar o TEXTO IV da Questão 17)', 'De acordo com o contexto apresentado na tirinha de Maurício de Sousa, qual opção abaixo destaca corretamente as funções da linguagem que predominam no segundo quadrinho?', '[{"letra": "A", "texto": "Metalinguística e fática."}, {"letra": "B", "texto": "Conativa e referencial."}, {"letra": "C", "texto": "Apelativa e denotativa."}, {"letra": "D", "texto": "Emotiva e poética."}, {"letra": "E", "texto": "Referencial e metalinguística."}]', 'D', 'A fala do segundo quadrinho expressa sentimentos e visões interiores do personagem (função emotiva/expressiva) e atribui valor poético/figurado à muda de árvore como "esperança" (função poética).', NULL, NULL, 'resumida', TRUE, FALSE, '24dd019d527a122da75ef6318ec129b7a10fdcfcd833cd3f087c657b50aaabc1', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'População e Demografia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 21, '21', NULL, 'medio', 'Desde a realização do primeiro Censo Demográfico, em 1872, até os dias atuais, o quantitativo populacional brasileiro aumentou mais de vinte vezes.
(Vivá: Geografia. Vol. 2. Igor Moreira. Curitiba: Positivo, 2016.)', 'Sobre a evolução populacional brasileira, assinale a opção correta.', '[{"letra": "A", "texto": "Entre os anos 1960 e 1970 iniciou-se a redução das taxas de natalidades, ainda que não tenha ocorrido incentivo público oficial de planejamento familiar."}, {"letra": "B", "texto": "Atualmente a inserção feminina no mercado de trabalho resultou num aumento da taxa de fecundidade, visto a sua maior capacidade de criar proles mais numerosas."}, {"letra": "C", "texto": "Nos anos 1930 e 1940, a população cresceu de forma bastante acelerada pois embora a taxa de natalidade fosse pequena, a taxa de mortalidade era muito baixa."}, {"letra": "D", "texto": "A partir dos anos 1970 verificou-se uma grande aceleração do crescimento demográfico, resultado do aumento das taxas de natalidades nos centros urbanos."}, {"letra": "E", "texto": "Uma das características atuais da população é o lento envelhecimento, fenômeno resultante do difícil acesso aos métodos profiláticos nas áreas urbanas."}]', 'A', 'O declínio da taxa de natalidade no Brasil iniciou-se entre as décadas de 1960 e 1970, associado à urbanização, maior acesso à informação e difusão de métodos contraceptivos, mesmo sem uma política oficial coercitiva de planejamento familiar estatal.', NULL, NULL, 'resumida', FALSE, FALSE, 'e3f871bf4e2bfa9658c521f4ccf81e2e1cead932aa9c582c17df2d3f50b688d2', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'Climatologia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 22, '22', NULL, 'medio', 'Ligados à circulação geral da atmosfera, que redistribui a energia solar pelas zonas térmicas do planeta, o tempo e o clima, embora não sejam a mesma coisa, referem-se aos mesmos fenômenos atmosféricos: temperatura e insolação, pressão atmosférica, ventos, umidade do ar e precipitações.
(Moreira, Igor. Vivá: geografia; volume 2. Curitiba: Positivo, 2016. pg. 102.)', 'Para explicar as mudanças do tempo e do clima, é importante compreender, principalmente, a dinâmica das massas de ar. Sobre a movimentação das massas de ar que atuam no Brasil, assinale a opção correta.', '[{"letra": "A", "texto": "Ao se deslocar de uma zona de alta pressão atmosférica (ciclonial) para outra de baixa pressão (anticiclonial), as massas de ar levam consigo as características adquiridas na região de origem."}, {"letra": "B", "texto": "A maior parte do território nacional está localizada na zona intertropical, onde os climas são controlados, sobretudo, pelo sistema dos ventos contra-alísios, que dão origem a massas de ar equatoriais, tropicais e subtropicais."}, {"letra": "C", "texto": "Os ventos alísios de sudeste são oriundos do anticiclone dos Açores, e os alísios de sudeste vêm do anticiclone do Atlântico Norte, o que contribui para a queda acentuada da pluviosidade durante o verão austral."}, {"letra": "D", "texto": "Em virtude da inversão das estações nos hemisférios e da ação de deslocamento dos centros anticicloniais e das massas de ar, a linha do equador térmico se move para o norte e para o sul em relação à do equador geográfico."}, {"letra": "E", "texto": "Os ventos alísios sopram das áreas tropicais para as áreas subtropicais, formando a chamada faixa de convergência intertropical, os quais provocam poucas chuvas durante todo o ano no sul do país."}]', 'D', 'As estações do ano e o deslocamento sazonal dos centros de alta e baixa pressão provocam a movimentação do Equador Térmico (e da Zona de Convergência Intertropical) ao longo dos hemisférios em relação ao Equador Geográfico.', NULL, NULL, 'resumida', FALSE, FALSE, '99e43ab063e2e2ba7a08277b541b04d644d154ce0db8356a9ad8137813c5d042', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'Geomorfologia e Relevo', 2026, '2º dia', 'SSPM - Marinha do Brasil', 23, '23', NULL, 'dificil', 'Classificar o relevo implica agrupar suas diferentes formas em compartimentos de acordo com a semelhança de características externas, com base em determinados critérios.
(Moreira, Igor. Vivá: geografia: volume 2. Curitiba: Positivo, 2016. pg. 86.)', 'As classificações do relevo brasileiro avançaram na medida em que a geomorfologia evoluiu. No que diz respeito às classificações do relevo brasileiro, analise as afirmativas a seguir.

I- Até meados do século XX, as classificações do relevo brasileiro prendiam-se basicamente à estrutura geológica, de modo que, muitas vezes, as formas de relevo eram definidas conforme o tipo de rochas.
II- A classificação do geógrafo Aziz Nacib Ab''Sáber, nos anos 1960, foi a primeira a romper, de forma mais definitiva, com certa confusão existente entre estrutura geológica e relevo.
III- Na década de 1990, foi elaborada uma nova classificação do relevo, a partir de imagens de radar, na qual o geógrafo Jurandyr L. S. Ross levou em consideração, como base em seus estudos, os chamados paleoclimas.

Assinale a opção correta.', '[{"letra": "A", "texto": "Apenas a afirmativa I está correta."}, {"letra": "B", "texto": "Apenas a afirmativa II está correta."}, {"letra": "C", "texto": "Apenas as afirmativas I e III estão corretas."}, {"letra": "D", "texto": "Apenas as afirmativas II e III estão corretas."}, {"letra": "E", "texto": "As afirmativas I, II e III estão corretas."}]', 'E', 'As três afirmativas estão corretas. As primeiras classificações vinculavam-se à altimetria/estrutura geológica, Ab''Sáber introduziu os critérios morfoclimáticos nos anos 1960, e Jurandyr Ross refinou o mapeamento nos anos 1990 usando o Radambrasil e dados morfogenéticos/paleoclimáticos.', NULL, NULL, 'resumida', FALSE, FALSE, '9c5b6ae9ace3c92ced31f01056b35115fd1d00b36c6986a2eda2b192b5dadcec', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'Climatologia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 24, '24', NULL, 'facil', 'A interação entre os climas, o relevo e os solos resulta em diferentes tipos de fauna e flora. Em regiões quentes e úmidas, a biodiversidade é muito maior se compararmos às regiões frias e/ou secas.
(Martini, Alice de. Geografia Ação e Transformação. São Paulo: Escala Educacional, 2016. p. 140.)', 'Em relação aos domínios morfoclimáticos brasileiros, assinale a opção correta.', '[{"letra": "A", "texto": "Caatinga - estende-se desde o Sertão até a faixa mais oriental da Região Nordeste, marcada pelo clima semiárido, com chuvas regulares e concentradas nos meses que compreendem o solstício de junho."}, {"letra": "B", "texto": "Amazônia - caracteriza-se por apresentar terras baixas, depressões relativas e planícies, grande insolação e grande pluviosidade anual, o que define o seu clima e grande diversidade à paisagem vegetal."}, {"letra": "C", "texto": "Mares de Morros - domínio associado à região das planícies cristalinas dispostas na parte mais ocidental do país, formando a Floresta Tropical ou Mata Atlântica, com moderado índice de devastação."}, {"letra": "D", "texto": "Araucária - vegetação bastante heterogênea e típica das planícies sulistas, notadamente no Estado do Paraná, onde as baixas temperaturas e os solos de boa fertilidade proporcionam vastas áreas de domínio e cobertura regional."}, {"letra": "E", "texto": "Cerrado - Vegetação composta por dois extratos, um arbóreo e outro arbustivo, onde o seu solo, muito fértil e com baixa concentração de hidróxidos de alumínio e ferro, estimula o desenvolvimento comercial de diversos cultivos de subsistência."}]', 'B', 'O domínio da Amazônia é caracterizado por extensas superfícies rebaixadas (planícies e depressões), altas temperaturas, elevada insolação e forte pluviosidade ao longo do ano inteiro.', NULL, NULL, 'resumida', FALSE, FALSE, 'e87fb5007c6839d8c8d8472027ebdaf810a0530e03391c3f2b1756c69552badf', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'Urbanização', 2026, '2º dia', 'SSPM - Marinha do Brasil', 25, '25', NULL, 'medio', 'Após a Segunda Mundial, o processo de urbanização intensificou-se tanto nos países desenvolvidos como nos países subdesenvolvidos e emergentes.
(Geografia: leituras e interação, volume 2/Arno Alisio Goettems, Antônio Luís Joia. São Paulo: Leya, 2016. p. 79)', 'Sabendo que a evolução da urbanização brasileira ocorreu de forma singular, é correto afirmar que:', '[{"letra": "A", "texto": "se materializou no início do século XIX, quando a cafeicultura estimulou a emigração e a concentração populacional no meio urbano."}, {"letra": "B", "texto": "ganhou forte impulso ao longo da segunda metade do século XX, quando o desenvolvimento do segundo setor econômico estimulou a vida urbana no país."}, {"letra": "C", "texto": "sempre ocorreu de forma planejada, já que a sua existência está vinculada às fiscalizações do poder público federal, estadual e municipal."}, {"letra": "D", "texto": "proporcionou em algumas cidades, como o caso de Brasília-DF, um modelo de organização espacial, especialmente nas ditas cidades-satélites."}, {"letra": "E", "texto": "estimulou a formação das Regiões Metropolitanas já na primeira metade do século XIX, especialmente nas regiões Norte e Centro-Oeste."}]', 'B', 'A urbanização brasileira acelerou-se intensamente a partir da segunda metade do século XX, motivada pela rápida industrialização (setor secundário) e pelo consequente exodo rural em massa.', NULL, NULL, 'resumida', FALSE, FALSE, '3d2e329adde65146af2d06d3d5445c435d936ba003c05582acd0d5d24dcf6555', 'cn-2026-dia2.txt'),
('CN', 'Geografia', 'Indústria', 2026, '2º dia', 'SSPM - Marinha do Brasil', 26, '26', NULL, 'medio', 'A industrialização de um país ocorre por meio de um processo que envolve múltiplos interesses em determinadas circunstâncias históricas. No Brasil, esse processo consolidou-se na segunda Revolução Industrial.
(Geografia: leituras e interação, volume 2/Arno Alísio Goettems, Antônio Luís Joia. 2. ed. São Paulo: Leya, 2016. p. 37.)', 'Sobre o processo industrial brasileiro, assinale a opção correta.', '[{"letra": "A", "texto": "O seu grande impulso deveu-se a fatores histórico-geográficos externos, sobretudo em períodos em que o comércio mundial foi abalado por guerras mundiais ou por crises econômicas ocorridas durante o século XX."}, {"letra": "B", "texto": "Com relação à distribuição espacial das atividades industriais no território brasileiro, historicamente concentram-se nas regiões Sudeste e Centro-Oeste, ainda que atualmente haja um forte deslocamento para a região Norte."}, {"letra": "C", "texto": "O principal surto industrial brasileiro foi financiado pelo capital acumulado proveniente da economia açucareira e contou com alguns fatores locacionais, como uma ampla rede ferroviária e o fim da escravidão."}, {"letra": "D", "texto": "A partir da segunda metade do século XIX, as indústrias de bens de consumo duráveis se destacaram, especialmente pelos investimentos do capital privado nacional nesse tipo de produção."}, {"letra": "E", "texto": "Somente a partir dos anos 1960 ocorreu o desenvolvimento das atividades automotivas brasileiras, quando receberam fortes subsídios estatais e grande apoio logístico do Japão."}]', 'A', 'O processo de substituição de importações que alavancou a indústria nacional foi fortemente impulsionado por eventos internacionais (Primeira e Segunda Guerras Mundiais e Crise de 1929), que bloqueavam a compra de bens manufaturados estrangeiros.', NULL, NULL, 'resumida', FALSE, FALSE, '5a557f685881188bce8260e3f55fa16fab5af4d5e257bd6601b6129e2ebb2727', 'cn-2026-dia2.txt'),
('CN', 'História', 'Brasil Colônia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 27, '27', NULL, 'medio', 'O historiador espanhol Ramón Blanco, em seu livro Las "bandeiras", publicado em 1966, reconhecendo que a nomenclatura do movimento é extremamente confusa, gasta mais de quinhentas páginas para tentar provar que as bandeiras nada mais eram que unidades militarizadas - algo como as companhias ou os batalhões dos exércitos de hoje - que foram utilizadas em muitas das mais importantes incursões territoriais feitas pelos luso brasileiros na América do Sul com a finalidade de capturar selvagens.
(Fonte: FILHO, Synésio Sampaio Goess. Navegantes, Bandeirantes, Diplomatas. Um ensaio sobre a formação das fronteiras do Brasil. Martins Fontes / Biblioteca do Exército Editora. Rio de Janeiro-RJ, 2000, Pg.90)', 'O historiador Ramón Blanco, em seu texto, faz referência à atividade denominada por alguns historiadores de Bandeiras, ocorrida no período colonial brasileiro.
Com base nessas informações assinale a que apresenta corretamente algumas das consequências geradas por essa atividade no Brasil colonial.', '[{"letra": "A", "texto": "Promoveram a exploração do interior da colônia para além da linha divisória estabelecida pelo Tratado de Tordesilhas, contribuindo, desta forma, para o alargamento dos domínios portugueses na América destacando-se a região sul, centro-oeste, Mato Grosso e Amazônia que foi alcançada pela expedição comandada por Fernão Dias Paes."}, {"letra": "B", "texto": "Legalmente autorizadas, tanto pelo governo português quanto pelo espanhol, devido à União Ibérica, colaboraram para a criação de rotas que interligavam São Paulo ao Guairá, região localizada no atual estado do Paraná, as minas de Potosí, controlada pelos espanhóis, no território correspondente à atual Bolívia."}, {"letra": "C", "texto": "Ampliaram as fronteiras da colônia portuguesa para além da Linha divisória estabelecida pelo Tratado de Tordesilhas assim como, neste processo, contribuíram tanto para a ocupação e surgimento de povoados em regiões litorâneas, onde se encontram as atuais cidades de Paranaguá e Laguna, ou do interior, onde se encontra a atual cidade de Curitiba."}, {"letra": "D", "texto": "As expedições bandeirantes não apenas permitiram que a Coroa portuguesa tomasse conhecimento das regiões interioranas do território, localizadas além dos limites do Tratado de Tordesilhas, como também, incentivadas pela administração portuguesa na América, colonizaram estas áreas ampliando sensivelmente os domínios dos portugueses na colônia."}, {"letra": "E", "texto": "Alargaram as fronteiras da colônia portuguesa para além da Linha de Tordesilhas, assim como contribuíram consideravelmente tanto para a ocupação e surgimento de povoados que surgiram ao longo de expedições, como a de Antonio Raposo Tavares que alcançou a cidade de Fortaleza, no atual estado do Ceará."}]', 'D', 'As expedições bandeirantes ultrapassaram os limites formais do Tratado de Tordesilhas, expandindo a presença territorial portuguesa no interior do continente e mapeando novos recursos minerais e caminhos coloniais.', NULL, NULL, 'resumida', FALSE, FALSE, '68a3cbeb0b22c7a65e8ab020a6d534ce78103f67264aa1259e53ddff9bbdbfd3', 'cn-2026-dia2.txt'),
('CN', 'História', 'Guerras Mundiais', 2026, '2º dia', 'SSPM - Marinha do Brasil', 28, '28', NULL, 'medio', 'Realmente, a 1ª Divisão de Infantaria Expedicionária era apenas uma entre centenas de unidades que os Aliados puseram em campo. Mas se a proporção de brasileiros que passaram pelo combate foi exígua, isso não acarretou minoração das contingências com que nossa tropa se deparou na guerra. Embora a Itália fosse um teatro de operações "secundário", para os combatentes a vida na linha de frente em nada diferia de outros fronts mais ativos.
(FONTE: MAXIMIANO, Campiani. Neve, fogo e montanhas: a experiência brasileira no combate na Itália (1944/1955), in. Nova História Militar Brasileira. Organiz. Celso Castro, Vitor Izecksohn e Hendrik Kraay. FGV Editora / Bom Texto. Rio de Janeiro, 2004. Pg.345)', 'Durante a Segunda Guerra Mundial (1939-1945), o Brasil foi levado a participar deste conflito ao lado das forças Aliadas, após navios brasileiros terem sido atacados por submarinos alemães no Atlântico.
Sobre a presença brasileira na Segunda Guerra Mundial é correto afirmar que', '[{"letra": "A", "texto": "foi considerada inexpressiva pelo fato de o Brasil ter se mantido neutro durante todo o conflito enviando apenas a FEB (Força Expedicionária Brasileira) praticamente no final da guerra, ou seja, já em 1945, participando de um combate apenas que ocorreu em Monte Castelo."}, {"letra": "B", "texto": "participou da guerra ao lado dos países aliados contra o Eixo e, entre as formas de participação, com a FEB (Força Expedicionária Brasileira), criada em 1943 que atuou contra as tropas alemãs na Itália participando de batalhas em Monte Castello, Castelnuovo e Fornovo."}, {"letra": "C", "texto": "a participação brasileira restringiu-se em sua totalidade no território nacional com a atuação da FAB (Força Aérea Brasileira) e da Marinha, enquanto apenas a FEB (Força Expedicionária Brasileira) lutou nos campos europeus com um contingente de mais de 45 mil homens."}, {"letra": "D", "texto": "participou da guerra ao lado dos países aliados contra as forças da Tríplice Entente, enviando a FAB (Força Aérea Brasileira) e a FEB (Força Expedicionária Brasileira) que lutou contra as tropas alemãs na Itália em batalhas como a de Monte Castello, Castelnuovo e Fornovo."}, {"letra": "E", "texto": "limitada a ações de patrulhamento da Marinha e da FAB (Força Aérea Brasileira) ao longo do Litoral Brasileiro sendo que apenas a FEB (Força Expedicionária Brasileira) lutou ao lado das forças aliadas contra as forças alemãs na Itália."}]', 'B', 'O Brasil enviou a Força Expedicionária Brasileira (FEB) em 1943/1944 para combater ao lado dos Aliados na campanha da Itália, conquistando posições estratégicas decisivas como Monte Castello, Castelnuovo e Fornovo.', NULL, NULL, 'resumida', FALSE, FALSE, '720fc295d773afe92388bae3975b19392dd8d3d5314da2a145799d124159cc20', 'cn-2026-dia2.txt'),
('CN', 'História', 'Brasil Império', 2026, '2º dia', 'SSPM - Marinha do Brasil', 29, '29', NULL, 'medio', 'Abriu-se, então, um vácuo político que liberou a imaginação popular [...]. De um lado, o problema prático e mais imediato foi resolvido a partir de uma sucessão de quatro regências, assumidas por políticos brasileiros [...]. De outro lado, contudo, a questão sucessória incendiou as demais províncias, que agora, sem um rei no poder, passaram a contestar a legitimidade dos novos governantes.
(Fonte: SCHWARCZ, Lilia M; STARLING, Heloisa M. Brasil: uma biografia. São Paulo: Companhia das Letras, 2015. p. 243.)', 'Com base nessas informações, dentre os três grupos políticos que disputavam o espaço público da Corte na virada das décadas de 1820 e 1830, pode-se citar os:', '[{"letra": "A", "texto": "restauradores ou caramurus, que queriam a volta de Dom Pedro I ao Brasil e que além do regime monárquico também defendiam o fim da escravidão como forma de enfraquecer os latifundiários que colaboravam para a fragmentação do Brasil."}, {"letra": "B", "texto": "liberais radicais, conhecidos como exaltados ou jurujubas, que além de defenderem reformas políticas mais amplas e até a instauração de uma Monarquia Parlamentar, também eram a favor do fim da escravidão no Brasil."}, {"letra": "C", "texto": "liberais moderados ou chimangos, grupo formado pela elite agroexportadora do país com tendências políticas variadas, mas que almejava manter a ordem e o Império a qualquer custo, preservando a escravidão e a unidade territorial."}, {"letra": "D", "texto": "restauradores, também conhecidos como farroupilhas, formados basicamente pelas camadas médias urbana e admiradores de D. Pedro I, e que buscavam, além da restauração da Monarquia Parlamentarista, a abolição da escravatura."}, {"letra": "E", "texto": "liberais exaltados ou caramurus, os quais queriam que as províncias tivessem mais liberdade para escolher seus presidentes e juízes, além de poderem elaborar suas próprias leis, independentemente do que estava estabelecido na Constituição de 1824."}]', 'C', 'Os liberais moderados (chimangos) representavam os interesses da grande aristocracia rural brasileira, atuando para manter a centralização política, a ordem social escravista e a unidade territorial do Império durante a crise regencial.', NULL, NULL, 'resumida', FALSE, FALSE, 'bbb50cd07aa4b9e8db4a0a25a54f45be2e4d4e9f83b2dc33200de4715276c9a2', 'cn-2026-dia2.txt'),
('CN', 'História', 'Brasil República', 2026, '2º dia', 'SSPM - Marinha do Brasil', 30, '30', NULL, 'medio', 'Lembranças de um menino operário
Jacob Penteado morava no bairro do Belenzinho, no município de São Paulo, em 1910. Cedo, teve que trabalhar numa fábrica de vidro. Seus colegas de trabalho tinham entre 7 e 14 anos. Ganhavam salários baixíssimos, alimentavam-se mal e levavam surras dos capatazes quando cometiam algum erro. Minha família, de parcos recursos, não poderia manter-me em estabelecimentos de ensino secundário [...]. Trabalhava-se [...] nove horas por dia, inclusive aos sábados... O ambiente era o pior possível [...] Acrescentem-se a isso os maus-tratos dos vidreiros, muito comuns naquele tempo.
(Fonte: Citado em CARONE, Edgard. O movimento operário no Brasil (1877-1944). São Paulo: Difel, 1984. p. 53-54.)', 'O texto acima retrata a situação de um trabalhador, ainda menino, durante o período denominado de República Velha (1889-1930). Sobre as condições da classe trabalhadora desse período, é correto afirmar que:', '[{"letra": "A", "texto": "estava submetida a jornadas de trabalho que ultrapassavam mais de 8 horas por semana, sem ter descanso semanal remunerado; total exclusão política devido a não poder participar do sistema eleitoral; ausência de todo e qualquer tipo de direito trabalhista que garantisse férias, horas extras, aposentadoria e jornada de trabalho definida."}, {"letra": "B", "texto": "não possuía qualquer direito de participação política; sofria exclusão social referente a moradia, saúde pública e saneamento básico; os direitos trabalhistas eram limitados e estavam restritos apenas às indenizações salariais quando havia demissão do trabalho e, as faixas salariais por categoria eram definidas pelos patrões."}, {"letra": "C", "texto": "enfrentavam péssimas condições de vida e de trabalho no início da república, pois, diferentemente dos dias de hoje, as leis trabalhistas eram inexpressivas, limitando-se apenas ao descanso semanal não remunerado e a aposentadoria; o ambiente de trabalho em geral era insalubre, propício a acidentes, e os salários eram baixos."}, {"letra": "D", "texto": "enfrentava exaustivas jornadas de trabalho que poderiam chegar até 15 horas por dia, de segunda a sábado e às vezes aos domingos; problemas de exclusão social devido a moradias precárias, falta de saneamento básico e saúde pública; ausência de direitos trabalhistas, como salário mínimo, férias, horas extras ou jornada definida de trabalho."}, {"letra": "E", "texto": "era submetida a duríssimas jornadas de trabalho que, não raro, ultrapassavam 12 horas por dia; enfrentava péssimas condições de vida residindo em vilas operárias que não possuíam qualquer forma de saneamento básico, e era desprovida de qualquer direito trabalhista, exceto a relacionada à faixa salarial a que a classe estava submetida."}]', 'D', 'Durante a Primeira República, a classe trabalhadora urbana sofria com jornadas exaustivas de até 15 horas diárias, ambientes fabris insalubres, ausência de leis protetivas (sem férias, aposentadorias ou salário mínimo) e moradias precárias.', NULL, NULL, 'resumida', FALSE, FALSE, '8f78e7049216fe5b91e5dc5849894707d11ab4e61bdbb6076c5993064e7b0546', 'cn-2026-dia2.txt'),
('CN', 'História', 'Brasil República', 2026, '2º dia', 'SSPM - Marinha do Brasil', 31, '31', NULL, 'medio', 'O período denominado de "Nova República", compreendido entre os anos de 1985 e 1989, foi caracterizado, no plano político, pelo fim do regime militar-empresarial e pela transição democrática gradual e negociada entre os setores dominantes brasileiros (empresariais e políticos); e, no plano econômico, pela enorme esperança no início do Governo Sarney que foi se transformando paulatinamente em frustração na medida em que os programas de estabilização (Planos Cruzado, Bresser e Verão) não conseguiam debelar o "dragão" da inflação que chegou a 1.783% em 1989- que corroeu a moeda nacional.
(Fonte: PINTO, Eduardo Costa. Nova República (1985-1989): transição democrática, crise da dívida externa, inflação, luta pela apropriação da renda e fim do desenvolvimentismo. Texto para Discussão 007 | 2019. UFRJ. Instituto de Economia. Rio de Janeiro, 2019. Pg.3)', 'Após o fim do regime militar, o governo de José Sarney (1985-1990) marcou o início da chamada Nova República no Brasil. Seu mandato foi caracterizado por grave crise econômica, hiperinflação e sucessivos planos de estabilização. Com relação aos Planos econômicos ocorridos durante o governo Sarney, assinale a opção correta.', '[{"letra": "A", "texto": "O Plano Brasil Novo, lançado em março de 1989 pela ministra da Economia, Fazenda e Planejamento, Zélia Cardoso de Mello, caracterizou-se pelo confisco de depósitos bancários e da caderneta de poupança, com o objetivo de frear a hiperinflação."}, {"letra": "B", "texto": "O Plano Cruzado II, lançado em 21 de novembro de 1986, foi um conjunto de medidas econômicas visando conter a inflação reprimida e o desabastecimento causados pelo primeiro Plano Cruzado."}, {"letra": "C", "texto": "O Plano Bresser, lançado em junho de 1987 pelo ministro Luiz Carlos Bresser-Pereira, foi uma tentativa heterodoxa de conter a hiperinflação, que apesar de sucesso inicial falhou no longo prazo e gerou perdas em poupanças, gerando ações judiciais intermináveis."}, {"letra": "D", "texto": "O Plano Verão, lançado em 16 de janeiro de 1989, foi um pacote econômico de choque para conter a hiperinflação, que incluiu o congelamento de preços e salários, a criação do cruzado novo (equivalente a 1.000 cruzados) e a desindexação da economia."}, {"letra": "E", "texto": "O Plano Cruzado, criado em 28 de fevereiro de 1986, teve como objetivo combater a hiperinflação por meio do congelamento de preços e salários, troca da moeda (cruzeiro por cruzado) e criação de gatilhos (reajustes) salariais."}]', 'E', 'O Plano Cruzado (fevereiro de 1986) buscou debelar a inflação congelando preços e salários, criando a nova moeda (Cruzado) e estabelecendo o "gatilho salarial" que reajustava salários quando a inflação acumulada atingia 20%.', NULL, NULL, 'resumida', FALSE, FALSE, '29d80bb43371c83287cdb26155ee1e4b18e8ed1204740288574b10bc6a7330f2', 'cn-2026-dia2.txt'),
('CN', 'História', 'Brasil República', 2026, '2º dia', 'SSPM - Marinha do Brasil', 32, '32', NULL, 'medio', 'O II PND tratou de incentivar os investimentos da grande empresa privada na produção de bens de capital... Entretanto, a nova política colocava no centro do palco da industrialização brasileira a grande empresa estatal. Os gigantescos investimentos a cargo do sistema Eletrobrás, da Petrobrás, da Embratel e de outras empresas públicas eram, a rigor, o sustentáculo do programa.
(Fonte: FAUSTO, Boris. História do Brasil, Editora da Universidade de São Paulo (EDUSP). São Paulo, 2003. Pg. 496)', 'Durante o período dos governos militares no Brasil (1964-1985), o país passou por significativas transformações econômicas que foram denominadas, por alguns, como "Milagre Econômico". Considerando esse contexto, assinale a opção correta.', '[{"letra": "A", "texto": "Apesar de inicialmente ter possibilitado a geração de muitos empregos, devido a construção de grandes obras, como a ponte Rio-Niterói, no âmbito social, devido ao fato de não terem ocorrido reajustes salariais correspondentes, o \"Milagre Econômico\" acentuou o processo de concentração de renda que intensificou o aumento das desigualdades sociais no Brasil."}, {"letra": "B", "texto": "O projeto não conseguiu, desde o seu início, alcançar patamares positivos como o crescimento do PIB, dessa forma limitando-se apenas a construção da ponte Rio-Niterói, que se tornou o centro da propaganda do governo de que a economia estava em franco crescimento e trazendo melhorias para o país; daí a designação de \"Milagre Econômico\"."}, {"letra": "C", "texto": "Caracterizou-se por maciça entrada de capital estrangeiro possibilitando investimento em grandes obras de infraestrutura, fato que gerou empregos e possibilitou o crescimento salarial da classe trabalhadora, levando o governo a disseminar de que finalmente o país estava vivendo uma plena prosperidade econômica, daí a denominação de \"Milagre Econômico\"."}, {"letra": "D", "texto": "O programa do governo, devido a combinação com uma forte concentração de renda, proporcionou o aumento da desigualdade entre ricos e pobres, o que estimulou nos grandes centros urbanos, a migração de muitos trabalhadores que ficaram desempregados e sem-teto a se voltarem para o campo submetendo-se a trabalhos com baixa remuneração salarial, tornando-se os chamados boias frias."}, {"letra": "E", "texto": "O Produto Interno Bruto (PIB) cresceu de forma inédita durante os governos militares, possibilitando, graças ao controle da inflação e aos empréstimos, utilizados para a modernização e a ampliação do setor industrial, aumentarem os postos de trabalho e o consumo das camadas médias urbanas e trabalhadoras em geral, minimizando, dessa forma, em um primeiro momento, as desigualdades sociais no Brasil."}]', 'A', 'O período do "Milagre Econômico" (1968-1973) atingiu elevadas taxas de crescimento do PIB e realizou grandes obras públicas, porém concentrou renda de forma aguda e arrochou os salários dos trabalhadores, aprofundando as desigualdades sociais.', NULL, NULL, 'resumida', FALSE, FALSE, 'e0d0f9f926b2ba37bc54863ff135bc310d7d117b3018a417ffa0ee8bec41282f', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Genética', 2026, '2º dia', 'SSPM - Marinha do Brasil', 33, '33', NULL, 'facil', NULL, 'A genética estuda os genes e a maneira como eles são transferidos para os descendentes. Com relação a importantes conceitos de genética, assinale a opção correta.', '[{"letra": "A", "texto": "As células do corpo humano têm 46 cromossomos, exceto os gametas, que apresentam 23 cromossomos."}, {"letra": "B", "texto": "Os cromossomos agrupam-se em pares, e os cromossomos de pares diferentes são denominados cromossomos homólogos."}, {"letra": "C", "texto": "O fenótipo refere-se ao conjunto total de genes de um indivíduo, sem influência do ambiente."}, {"letra": "D", "texto": "O alelo dominante manifesta-se apenas no fenótipo de indivíduos heterozigóticos."}, {"letra": "E", "texto": "Nos seres procarióticos, os cromossomos encontram-se no núcleo das células."}]', 'A', 'As células somáticas humanas são diploides ($2n = 46$ cromossomos), ao passo que os gametas são células haploides ($n = 23$ cromossomos).', NULL, NULL, 'resumida', TRUE, FALSE, '85aaee539e3c277e73ee7bcbae432d3a0ef7d98d785263909398e9e8952ad69c', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Tipagem Sanguínea', 2026, '2º dia', 'SSPM - Marinha do Brasil', 34, '34', NULL, 'medio', NULL, 'No Sistema ABO, o sangue é classificado em quatro tipos (A, B, AB e O) e no sistema Rh de classificação, o sangue pode ser do tipo $Rh^+$ (Rh positivo) ou $Rh^-$ (Rh negativo). A respeito do Sistema ABO e do Sistema Rh, analise as afirmativas abaixo e assinale a opção correta.

I- Um indivíduo $A^+$ pode doar sangue para outro indivíduo $A^+$ mas não para um indivíduo $A^-$.
II- Um indivíduo $B^-$ não pode doar sangue para um indivíduo $B^+$.
III- Um indivíduo $O^+$ pode doar sangue para indivíduos de todos os outros tipos sanguíneos, $Rh^+$ ou $Rh^-$.
IV- Um indivíduo $AB^+$ só pode doar sangue para outro indivíduo $AB^+$ mas pode receber sangue de todos os outros tipos sanguíneos, $Rh^+$ ou $Rh^-$.', '[{"letra": "A", "texto": "Apenas as afirmativas I e II são verdadeiras."}, {"letra": "B", "texto": "Apenas as afirmativas I e III são verdadeiras."}, {"letra": "C", "texto": "Apenas as afirmativas II e III são verdadeiras."}, {"letra": "D", "texto": "Apenas as afirmativas I e IV são verdadeiras."}, {"letra": "E", "texto": "Apenas a afirmativa IV é verdadeira."}]', 'D', 'As afirmativas I e IV são verdadeiras. Indivíduos $Rh^+$ possuem o fator Rh na hemácia e não podem doar para $Rh^-$. Indivíduos $AB^+$ possuem antígenos A, B e Rh e nenhum anticorpo anti-A, anti-B ou anti-Rh no plasma, sendo receptores universais.', NULL, '[{"titulo": "Passo 1", "conteudo": "As afirmativas I e IV são verdadeiras. Indivíduos $Rh^+$ possuem o fator Rh na hemácia e não podem doar para $Rh^-$.", "formula": null}, {"titulo": "Conclusão", "conteudo": "Indivíduos $AB^+$ possuem antígenos A, B e Rh e nenhum anticorpo anti-A, anti-B ou anti-Rh no plasma, sendo receptores universais.", "formula": null}]', 'automatica', TRUE, FALSE, '4bb5477abea04fbe305f1093339e901736e445394e34d1a204b3e9f1d758ed13', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Microbiologia e Doenças', 2026, '2º dia', 'SSPM - Marinha do Brasil', 35, '35', NULL, 'facil', NULL, 'Os micro-organismos estão presentes em diversos tipos de ambientes, inclusive no interior do corpo humano. A maioria deles é inofensiva, mas há, no entanto, alguns micro-organismos capazes de causar doenças em seres humanos. A respeito dessas doenças, assinale a opção correta.', '[{"letra": "A", "texto": "Todas as doenças causadas por vírus são transmitidas diretamente de pessoa pra pessoa, pela tosse ou espirros."}, {"letra": "B", "texto": "A leptospirose, causada pelo vírus Leptospira sp., é transmitida pelo contato com a urina de ratos contaminados."}, {"letra": "C", "texto": "A cólera, causada pela bactéria Vibrio cholerae, tem como métodos de prevenção o saneamento básico e bons hábitos de higiene."}, {"letra": "D", "texto": "Os fungos não causam doenças em seres humanos, mas tem elevada importância na produção de alguns medicamentos."}, {"letra": "E", "texto": "Os protozoários podem causar doenças como a amebíase e a giardíase, através da picada de um inseto transmissor, denominado vetor."}]', 'C', 'A cólera é uma infecção bacteriana causada pelo *Vibrio cholerae*, transmitida via fecal-oral por água e alimentos contaminados, sendo prevenível com saneamento básico e higiene.', NULL, NULL, 'resumida', FALSE, FALSE, 'f4be967645d498ae5e6ef47354b4fe9892670b8a407e42bd8fae2ee726c283ad', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Ecologia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 36, '36', NULL, 'facil', '"São formações coletivas em que há cooperação entre os indivíduos da mesma espécie. Os indivíduos são fisicamente independentes e, em geral, capazes de se locomover. Os formigueiros apresentam esse tipo de relação ecológica."
(Adaptado de Geração Alpha Ciências: ensino fundamental: anos finais / André Catani, Gustavo Isaac Killner, João Batista Aguilar, 4. ed. Edições SM, 2022.)', 'Assim, a qual tipo de relação ecológica o texto se refere?', '[{"letra": "A", "texto": "Colônia."}, {"letra": "B", "texto": "Sociedade."}, {"letra": "C", "texto": "Protocooperação."}, {"letra": "D", "texto": "Mutualismo."}, {"letra": "E", "texto": "Competição."}]', 'B', 'A sociedade é uma relação ecológica intraespecífica em que os indivíduos vivem anatomicamente separados, mas organizam-se de forma altamente cooperativa com divisão do trabalho (ex: formigas e abelhas).', NULL, NULL, 'resumida', FALSE, FALSE, '86f901c3b38e010fe1971e0b700c07bae60d9cd83c180e25714e16c231088c79', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Ecologia', 2026, '2º dia', 'SSPM - Marinha do Brasil', 37, '37', NULL, 'facil', NULL, 'O Brasil é um país de dimensões continentais, com diferentes ecossistemas e grande biodiversidade. Clima, relevo e outras condições determinam a formação de ambientes variados no Brasil. A respeito dos biomas brasileiros, assinale a opção INCORRETA.', '[{"letra": "A", "texto": "O Brasil tem seis grandes biomas: Floresta Amazônica, Cerrado, Pantanal, Caatinga, Mata Atlântica e Pampas."}, {"letra": "B", "texto": "A Mata Atlântica é o bioma brasileiro mais devastado, em grande parte pela urbanização, que devastou quase 90% desse bioma."}, {"letra": "C", "texto": "A Floresta Amazônica é o maior bioma brasileiro e tem vários rios, entre eles o rio Amazonas, maior do mundo em volume d''água."}, {"letra": "D", "texto": "A Caatinga é um bioma que só existe no Brasil e se distribui continuamente em todos estados do nordeste brasileiro e em parte do norte de Minas Gerais."}, {"letra": "E", "texto": "O Pantanal distribui-se em todos os estados da região centro-oeste e é muito ameaçado pela pecuária intensiva no estado de Goiás."}]', 'E', 'O Pantanal não abrange todos os estados do Centro-Oeste; localiza-se exclusivamente em partes dos estados do Mato Grosso e Mato Grosso do Sul (não estando presente em Goiás nem no Distrito Federal).', NULL, NULL, 'resumida', FALSE, FALSE, 'cbabd880f5f5ac7946bc5f68873154870ce1aff441410aaf20c189c1d4dddfb9', 'cn-2026-dia2.txt'),
('CN', 'Biologia', 'Genética', 2026, '2º dia', 'SSPM - Marinha do Brasil', 38, '38', NULL, 'medio', 'Um professor de ciências acabou de descobrir que será pai. Ele então pediu aos seus alunos que avaliassem qual a probabilidade de o seu bebê ter o lóbulo da orelha preso. Para isso ele deu duas informações importantes:
I- O professor apresenta o lóbulo da orelha solto, enquanto sua esposa apresenta o lóbulo da orelha preso ao pescoço.
II- A condição de lóbulo da orelha solto é dominante em relação à de lóbulo preso.', 'A partir das informações acima, qual é a resposta correta?', '[{"letra": "A", "texto": "O bebê certamente terá lóbulo da orelha preso, já que a sua mãe apresenta essa característica."}, {"letra": "B", "texto": "O bebê certamente terá lóbulo da orelha solto, já que o seu pai apresenta essa característica, que é dominante."}, {"letra": "C", "texto": "O bebê terá 50% de chance de ter lóbulo da orelha preso se o pai for heterozigótico para essa característica."}, {"letra": "D", "texto": "O bebê terá 50% de chance de ter lóbulo da orelha preso se o pai for homozigótico para essa característica."}, {"letra": "E", "texto": "O bebê terá 75% de chance de ter lóbulo da orelha preso se o pai for heterozigótico para essa característica."}]', 'C', 'A mãe com lóbulo preso é homozigota recessiva ($aa$). Se o pai for heterozigoto ($Aa$), o cruzamento $Aa \times aa$ resulta em $50\%$ de probabilidade para descendentes $aa$ (lóbulo preso).', NULL, NULL, 'resumida', TRUE, FALSE, 'c09d0d66bc1709fd886f065c040d2a1fe69563f5a58681e677b04db5b3022db5', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Dinâmica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 39, '39', NULL, 'medio', '[DESCRIÇÃO DA IMAGEM: Figura mostrando um bloco de massa M repousando sobre um plano inclinado que faz um ângulo $\theta$ com a horizontal. Uma força horizontal $|\vec{F}|$ é aplicada apontando para a esquerda (empurrando o bloco horizontalmente na direção da rampa).]', 'A figura acima mostra um bloco de massa M que desce um plano inclinado sem atrito puxado para baixo com uma força horizontal $|\vec{F}|$.
Com base nessas informações, qual a opção que apresenta o módulo da força normal aplicada ao bloco M pela superfície do plano inclinado?', '[{"letra": "A", "texto": "$|\\vec{N}| = m g \\cos\\theta - F \\operatorname{sen}\\theta$"}, {"letra": "B", "texto": "$|\\vec{N}| = m g \\operatorname{sen}\\theta + F \\cos\\theta$"}, {"letra": "C", "texto": "$|\\vec{N}| = m g \\cos\\theta - F \\cos\\theta$"}, {"letra": "D", "texto": "$|\\vec{N}| = F m \\cos\\theta + F \\operatorname{sen}\\theta$"}, {"letra": "E", "texto": "$|\\vec{N}| = F g \\cos\\theta - F \\operatorname{sen}\\theta$"}]', 'A', 'Decompondo as forças na direção perpendicular ao plano inclinado, a componente do peso empurra o bloco contra o plano ($M g \cos\theta$) e a força horizontal $\vec{F}$ atua puxando-o parcialmente para fora do plano ($F \operatorname{sen}\theta$), resultando em $N = M g \cos\theta - F \operatorname{sen}\theta$.', 'Figura mostrando um bloco de massa M repousando sobre um plano inclinado que faz um ângulo $\theta$ com a horizontal. Uma força horizontal $|\vec{F}|$ é aplicada apontando para a esquerda (empurrando o bloco horizontalmente na direção da rampa).', NULL, 'resumida', TRUE, FALSE, 'e55786356e32f81062ed2569bfd8a551b21f8f890c41e9a1d79dce99f871ac66', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Eletrodinâmica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 40, '40', NULL, 'medio', '[DESCRIÇÃO DA IMAGEM: Diagrama de um circuito elétrico em paralelo submetido a uma tensão $U = 120\text{ V}$. Os ramos do circuito contêm: 1 micro-ondas MO ($600\text{ W}$), 1 chuveiro CH ($4800\text{ W}$) e 4 lâmpadas L ($60\text{ W}$ cada).]', 'A figura acima representa um circuito no qual há as siglas dos aparelhos elétricos: MO - micro-onda, CH - chuveiro e L - lâmpada, com suas respectivas potências.
Com base nessas informações, a energia em kWh consumida no circuito durante o uso diário de 3 horas em um mês é de aproximadamente:', '[{"letra": "A", "texto": "508"}, {"letra": "B", "texto": "564"}, {"letra": "C", "texto": "658"}, {"letra": "D", "texto": "618"}, {"letra": "E", "texto": "764"}]', 'A', 'A potência total dos aparelhos é $P = 600 + 4800 + (4 \times 60) = 5640\text{ W} = 5,64\text{ kW}$. Em 30 dias de uso diário de 3 horas ($t = 90\text{ h}$), o consumo é $E = 5,64 \times 90 = 507,6\text{ kWh} \approx 508\text{ kWh}$.', 'Diagrama de um circuito elétrico em paralelo submetido a uma tensão $U = 120\text{ V}$. Os ramos do circuito contêm: 1 micro-ondas MO ($600\text{ W}$), 1 chuveiro CH ($4800\text{ W}$) e 4 lâmpadas L ($60\text{ W}$ cada).', NULL, 'resumida', TRUE, FALSE, '8a831146538a2332505ea928483ea1337c5b049fd1d456d7d5bae8b12480c43c', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Óptica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 41, '41', NULL, 'facil', NULL, 'Considere as afirmativas abaixo sobre o fenômeno de refração da luz:

I- A velocidade da luz é diretamente proporcional ao índice de refração.
II- A refração é um fenômeno no qual a luz sempre sofre desvio.
III- A luz, ao incidir obliquamente em um dióptro plano, pode sofrer reflexão total.
IV- A luz, ao incidir obliquamente em um dióptro, pode sofrer refração aproximando-se da reta normal.

Assinale a opção correta.', '[{"letra": "A", "texto": "Apenas as afirmativas I e II são verdadeiras."}, {"letra": "B", "texto": "Apenas as afirmativas III e IV são verdadeiras."}, {"letra": "C", "texto": "Apenas as afirmativas II e IV são verdadeiras."}, {"letra": "D", "texto": "Apenas as alternativas I, II e III são verdadeiras."}, {"letra": "E", "texto": "As afirmativas I, II, III e IV são verdadeiras."}]', 'B', 'As afirmações III e IV são corretas. A afirmativa I está incorreta pois a velocidade é inversamente proporcional ao índice de refração ($v = c/n$), e a II é incorreta pois na incidência normal a luz é refratada sem sofrer desvio angular.', NULL, NULL, 'resumida', TRUE, FALSE, 'a327a093c697f13ce7df3ee09d1bb463b5222925d321c3e0a05e520daa39f3b5', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Dinâmica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 42, '42', NULL, 'medio', NULL, 'Em uma máquina há duas polias que funcionam num processo de transmissão de movimento por correia, a primeira tem raio de 15 cm e 150 rotações por segundo. Qual é a quantidade de voltas em um minuto da segunda polia se ela tiver um raio de 30 cm?', '[{"letra": "A", "texto": "1400"}, {"letra": "B", "texto": "2600"}, {"letra": "C", "texto": "3200"}, {"letra": "D", "texto": "3600"}, {"letra": "E", "texto": "4500"}]', 'E', 'Pela transmissão de movimento por correia, $f_1 \cdot R_1 = f_2 \cdot R_2 \implies 150 \times 15 = f_2 \times 30 \implies f_2 = 75\text{ rps}$. Em 1 minuto ($60\text{ s}$), o número total de voltas da segunda polia é $75 \times 60 = 4500\text{ voltas}$.', NULL, NULL, 'resumida', TRUE, FALSE, '30a5ccf9279e83fe5159d900a8acd638440ef9cb38a70c8ea014d790a7da33af', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Termologia e Calorimetria', 2026, '2º dia', 'SSPM - Marinha do Brasil', 43, '43', NULL, 'facil', '[DESCRIÇÃO DA IMAGEM: Gráfico cartesiano relacionando uma escala termométrica $^\circ\text{H}$ (eixo vertical) com a escala Celsius $^\circ\text{C}$ (eixo horizontal). A reta cruza o eixo vertical em $(0, -20)$ e passa pelo ponto $(80, 140)$.]', 'A figura acima mostra a correspondência de uma escala termométrica H com a escala termométrica Celsius.
Com base nessas informações, uma temperatura de $100^\circ\text{C}$ terá um valor correspondente na escala H igual a:', '[{"letra": "A", "texto": "$120^\\circ\\text{H}$"}, {"letra": "B", "texto": "$140^\\circ\\text{H}$"}, {"letra": "C", "texto": "$160^\\circ\\text{H}$"}, {"letra": "D", "texto": "$180^\\circ\\text{H}$"}, {"letra": "E", "texto": "$200^\\circ\\text{H}$"}]', 'D', 'A equação de conversão linear entre as escalas é dada por $\frac{H - (-20)}{140 - (-20)} = \frac{C - 0}{80 - 0} \implies H + 20 = 2C$. Para $C = 100^\circ\text{C}$, obtém-se $H = 2(100) - 20 = 180^\circ\text{H}$.', 'Gráfico cartesiano relacionando uma escala termométrica $^\circ\text{H}$ (eixo vertical) com a escala Celsius $^\circ\text{C}$ (eixo horizontal). A reta cruza o eixo vertical em $(0, -20)$ e passa pelo ponto $(80, 140)$.', NULL, 'resumida', TRUE, FALSE, 'cbedd3e84b470287bd572c0e344216bb5ec97307ad23077a1759fb273bf6a9ef', 'cn-2026-dia2.txt'),
('CN', 'Física', 'Conservação', 2026, '2º dia', 'SSPM - Marinha do Brasil', 44, '44', NULL, 'medio', '[DESCRIÇÃO DA IMAGEM: Figura mostrando uma rampa inclinada de altura $h = 1\text{ m}$. Um bloco de massa $3\text{ kg}$ desliza do topo da rampa e, na superfície horizontal no pé da rampa, atinge uma mola que é comprimida de uma distância $x$.]', 'A figura acima mostra um bloco de massa 3 kg que desliza a partir de 1 m de altura na superfície e em seguida atinge uma mola de constante elástica igual a $3 \cdot 10^3\text{ N/m}$, comprimindo-a 10 cm.
Determine o valor da energia dissipada na situação descrita no sistema acima e assinale a opção correta.
Dado: aceleração da gravidade $10\text{ m/s}^2$', '[{"letra": "A", "texto": "10 J"}, {"letra": "B", "texto": "13 J"}, {"letra": "C", "texto": "15 J"}, {"letra": "D", "texto": "17 J"}, {"letra": "E", "texto": "20 J"}]', 'C', 'A energia mecânica inicial é $E_i = m g h = 3 \times 10 \times 1 = 30\text{ J}$. A energia elástica final na mola com $x = 0,1\text{ m}$ é $E_f = \frac{3000 \times (0,1)^2}{2} = 15\text{ J}$. A energia dissipada pelo atrito é $30 - 15 = 15\text{ J}$.', 'Figura mostrando uma rampa inclinada de altura $h = 1\text{ m}$. Um bloco de massa $3\text{ kg}$ desliza do topo da rampa e, na superfície horizontal no pé da rampa, atinge uma mola que é comprimida de uma distância $x$.', '[{"titulo": "Passo 1", "conteudo": "A energia mecânica inicial é $E_i = m g h = 3 \\times 10 \\times 1 = 30\\text{ J}$. A energia elástica final na mola com $x = 0,1\\text{ m}$ é $E_f = \\frac{3000 \\times (0,1)^2}{2} = 15\\text{ J}$.", "formula": null}, {"titulo": "Conclusão", "conteudo": "A energia dissipada pelo atrito é $30 - 15 = 15\\text{ J}$.", "formula": null}]', 'automatica', TRUE, FALSE, '4fae903b4f6e246a428addbfb5aba6797ac1481873110e79038b3f83f47de922', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Estequiometria', 2026, '2º dia', 'SSPM - Marinha do Brasil', 45, '45', NULL, 'medio', NULL, 'Em um experimento, foram colocados para reagir 213g de gás cloro e fósforo sólido em excesso, produzindo a reação balanceada abaixo:

$$P_{4(s)} + 6 Cl_{2(g)} \rightarrow 4 PCl_{3(l)}$$

Calcule a massa de cloreto de fósforo produzido e assinale a opção correta.
Dados: massas molares: $Cl = 35,5\text{ g/mol}$; $P = 31\text{ g/mol}$.', '[{"letra": "A", "texto": "412g"}, {"letra": "B", "texto": "350g"}, {"letra": "C", "texto": "275g"}, {"letra": "D", "texto": "206g"}, {"letra": "E", "texto": "137g"}]', 'C', 'A massa molar de $6 Cl_2$ é $6 \times 71 = 426\text{ g}$ e produz $4 PCl_3$ ($4 \times 137,5 = 550\text{ g}$). Como foram reajustados $213\text{ g}$ de $Cl_2$ (metade da proporção molar), a massa produzida de $PCl_3$ será $550 / 2 = 275\text{ g}$.', NULL, '[{"titulo": "Passo 1", "conteudo": "A massa molar de $6 Cl_2$ é $6 \\times 71 = 426\\text{ g}$ e produz $4 PCl_3$ ($4 \\times 137,5 = 550\\text{ g}$).", "formula": null}, {"titulo": "O que o enunciado dá", "conteudo": "Como foram reajustados $213\\text{ g}$ de $Cl_2$ (metade da proporção molar), a massa produzida de $PCl_3$ será $550 / 2 = 275\\text{ g}$.", "formula": null}]', 'automatica', TRUE, FALSE, '1d1b40022ea77704bb899d003ca19502916ea27873846ef40c99c029420dcfdc', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Separação de Misturas', 2026, '2º dia', 'SSPM - Marinha do Brasil', 46, '46', NULL, 'facil', NULL, 'Assinale a opção que apresenta apenas misturas homogêneas.', '[{"letra": "A", "texto": "Água e óleo; água e álcool; água e sal; ar atmosférico."}, {"letra": "B", "texto": "Água líquida e gelo; gás cloro e gás nitrogênio; granito."}, {"letra": "C", "texto": "Areia da praia; sal e açúcar, água e álcool; sopa de legumes."}, {"letra": "D", "texto": "Água e álcool; ar atmosférico; mistura de gases para mergulho; água e sal."}, {"letra": "E", "texto": "Água e óleo; mistura de gases para mergulho; água com gás; ar atmosférico."}]', 'D', 'A alternativa D reúne exclusivamente misturas homogêneas (sistemas monofásicos): água e álcool (solução líquida), ar atmosférico, mistura gasosa para mergulho e água com sal dissolvido.', NULL, NULL, 'resumida', TRUE, FALSE, 'ce86a3ded296f35b049f93749686edca4db6fc890912d71e44c0575dfba9b6a0', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Reações Químicas', 2026, '2º dia', 'SSPM - Marinha do Brasil', 47, '47', NULL, 'facil', NULL, 'Balanceie a reação de combustão do octano apresentada abaixo e assinale a opção com os índices estequiométricos corretos da esquerda para a direita:

$$C_8 H_{18} + O_2 \rightarrow CO_2 + H_2 O$$', '[{"letra": "A", "texto": "1, 5, 6, 8"}, {"letra": "B", "texto": "2, 10, 3, 7"}, {"letra": "C", "texto": "2, 10, 5, 5"}, {"letra": "D", "texto": "3, 12, 8, 9"}, {"letra": "E", "texto": "2, 25, 16, 18"}]', 'E', 'Realizando o balanceamento da combustão completa do octano para obter coeficientes inteiros mínimos: $2 C_8 H_{18} + 25 O_2 \rightarrow 16 CO_2 + 18 H_2 O$. Os coeficientes ordenados são 2, 25, 16, 18.', NULL, NULL, 'resumida', TRUE, FALSE, '7a82d081abe383722bea3d406676ecb335e8f63e4dbca4c43b53fc5e597fb336', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Atomística e Tabela Periódica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 48, '48', NULL, 'facil', NULL, 'Sobre a estrutura do átomo e os modelos atômicos, assinale a opção correta.', '[{"letra": "A", "texto": "O átomo é composto, principalmente, de três partículas subatômicas, conhecidas como prótons, nêutrons e elétrons."}, {"letra": "B", "texto": "O primeiro modelo atômico a prever a presença de elétrons na estrutura do átomo foi o modelo de Dalton."}, {"letra": "C", "texto": "O modelo atômico de Rutherford é conhecido como bola de bilhar."}, {"letra": "D", "texto": "Os nêutrons são partículas com massa desprezível que circulam o núcleo do átomo, equilibrando as cargas."}, {"letra": "E", "texto": "Thomson foi o cientista que propôs a teoria de orbitais moleculares, propondo a presença de nêutrons no núcleo atômico."}]', 'A', 'A estrutura atômica clássica é formada por três partículas fundamentais principais: prótons e nêutrons situados no núcleo, e elétrons distribuídos na eletrosfera.', NULL, NULL, 'resumida', TRUE, FALSE, 'fc3947697d955667af97590b6fea69879743219c3f7e14bee1c5c9cdd4c15785', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Química Orgânica', 2026, '2º dia', 'SSPM - Marinha do Brasil', 49, '49', NULL, 'medio', NULL, 'A reação entre um ácido forte e uma base forte é uma reação de neutralização. Em um recipiente cilíndrico, foram misturados ácido nítrico e hidróxido de sódio. No mesmo laboratório, em um recipiente esférico, foram misturados ácido sulfúrico e hidróxido de potássio.
Considerando que todos os reagentes estão em proporção estequiométrica e que as reações foram completas, assinale a opção correta.', '[{"letra": "A", "texto": "Após as reações, no recipiente cilíndrico haverá nitrito de sódio e água."}, {"letra": "B", "texto": "Após as reações, no recipiente esférico haverá sulfato de potássio e água."}, {"letra": "C", "texto": "Após as reações, no recipiente esférico haverá sulfeto de sódio e água."}, {"letra": "D", "texto": "Após as reações, no recipiente cilíndrico haverá nitreto de sódio e água."}, {"letra": "E", "texto": "Após as reações, haverá apenas água nos dois recipientes."}]', 'B', 'A reação de neutralização total entre o ácido sulfúrico ($H_2 SO_4$) e o hidróxido de potássio ($KOH$) produz o sal sulfato de potássio ($K_2 SO_4$) e água ($H_2 O$).', NULL, NULL, 'resumida', TRUE, FALSE, 'eeb0c695e585abbfb996d416a26ceab9977e3717a1ea1db87d843a13114bc8a3', 'cn-2026-dia2.txt'),
('CN', 'Química', 'Ligações Químicas', 2026, '2º dia', 'SSPM - Marinha do Brasil', 50, '50', NULL, 'facil', NULL, 'Sobre ligações químicas e camada de valência, assinale a opção correta.', '[{"letra": "A", "texto": "A ligação química entre um metal e um não-metal é chamada de ligação covalente."}, {"letra": "B", "texto": "A ligação iônica é a ligação que se forma quando há compartilhamento de elétrons."}, {"letra": "C", "texto": "A ligação entre não-metais é chamada de ligação ametálica."}, {"letra": "D", "texto": "Os gases nobres normalmente não fazem ligações porque suas camadas de valência são completas."}, {"letra": "E", "texto": "Quando um metal e um não-metal fazem uma ligação química, suas camadas de valência deixam de existir."}]', 'D', 'Os gases nobres apresentam a camada de valência completa (com 8 elétrons, ou 2 no caso do hélio), motivo pelo qual possuem elevada estabilidade química e raramente participam de ligações.', NULL, NULL, 'resumida', TRUE, FALSE, 'a9af85848361c22d86e9d3da003c11abee01a77362f2acd1087390803260353e', 'cn-2026-dia2.txt');
-- ─── 1. Garante que as matérias existem ─────────────────────────────
INSERT INTO materias (nome, descricao, icone_emoji)
SELECT DISTINCT s.materia_nome, 'Importada do banco de questões oficial', '📚'
FROM stg_questoes s
WHERE s.materia_nome IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM materias m WHERE m.nome = s.materia_nome);

-- ─── 2. Garante que os assuntos existem ─────────────────────────────
INSERT INTO assuntos (materia_id, nome, ordem)
SELECT DISTINCT m.id, s.assunto_nome, 0
FROM stg_questoes s
JOIN materias m ON m.nome = s.materia_nome
WHERE s.assunto_nome IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM assuntos a
    WHERE a.materia_id = m.id AND a.nome = s.assunto_nome
  );

-- ─── 3. Vincula matéria ao concurso (alimenta os filtros da UI) ─────
INSERT INTO concurso_materias (concurso_id, materia_id)
SELECT DISTINCT c.id, m.id
FROM stg_questoes s
JOIN concursos c ON c.sigla = s.concurso_sigla
JOIN materias  m ON m.nome  = s.materia_nome
WHERE NOT EXISTS (
  SELECT 1 FROM concurso_materias cm
  WHERE cm.concurso_id = c.id AND cm.materia_id = m.id
);

-- ─── 4. Insere as questões ──────────────────────────────────────────
INSERT INTO questoes (
  concurso_id, materia_id, assunto_id,
  enunciado, texto_base, alternativas, resposta_correta, explicacao,
  ano, banca, dificuldade, dia_prova, numero_ordem, numero_original,
  area_conhecimento, figura_descricao, resolucao_passos, resolucao_status,
  precisa_resolucao, anulada, hash_conteudo, arquivo_origem, ativa
)
SELECT
  c.id, m.id, a.id,
  s.enunciado, s.texto_base, s.alternativas, s.resposta_correta, s.explicacao,
  s.ano, s.banca, s.dificuldade::dificuldade_tipo, s.dia_prova,
  s.numero_ordem, s.numero_original, s.area_conhecimento, s.figura_descricao,
  s.resolucao_passos, s.resolucao_status, s.precisa_resolucao, s.anulada,
  s.hash_conteudo, s.arquivo_origem, TRUE
FROM stg_questoes s
JOIN concursos c ON c.sigla = s.concurso_sigla
JOIN materias  m ON m.nome  = s.materia_nome
JOIN assuntos  a ON a.materia_id = m.id AND a.nome = s.assunto_nome
WHERE s.resposta_correta IS NOT NULL
ON CONFLICT (hash_conteudo) DO NOTHING;

-- ─── 5. Registra a importação no armazém ────────────────────────────
INSERT INTO questao_importadas (hash_conteudo, questao_id, arquivo_origem, status)
SELECT s.hash_conteudo, q.id, s.arquivo_origem, 'aceita'::questao_importada_status
FROM stg_questoes s
JOIN questoes q ON q.hash_conteudo = s.hash_conteudo
WHERE NOT EXISTS (
  SELECT 1 FROM questao_importadas qi WHERE qi.hash_conteudo = s.hash_conteudo
);

COMMIT;

SELECT
  'CN — lote 2/2' AS seed,
  (SELECT COUNT(*) FROM questoes) AS total_questoes_no_banco;
